-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Booth = {
		Amount = 100, 
		Tier = "Easy", 
		Description = "Sell {Amount} Pets at a Trading Booth"
	}, 
	Eggs = {
		Amount = 25000, 
		Tier = "Medium", 
		Egg = {
			Pattern = "Tropical Doodle"
		}
	}, 
	Coins = {
		Amount = 1500, 
		Tier = "Hard", 
		Description = "Break {Amount} Giant Doodle Oasis Chests!", 
		Coin = {
			Pattern = "Giant Doodle Oasis"
		}
	}
};
