-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Eggs = {
		Amount = 3000, 
		Tier = "Easy", 
		Description = "Hatch {Amount} Flower Doodle Eggs!", 
		Egg = {
			Pattern = "Flower Doodle"
		}
	}, 
	Coins = {
		Amount = 3000, 
		Tier = "Medium", 
		Coin = {
			Pattern = "Coin"
		}
	}, 
	Eggs2 = {
		Amount = 30, 
		Tier = "Hard", 
		Egg = {
			Pet = "460", 
			Attributes = {
				sh = true
			}
		}
	}
};
