-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Eggs = {
		Amount = 500, 
		Tier = "Easy", 
		Description = "Hatch {Amount} Mythicals from the Doodle Barn Egg!", 
		Egg = {
			Pattern = "Barn Doodle", 
			Rarity = "Mythical"
		}
	}, 
	Coins = {
		Amount = 500, 
		Tier = "Medium", 
		Coin = {
			Pattern = "Giant Doodle Barn Chest"
		}
	}, 
	Eggs2 = {
		Amount = 30, 
		Tier = "Hard", 
		Description = "Hatch {Amount} Secret Pets from the Doodle Barn Egg!", 
		Egg = {
			Pattern = "Barn Doodle", 
			Rarity = "Secret"
		}
	}
};
