-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Eggs = {
		Amount = 15000, 
		Tier = "Easy", 
		Egg = {
			Pattern = "Gem Doodle"
		}
	}, 
	Coins = {
		Amount = 500, 
		Tier = "Medium", 
		Coin = {
			Pattern = "Chest"
		}
	}, 
	Eggs2 = {
		Amount = 10, 
		Tier = "Hard", 
		Description = "Hatch {Amount} Secret Pets from Gem Eggs!", 
		Egg = {
			Pattern = "Gem Doodle", 
			Rarity = "Secret"
		}
	}
};
