-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Golden = {
		Amount = 500, 
		Tier = "Easy", 
		Description = "Successfully Gold {Amount} Doodle Rhinos!"
	}, 
	Rainbow = {
		Amount = 250, 
		Tier = "Medium", 
		Description = "Successfully Rainbow {Amount} Doodle Rhinos!"
	}, 
	Auction = {
		Amount = 100000000000, 
		Tier = "Hard", 
		Description = "Earn {Amount.Short} Diamonds at Auction!"
	}
};
