-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Enchant = {
		Amount = 50, 
		Tier = "Easy", 
		Description = "Enchant {Amount} Pets with Cartoon Coins!"
	}, 
	ServerBoosts = {
		Amount = 500, 
		Tier = "Medium", 
		Description = "Activate {Amount} Server Triple Damage Boosts!"
	}, 
	Rainbow = {
		Amount = 750, 
		Tier = "Hard", 
		Description = "Successfully Rainbow {Amount} Doodle Sloths!"
	}
};
