-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Coins = {
		Amount = 750, 
		Tier = "Easy", 
		Coin = {
			Pattern = "Safe"
		}
	}, 
	Daycare = {
		Amount = 1000000000000, 
		Tier = "Medium", 
		Description = "Collect {Amount.Short} Cartoon Coins from Daycare!"
	}, 
	Merchant = {
		Amount = 200, 
		Tier = "Hard", 
		Description = "Buy {Amount} Mythical Pets from Traveling Merchant!"
	}
};
