-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Teamwork = {
		canDrop = true, 
		dropWeight = 125, 
		isUnique = false, 
		tiers = { {
				title = "Teamwork", 
				desc = "Pets do more damage together with this pet", 
				value = 1.15
			}, {
				title = "Super Teamwork", 
				desc = "Pets do much more damage together with this pet", 
				value = 1.3
			} }
	}
};
