-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Cartoon Coins"] = {
		canDrop = true, 
		dropWeight = 25, 
		isUnique = false, 
		tiers = { {
				title = "Cartoon Coins I", 
				desc = "Pet earns +15% more Cartoon Coins", 
				value = 1.15
			}, {
				title = "Cartoon Coins II", 
				desc = "Pet earns +30% more Cartoon Coins", 
				value = 1.3
			}, {
				title = "Cartoon Coins III", 
				desc = "Pet earns +50% more Cartoon Coins", 
				value = 1.5
			}, {
				title = "Cartoon Coins IV", 
				desc = "Pet earns +75% more Cartoon Coins", 
				value = 1.75
			}, {
				title = "Cartoon Coins V", 
				desc = "Pet earns +100% more Cartoon Coins", 
				value = 2
			} }
	}
};
