-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Diamonds = {
		canDrop = true, 
		dropWeight = 75, 
		isUnique = false, 
		tiers = { {
				title = "Diamonds I", 
				desc = "Pet earns +10% more Diamonds", 
				value = 1.1
			}, {
				title = "Diamonds II", 
				desc = "Pet earns +20% more Diamonds", 
				value = 1.2
			}, {
				title = "Diamonds III", 
				desc = "Pet earns +35% more Diamonds", 
				value = 1.35
			}, {
				title = "Diamonds IV", 
				desc = "Pet earns +50% more Diamonds", 
				value = 1.5
			}, {
				title = "Diamonds V", 
				desc = "Pet earns +65% more Diamonds", 
				value = 1.65
			} }
	}
};
