-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Tech Coins"] = {
		canDrop = true, 
		dropWeight = 30, 
		isUnique = false, 
		tiers = { {
				title = "Tech Coins I", 
				desc = "Pet earns +15% more Tech Coins", 
				value = 1.15
			}, {
				title = "Tech Coins II", 
				desc = "Pet earns +30% more Tech Coins", 
				value = 1.3
			}, {
				title = "Tech Coins III", 
				desc = "Pet earns +50% more Tech Coins", 
				value = 1.5
			}, {
				title = "Tech Coins IV", 
				desc = "Pet earns +75% more Tech Coins", 
				value = 1.75
			}, {
				title = "Tech Coins V", 
				desc = "Pet earns +100% more Tech Coins", 
				value = 2
			} }
	}
};
