-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Presents = {
		canDrop = true, 
		dropWeight = 100, 
		isUnique = false, 
		tiers = { {
				title = "Gifts I", 
				desc = "Presents damaged by this pet yield +35% rewards", 
				value = 1.35
			}, {
				title = "Gifts II", 
				desc = "Presents damaged by this pet yield +70% rewards", 
				value = 1.7
			}, {
				title = "Gifts III", 
				desc = "Presents damaged by this pet yield +100% rewards", 
				value = 2
			} }
	}
};
