-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Coins = {
		canDrop = true, 
		dropWeight = 75, 
		isUnique = false, 
		tiers = { {
				title = "Coins I", 
				desc = "Pet earns +15% more Regular Coins", 
				value = 1.15
			}, {
				title = "Coins II", 
				desc = "Pet earns +30% more Regular Coins", 
				value = 1.3
			}, {
				title = "Coins III", 
				desc = "Pet earns +50% more Regular Coins", 
				value = 1.5
			}, {
				title = "Coins IV", 
				desc = "Pet earns +75% more Regular Coins", 
				value = 1.75
			}, {
				title = "Coins V", 
				desc = "Pet earns +100% more Regular Coins", 
				value = 2
			} }
	}
};
