-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Chests = {
		canDrop = true, 
		dropWeight = 100, 
		isUnique = false, 
		tiers = { {
				title = "Chest Breaker I", 
				desc = "Pet deals +50% more damage to Chests", 
				value = 1.5
			}, {
				title = "Chest Breaker II", 
				desc = "Pet deals +100% more damage to Chests", 
				value = 2
			}, {
				title = "Chest Breaker III", 
				desc = "Pet deals +150% more damage to Chests", 
				value = 2.5
			} }
	}
};
