-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Companion = {
		canDrop = false, 
		dropWeight = 6, 
		isUnique = true, 
		tiers = { {
				title = "Companion I", 
				desc = "Pet will always be 50% as strong as your best pets.", 
				value = 0.5
			}, {
				title = "Companion II", 
				desc = "Pet will always be 60% as strong as your best pets.", 
				value = 0.6
			}, {
				title = "Companion III", 
				desc = "Pet will always be 75% as strong as your best pets.", 
				value = 0.75
			} }
	}
};
