-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Strength = {
		canDrop = true, 
		dropWeight = 150, 
		isUnique = false, 
		tiers = { {
				title = "Strength I", 
				desc = "Pet does +15% more damage", 
				value = 1.15
			}, {
				title = "Strength II", 
				desc = "Pet does +30% more damage", 
				value = 1.3
			}, {
				title = "Strength III", 
				desc = "Pet does +50% more damage", 
				value = 1.5
			}, {
				title = "Strength IV", 
				desc = "Pet does +70% more damage", 
				value = 1.7
			}, {
				title = "Strength V", 
				desc = "Pet does +100% more damage", 
				value = 2
			} }
	}
};
