-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Diamond Bag Luck"] = {
		canDrop = true, 
		dropWeight = 20, 
		isUnique = false, 
		tiers = { {
				title = "Diamond Bag Luck I", 
				desc = "+2% Diamond Bag drop chance (Diamond Mine)", 
				value = 0.02
			}, {
				title = "Diamond Bag Luck II", 
				desc = "+4% Diamond Bag drop chance (Diamond Mine)", 
				value = 0.04
			}, {
				title = "Diamond Bag Luck III", 
				desc = "+6% Diamond Bag drop chance (Diamond Mine)", 
				value = 0.06
			}, {
				title = "Diamond Bag Luck IV", 
				desc = "+8% Diamond Bag drop chance (Diamond Mine)", 
				value = 0.08
			}, {
				title = "Diamond Bag Luck V", 
				desc = "+10% Diamond Bag drop chance (Diamond Mine)", 
				value = 0.1
			} }
	}
};
