-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Shadow Coins"] = {
		canDrop = false, 
		dropWeight = 0, 
		isUnique = false, 
		tiers = { {
				title = "Shadow Coins I", 
				desc = "Pet earns +15% more Shadow Coins", 
				value = 1.15
			}, {
				title = "Shadow Coins II", 
				desc = "Pet earns +30% more Shadow Coins", 
				value = 1.3
			}, {
				title = "Shadow Coins III", 
				desc = "Pet earns +50% more Shadow Coins", 
				value = 1.5
			}, {
				title = "Shadow Coins IV", 
				desc = "Pet earns +75% more Shadow Coins", 
				value = 1.75
			}, {
				title = "Shadow Coins V", 
				desc = "Pet earns +100% more Shadow Coins", 
				value = 2
			} }
	}
};
