-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Rainbow Coins"] = {
		canDrop = true, 
		dropWeight = 30, 
		isUnique = false, 
		tiers = { {
				title = "Rainbow Coins I", 
				desc = "Pet earns +15% more Rainbow Coins", 
				value = 1.15
			}, {
				title = "Rainbow Coins II", 
				desc = "Pet earns +30% more Rainbow Coins", 
				value = 1.3
			}, {
				title = "Rainbow Coins III", 
				desc = "Pet earns +50% more Rainbow Coins", 
				value = 1.5
			}, {
				title = "Rainbow Coins IV", 
				desc = "Pet earns +75% more Rainbow Coins", 
				value = 1.75
			}, {
				title = "Rainbow Coins V", 
				desc = "Pet earns +100% more Rainbow Coins", 
				value = 2
			} }
	}
};
