-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Fantasy Coins"] = {
		canDrop = true, 
		dropWeight = 40, 
		isUnique = false, 
		tiers = { {
				title = "Fantasy Coins I", 
				desc = "Pet earns +15% more Fantasy Coins", 
				value = 1.15
			}, {
				title = "Fantasy Coins II", 
				desc = "Pet earns +30% more Fantasy Coins", 
				value = 1.3
			}, {
				title = "Fantasy Coins III", 
				desc = "Pet earns +50% more Fantasy Coins", 
				value = 1.5
			}, {
				title = "Fantasy Coins IV", 
				desc = "Pet earns +75% more Fantasy Coins", 
				value = 1.75
			}, {
				title = "Fantasy Coins V", 
				desc = "Pet earns +100% more Fantasy Coins", 
				value = 2
			} }
	}
};
