-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Agility = {
		canDrop = true, 
		dropWeight = 200, 
		isUnique = false, 
		tiers = { {
				title = "Agility I", 
				desc = "Pet moves 20% faster", 
				value = 1.2
			}, {
				title = "Agility II", 
				desc = "Pet moves 35% faster", 
				value = 1.35
			}, {
				title = "Agility III", 
				desc = "Pet moves 50% faster", 
				value = 1.5
			} }
	}
};
