-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Multiplier Madness"] = {
		canDrop = true, 
		dropWeight = 15, 
		isUnique = false, 
		tiers = { {
				title = "Multiplier Madness I", 
				desc = "Pet earns +15% more Coins during random multipliers", 
				value = 0.15
			}, {
				title = "Multiplier Madness II", 
				desc = "Pet earns +30% more Coins during random multipliers", 
				value = 0.3
			}, {
				title = "Multiplier Madness III", 
				desc = "Pet earns +50% more Coins during random multipliers", 
				value = 0.5
			}, {
				title = "Multiplier Madness IV", 
				desc = "Pet earns +75% more Coins during random multipliers", 
				value = 0.75
			}, {
				title = "Multiplier Madness V", 
				desc = "Pet earns +100% more Coins during random multipliers", 
				value = 1
			} }
	}
};
