-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Open Giftboxes"] = { {
			title = "Gifts", 
			desc = "Open 1 giftbox", 
			amount = 1, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Slots", 
			reward = 5
		}, {
			title = "Unboxing", 
			desc = "Open 3 giftboxes", 
			amount = 3, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Slots", 
			reward = 5
		}, {
			title = "Unboxing Pro", 
			desc = "Open 10 giftboxes", 
			amount = 10, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Slots", 
			reward = 5
		}, {
			title = "Unbox Therapy", 
			desc = "Open 20 giftboxes", 
			amount = 20, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Slots", 
			reward = 5
		} }
};
