-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Fruits = { {
			title = "Fruits", 
			desc = "Break 50 Fruits", 
			amount = 50, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 5000
		}, {
			title = "Fruits II", 
			desc = "Break 250 Fruits", 
			amount = 250, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 25000
		}, {
			title = "Fruits III", 
			desc = "Break 500 Fruits", 
			amount = 500, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 75000
		}, {
			title = "Fruits Pro", 
			desc = "Break 1000 Fruits", 
			amount = 1000, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 100000
		}, {
			title = "Fruits Pro II", 
			desc = "Break 2500 Fruits", 
			amount = 2500, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 150000
		}, {
			title = "Fruits Pro III", 
			desc = "Break 5000 Fruits", 
			amount = 5000, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 250000
		}, {
			title = "Fruits Ninja", 
			desc = "Break 7500 Fruits", 
			amount = 7500, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 400000
		}, {
			title = "Fruits Ninja II", 
			desc = "Break 10,000 Fruits", 
			amount = 10000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 625000
		}, {
			title = "Fruits Ninja III", 
			desc = "Break 15,000 Fruits", 
			amount = 15000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 1000000
		} }
};
