-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Orbs = { {
			title = "Orbs I", 
			desc = "Pickup 500 Orbs", 
			amount = 500, 
			difficulty = 1, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 250
		}, {
			title = "Orbs II", 
			desc = "Pickup 1,000 Orbs", 
			amount = 1000, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 400
		}, {
			title = "Orbs III", 
			desc = "Pickup 2,500 Orbs", 
			amount = 2500, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 750
		}, {
			title = "Orbs IV", 
			desc = "Pickup 5,000 Orbs", 
			amount = 5000, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 1400
		}, {
			title = "Orbs V", 
			desc = "Pickup 10,000 Orbs", 
			amount = 10000, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 3000
		}, {
			title = "Orbs VI", 
			desc = "Pickup 25,000 Orbs", 
			amount = 25000, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 6500
		}, {
			title = "Orbs VII", 
			desc = "Pickup 50,000 Orbs", 
			amount = 50000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 11000
		}, {
			title = "Orbs VIII", 
			desc = "Pickup 75,000 Orbs", 
			amount = 75000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 20000
		}, {
			title = "Orbs IX", 
			desc = "Pickup 100,000 Orbs", 
			amount = 100000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 45000
		}, {
			title = "Orbs X", 
			desc = "Pickup 200,000 Orbs", 
			amount = 200000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 100000
		}, {
			title = "Orbs XI", 
			desc = "Pickup 500,000 Orbs", 
			amount = 500000, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 200000
		}, {
			title = "Orbs XII", 
			desc = "Pickup 1,000,000 Orbs", 
			amount = 1000000, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 325000
		} }
};
