-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Safes = { {
			title = "Safes I", 
			desc = "Break 10 Safes", 
			amount = 10, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 200
		}, {
			title = "Safes II", 
			desc = "Break 25 Safes", 
			amount = 25, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 750
		}, {
			title = "Safes III", 
			desc = "Break 50 Safes", 
			amount = 50, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 1200
		}, {
			title = "Safes IV", 
			desc = "Break 100 Safes", 
			amount = 100, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 2500
		}, {
			title = "Safes V", 
			desc = "Break 250 Safes", 
			amount = 250, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 8000
		}, {
			title = "Safes VI", 
			desc = "Break 500 Safes", 
			amount = 500, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 13500
		}, {
			title = "Safes VII", 
			desc = "Break 750 Safes", 
			amount = 750, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 18000
		}, {
			title = "Safes VIII", 
			desc = "Break 1,000 Safes", 
			amount = 1000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 27500
		}, {
			title = "Safes IX", 
			desc = "Break 1,500 Safes", 
			amount = 1500, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 45000
		}, {
			title = "Safes X", 
			desc = "Break 2,000 Safes", 
			amount = 2000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 80000
		}, {
			title = "Safes XI", 
			desc = "Break 3,500 Safes", 
			amount = 3500, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 125000
		}, {
			title = "Safes XII", 
			desc = "Break 7,500 Safes", 
			amount = 7500, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 250000
		}, {
			title = "Safes XIII", 
			desc = "Break 12,500 Safes", 
			amount = 12500, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 500000
		} }
};
