-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Golden Machine Failed"] = { {
			title = "Unlucky", 
			desc = "Fail an attempt using the golden machine 5 times", 
			amount = 5, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 750
		}, {
			title = "Very Unlucky", 
			desc = "Fail an attempt using the golden machine 50 times", 
			amount = 50, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 5000
		}, {
			title = "Seriously, Give Up", 
			desc = "Fail an attempt using the golden machine a whopping 200 times", 
			amount = 200, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 17500
		} }
};
