-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Crates = { {
			title = "Crates I", 
			desc = "Break 10 Crates", 
			amount = 10, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 200
		}, {
			title = "Crates II", 
			desc = "Break 25 Crates", 
			amount = 25, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 750
		}, {
			title = "Crates III", 
			desc = "Break 50 Crates", 
			amount = 50, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 1200
		}, {
			title = "Crates IV", 
			desc = "Break 100 Crates", 
			amount = 100, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 2500
		}, {
			title = "Crates V", 
			desc = "Break 250 Crates", 
			amount = 250, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 8000
		}, {
			title = "Crates VI", 
			desc = "Break 500 Crates", 
			amount = 500, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 13500
		}, {
			title = "Crates VII", 
			desc = "Break 750 Crates", 
			amount = 750, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 18000
		}, {
			title = "Crates VIII", 
			desc = "Break 1,000 Crates", 
			amount = 1000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 27500
		}, {
			title = "Crates IX", 
			desc = "Break 1,500 Crates", 
			amount = 1500, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 45000
		}, {
			title = "Crates X", 
			desc = "Break 2,000 Crates", 
			amount = 2000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 80000
		}, {
			title = "Crates XI", 
			desc = "Break 3,500 Crates", 
			amount = 3500, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 125000
		}, {
			title = "Crates XII", 
			desc = "Break 7,500 Crates", 
			amount = 7500, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 250000
		}, {
			title = "Crates XIII", 
			desc = "Break 12,500 Crates", 
			amount = 12500, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 500000
		} }
};
