-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Lootbags = { {
			title = "Lootbags I", 
			desc = "Pickup 5 Lootbags", 
			amount = 5, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 600
		}, {
			title = "Lootbags II", 
			desc = "Pickup 20 Lootbags", 
			amount = 20, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 1500
		}, {
			title = "Lootbags III", 
			desc = "Pickup 50 Lootbags", 
			amount = 50, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 4050
		}, {
			title = "Lootbags IV", 
			desc = "Pickup 100 Lootbags", 
			amount = 100, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 7500
		}, {
			title = "Lootbags V", 
			desc = "Pickup 200 Lootbags", 
			amount = 200, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 18000
		}, {
			title = "Lootbags VI", 
			desc = "Pickup 500 Lootbags", 
			amount = 500, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 37500
		}, {
			title = "Lootbags VII", 
			desc = "Pickup 1,000 Lootbags", 
			amount = 1000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 75000
		}, {
			title = "Lootbags VIII", 
			desc = "Pickup 1,500 Lootbags", 
			amount = 1500, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 105000
		}, {
			title = "Lootbags IX", 
			desc = "Pickup 2,000 Lootbags", 
			amount = 2000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 150000
		}, {
			title = "Lootbags X", 
			desc = "Pickup 3,500 Lootbags", 
			amount = 3500, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 255000
		}, {
			title = "Lootbags XI", 
			desc = "Pickup 5,000 Lootbags", 
			amount = 5000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 375000
		}, {
			title = "Lootbags XII", 
			desc = "Pickup 10,000 Lootbags", 
			amount = 10000, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 750000
		}, {
			title = "Lootbags XIII", 
			desc = "Pickup 20,000 Lootbags", 
			amount = 20000, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 1500000
		} }
};
