-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Enchanting = { {
			title = "Pixie Dust", 
			desc = "Enchant 1 pet", 
			amount = 1, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 1500
		}, {
			title = "Wizardry", 
			desc = "Enchant 5 more pets", 
			amount = 5, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 7500
		}, {
			title = "Bewitchment", 
			desc = "Enchant 20 more pets", 
			amount = 20, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 25000
		}, {
			title = "Abracadabra", 
			desc = "Enchant 100 more pets", 
			amount = 100, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 25000
		}, {
			title = "Sorcerer Supreme", 
			desc = "Enchant 250 more pets", 
			amount = 250, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 25000
		} }
};
