-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Fuse Pets"] = { {
			title = "Mad Scientist", 
			desc = "Fuse pets", 
			amount = 1, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 200
		}, {
			title = "Lab Rat", 
			desc = "Fuse pets 5 times", 
			amount = 5, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 750
		}, {
			title = "Frankenstein", 
			desc = "Fuse pets 25 times", 
			amount = 25, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 2500
		}, {
			title = "Breaking Bad", 
			desc = "Fuse pets 100 times", 
			amount = 100, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 8500
		} }
};
