-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Open Eggs"] = { {
			title = "Egg Opener", 
			desc = "Open 3 Eggs", 
			amount = 3, 
			difficulty = 1, 
			secret = false, 
			rewardType = "Coins", 
			reward = 500
		}, {
			title = "Egg Opener II", 
			desc = "Open 5 Eggs", 
			amount = 5, 
			difficulty = 1, 
			secret = false, 
			rewardType = "Coins", 
			reward = 1500
		}, {
			title = "Egg Opener III", 
			desc = "Open 10 Eggs", 
			amount = 10, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Coins", 
			reward = 5000
		}, {
			title = "Egg Pro", 
			desc = "Open 20 Eggs", 
			amount = 20, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 750
		}, {
			title = "Egg Pro II", 
			desc = "Open 35 Eggs", 
			amount = 35, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 1750
		}, {
			title = "Egg Pro III", 
			desc = "Open 50 Eggs", 
			amount = 50, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 3250
		}, {
			title = "Egg Elite", 
			desc = "Open 75 Eggs", 
			amount = 75, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 5000
		}, {
			title = "Egg Elite II", 
			desc = "Open 100 Eggs", 
			amount = 100, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 7500
		}, {
			title = "Egg Elite III", 
			desc = "Open 150 Eggs", 
			amount = 150, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 12500
		}, {
			title = "Egg Champion", 
			desc = "Open 200 Eggs", 
			amount = 200, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 15000
		}, {
			title = "Egg Champion II", 
			desc = "Open 350 Eggs", 
			amount = 350, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 22500
		}, {
			title = "Egg Champion III", 
			desc = "Open 500 Eggs", 
			amount = 500, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 50000
		}, {
			title = "Egg Legend", 
			desc = "Open 750 Eggs", 
			amount = 750, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Slots", 
			reward = 10
		}, {
			title = "Egg Legend II", 
			desc = "Open 1,500 Eggs", 
			amount = 1500, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Slots", 
			reward = 15
		}, {
			title = "Egg Legend III", 
			desc = "Open 2,500 Eggs", 
			amount = 2500, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Slots", 
			reward = 20
		} }
};
