-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Golden Machine Success"] = { {
			title = "It's Gold", 
			desc = "Successfully convert a pet to golden", 
			amount = 1, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 200
		}, {
			title = "More Gold", 
			desc = "Successfully convert 5 pets to golden", 
			amount = 5, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 750
		}, {
			title = "Gold Addict", 
			desc = "Successfully convert 25 pets to golden", 
			amount = 25, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 2500
		}, {
			title = "Gold Standard", 
			desc = "Successfully convert 100 pets to golden", 
			amount = 100, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 8500
		} }
};
