-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Presents = { {
			title = "Presents I", 
			desc = "Break 10 Presents", 
			amount = 10, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 250
		}, {
			title = "Presents II", 
			desc = "Break 25 Presents", 
			amount = 25, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 900
		}, {
			title = "Presents III", 
			desc = "Break 50 Presents", 
			amount = 50, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 1500
		}, {
			title = "Presents IV", 
			desc = "Break 100 Presents", 
			amount = 100, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 3250
		}, {
			title = "Presents V", 
			desc = "Break 250 Presents", 
			amount = 250, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 10000
		}, {
			title = "Presents VI", 
			desc = "Break 500 Presents", 
			amount = 500, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 16500
		}, {
			title = "Presents VII", 
			desc = "Break 750 Presents", 
			amount = 750, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 22500
		}, {
			title = "Presents VIII", 
			desc = "Break 1,000 Presents", 
			amount = 1000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 35000
		}, {
			title = "Presents IX", 
			desc = "Break 1,500 Presents", 
			amount = 1500, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 50000
		}, {
			title = "Presents X", 
			desc = "Break 2,000 Presents", 
			amount = 2000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 85000
		}, {
			title = "Presents XI", 
			desc = "Break 3,500 Presents", 
			amount = 3500, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 125000
		}, {
			title = "Presents XII", 
			desc = "Break 7,500 Presents", 
			amount = 7500, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 250000
		}, {
			title = "Presents XIII", 
			desc = "Break 12,500 Presents", 
			amount = 12500, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 500000
		} }
};
