-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Chests = { {
			title = "Chests I", 
			desc = "Break 3 Chests", 
			amount = 3, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 200
		}, {
			title = "Chests II", 
			desc = "Break 10 Chests", 
			amount = 10, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 500
		}, {
			title = "Chests III", 
			desc = "Break 25 Chests", 
			amount = 25, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 1350
		}, {
			title = "Chests IV", 
			desc = "Break 50 Chests", 
			amount = 50, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 2500
		}, {
			title = "Chests V", 
			desc = "Break 100 Chests", 
			amount = 100, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 6000
		}, {
			title = "Chests VI", 
			desc = "Break 250 Chests", 
			amount = 250, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 12500
		}, {
			title = "Chests VII", 
			desc = "Break 500 Chests", 
			amount = 500, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 25000
		}, {
			title = "Chests VIII", 
			desc = "Break 750 Chests", 
			amount = 750, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 35000
		}, {
			title = "Chests IX", 
			desc = "Break 1,000 Chests", 
			amount = 1000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 50000
		}, {
			title = "Chests X", 
			desc = "Break 1,500 Chests", 
			amount = 1500, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 85000
		}, {
			title = "Chests XI", 
			desc = "Break 2,500 Chests", 
			amount = 2500, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 125000
		}, {
			title = "Chests XII", 
			desc = "Break 5,000 Chests", 
			amount = 5000, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 250000
		}, {
			title = "Chests XIII", 
			desc = "Break 10,000 Chests", 
			amount = 10000, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 500000
		} }
};
