-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Create Dark Matter"] = { {
			title = "Anti-Gravity", 
			desc = "Create 1 dark matter pet", 
			amount = 1, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 7500
		}, {
			title = "Astronomical", 
			desc = "Create 5 more dark matter pets", 
			amount = 5, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 30000
		}, {
			title = "Black Hole", 
			desc = "Create 15 more dark matter pets", 
			amount = 15, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 75000
		}, {
			title = "Particle Accelerator", 
			desc = "Create 50 more dark matter pets", 
			amount = 50, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 275000
		}, {
			title = "Atomic Converter", 
			desc = "Create 200 more dark matter pets", 
			amount = 200, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 1000000
		} }
};
