-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Mine Coins"] = { {
			title = "Coin Collector", 
			desc = "Mine 20 Coins", 
			amount = 20, 
			difficulty = 1, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 100
		}, {
			title = "Coin Collector II", 
			desc = "Mine 50 Coins", 
			amount = 50, 
			difficulty = 1, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 250
		}, {
			title = "Coin Collector III", 
			desc = "Mine 100 Coins", 
			amount = 100, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 500
		}, {
			title = "Coin Pro", 
			desc = "Mine 250 Coins", 
			amount = 250, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 1250
		}, {
			title = "Coin Pro II", 
			desc = "Mine 500 Coins", 
			amount = 500, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 3000
		}, {
			title = "Coin Pro III", 
			desc = "Mine 750 Coins", 
			amount = 750, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 5250
		}, {
			title = "Coin Elite", 
			desc = "Mine 1,000 Coins", 
			amount = 1000, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 7500
		}, {
			title = "Coin Elite II", 
			desc = "Mine 1,500 Coins", 
			amount = 1500, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 9500
		}, {
			title = "Coin Elite III", 
			desc = "Mine 2,000 Coins", 
			amount = 2000, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 12500
		}, {
			title = "Coin Champion", 
			desc = "Mine 2,500 Coins", 
			amount = 2500, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 15000
		}, {
			title = "Coin Champion II", 
			desc = "Mine 5,000 Coins", 
			amount = 5000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 22500
		}, {
			title = "Coin Champion III", 
			desc = "Mine 7,500 Coins", 
			amount = 7500, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 27500
		}, {
			title = "Coin Legend", 
			desc = "Mine 10,000 Coins", 
			amount = 10000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 42500
		}, {
			title = "Coin Legend II", 
			desc = "Mine 25,000 Coins", 
			amount = 25000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 125000
		}, {
			title = "Coin Legend III", 
			desc = "Mine 50,000 Coins", 
			amount = 50000, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 225000
		} }
};
