-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Rainbow Machine Success"] = { {
			title = "It's Rainbow", 
			desc = "Successfully convert a pet to rainbow", 
			amount = 1, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 350
		}, {
			title = "Double Rainbow", 
			desc = "Successfully convert 5 pets to rainbow", 
			amount = 5, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 1500
		}, {
			title = "Triple Rainbow", 
			desc = "Successfully convert 25 pets to rainbow", 
			amount = 25, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 4500
		}, {
			title = "Full Spectrum", 
			desc = "Successfully convert 100 pets to rainbow", 
			amount = 100, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 13500
		} }
};
