-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Upgrade Bank"] = { {
			title = "Restructuring", 
			desc = "Upgrade your Bank", 
			amount = 1, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 750000
		}, {
			title = "Incorporation", 
			desc = "Upgrade your Bank to Tier 4", 
			amount = 2, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 1250000
		}, {
			title = "Monopoly", 
			desc = "Upgrade your Bank to Tier 6", 
			amount = 2, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 2500000
		}, {
			title = "Empire", 
			desc = "Upgrade your Bank to Tier 7", 
			amount = 1, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 7500000
		}, {
			title = "Total Control", 
			desc = "Upgrade your Bank to Tier 8", 
			amount = 1, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 20000000
		} }
};
