-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Free Gifts"] = { {
			title = "Free Gifts I", 
			desc = "Claim 1 Gift", 
			amount = 1, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 1000
		}, {
			title = "Free Gifts II", 
			desc = "Claim 3 Gift", 
			amount = 3, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 10000
		}, {
			title = "Free Gifts III", 
			desc = "Claim 10 Gift", 
			amount = 10, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 20000
		}, {
			title = "Free Gifts IV", 
			desc = "Claim 25 Gift", 
			amount = 25, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 50000
		}, {
			title = "Free Gifts V", 
			desc = "Claim 50 Gift", 
			amount = 50, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 100000
		}, {
			title = "Free Gifts VI", 
			desc = "Claim 100 Gift", 
			amount = 100, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 250000
		} }
};
