-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Vaults = { {
			title = "Vaults I", 
			desc = "Break 3 Vaults", 
			amount = 3, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 200
		}, {
			title = "Vaults II", 
			desc = "Break 10 Vaults", 
			amount = 10, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 500
		}, {
			title = "Vaults III", 
			desc = "Break 25 Vaults", 
			amount = 25, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 1350
		}, {
			title = "Vaults IV", 
			desc = "Break 50 Vaults", 
			amount = 50, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 2500
		}, {
			title = "Vaults V", 
			desc = "Break 100 Vaults", 
			amount = 100, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 6000
		}, {
			title = "Vaults VI", 
			desc = "Break 250 Vaults", 
			amount = 250, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 12500
		}, {
			title = "Vaults VII", 
			desc = "Break 500 Vaults", 
			amount = 500, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 25000
		}, {
			title = "Vaults VIII", 
			desc = "Break 750 Vaults", 
			amount = 750, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 35000
		}, {
			title = "Vaults IX", 
			desc = "Break 1,000 Vaults", 
			amount = 1000, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 50000
		}, {
			title = "Vaults X", 
			desc = "Break 1,750 Vaults", 
			amount = 1750, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 85000
		}, {
			title = "Vaults XI", 
			desc = "Break 2,500 Vaults", 
			amount = 2500, 
			difficulty = 4, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 125000
		}, {
			title = "Vaults XII", 
			desc = "Break 5,000 Vaults", 
			amount = 5000, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 250000
		}, {
			title = "Vaults XIII", 
			desc = "Break 10,000 Vaults", 
			amount = 10000, 
			difficulty = 5, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 500000
		} }
};
