-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Upgrades = { {
			title = "Self Improvement", 
			desc = "Buy 3 upgrades", 
			amount = 3, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 500
		}, {
			title = "Big Gains", 
			desc = "Buy 5 more upgrades", 
			amount = 5, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 2000
		}, {
			title = "Perfection", 
			desc = "Buy 10 more upgrades", 
			amount = 10, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Diamonds", 
			reward = 5000
		} }
};
