-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["April Fools 2022"] = { {
			title = "April Fools! (1/3)", 
			desc = "April Fools 2022 Event!", 
			amount = 1, 
			difficulty = 2, 
			secret = true, 
			rewardType = "Diamonds", 
			reward = 150000
		}, {
			title = "April Fools! (2/3)", 
			desc = "April Fools 2022 Event!", 
			amount = 1, 
			difficulty = 3, 
			secret = true, 
			rewardType = "Diamonds", 
			reward = 500000
		}, {
			title = "April Fools! (Final)", 
			desc = "Complete the April Fools 2022 Event!", 
			amount = 1, 
			difficulty = 4, 
			secret = true, 
			rewardType = "Pet", 
			reward = "138"
		} }
};
