-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["Buy Areas"] = { {
			title = "Expansion", 
			desc = "Buy 2 areas", 
			amount = 1, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Slots", 
			reward = 5
		}, {
			title = "New Horizons", 
			desc = "Buy 3 more areas", 
			amount = 2, 
			difficulty = 2, 
			secret = false, 
			rewardType = "Slots", 
			reward = 5
		}, {
			title = "Expedition", 
			desc = "Buy 3 more areas", 
			amount = 3, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Slots", 
			reward = 5
		}, {
			title = "Journey", 
			desc = "Buy 3 more areas", 
			amount = 3, 
			difficulty = 3, 
			secret = false, 
			rewardType = "Slots", 
			reward = 5
		} }
};
