-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return { {
		Tier = 1, 
		Title = "Starter Account", 
		Cost = 7500000, 
		ProductId = 0, 
		MaxPlayers = 1, 
		PetSlots = 40, 
		MaxDiamonds = 10000000000, 
		Interest = 0
	}, {
		Tier = 2, 
		Title = "Basic Account", 
		Cost = 40000000, 
		ProductId = 1228140504, 
		MaxPlayers = 2, 
		PetSlots = 95, 
		MaxDiamonds = 50000000000, 
		Interest = 0.1
	}, {
		Tier = 3, 
		Title = "Plus Account", 
		Cost = 200000000, 
		ProductId = 1228140516, 
		MaxPlayers = 3, 
		PetSlots = 200, 
		MaxDiamonds = 300000000000, 
		Interest = 0.175
	}, {
		Tier = 4, 
		Title = "Deluxe Account", 
		Cost = 800000000, 
		ProductId = 1228140531, 
		MaxPlayers = 4, 
		PetSlots = 500, 
		MaxDiamonds = 1500000000000, 
		Interest = 0.25
	}, {
		Tier = 5, 
		Title = "Premier Account", 
		Cost = 3500000000, 
		ProductId = 1228140544, 
		MaxPlayers = 5, 
		PetSlots = 950, 
		MaxDiamonds = 5000000000000, 
		Interest = 0.4
	}, {
		Tier = 6, 
		Title = "Gold Account", 
		Cost = 15000000000, 
		ProductId = 1228140560, 
		MaxPlayers = 5, 
		PetSlots = 1400, 
		MaxDiamonds = 10000000000000, 
		Interest = 0.55
	}, {
		Tier = 7, 
		Title = "Diamond Account", 
		Cost = 50000000000, 
		ProductId = 1228140571, 
		MaxPlayers = 6, 
		PetSlots = 2500, 
		MaxDiamonds = 25000000000000, 
		Interest = 0.7
	}, {
		Tier = 8, 
		Title = "Sapphire Account", 
		Cost = 125000000000, 
		ProductId = 0, 
		MaxPlayers = 6, 
		PetSlots = 3500, 
		MaxDiamonds = 100000000000000, 
		Interest = 0.85
	} };
