-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Presents = {
		Amount = 500, 
		Tier = "Easy", 
		Coin = {
			Pattern = "Present"
		}
	}, 
	Eggs = {
		Amount = 5000, 
		Tier = "Medium", 
		Egg = {
			Pattern = "Relic", 
			PatternOverride = "Ancient"
		}
	}, 
	Golden = {
		Amount = 200, 
		Tier = "Hard", 
		Description = "Successfully Gold {Amount} Mythicals with 13% Chance!"
	}
};
