-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Coins = {
		Amount = 500, 
		Tier = "Easy", 
		Coin = {
			Pattern = "Coin"
		}
	}, 
	Enchant = {
		Amount = 10, 
		Tier = "Medium", 
		Description = "Enchant a Pet with Glittering {Amount} times!"
	}, 
	Mythicals = {
		Amount = 150, 
		Tier = "Hard", 
		Description = "Successfully Rainbow {Amount} Mythicals with 13% Chance!"
	}
};
