-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Eggs = {
		Amount = 300, 
		Tier = "Easy", 
		Egg = {
			Pattern = "Enchanted", 
			PatternOverride = "Enchanted Forest"
		}
	}, 
	Vaults = {
		Amount = 350, 
		Tier = "Medium", 
		Coin = {
			Pattern = "Vault"
		}
	}, 
	Enchant = {
		Amount = 2500, 
		Tier = "Hard", 
		Description = "Use the Enchant Machine {Amount} times!"
	}
};
