-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Booth = {
		Amount = 50, 
		Tier = "Easy", 
		Description = "Buy {Amount} pets from Trading Booths!"
	}, 
	Eggs = {
		Amount = 500, 
		Tier = "Medium", 
		Description = "Hatch {Amount} Mythicals from the Empyrean Eggs!", 
		Egg = {
			Pattern = "Empyrean", 
			Rarity = "Mythical"
		}
	}, 
	Chest = {
		Amount = 1500, 
		Tier = "Hard", 
		Coin = {
			Pattern = "Grand Heaven Chest"
		}
	}
};
