-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Eggs = {
		Amount = 1000, 
		Tier = "Easy", 
		Egg = {
			Pattern = "Heaven"
		}
	}, 
	Chests = {
		Amount = 1000, 
		Tier = "Medium", 
		Coin = {
			Pattern = "Chest"
		}
	}, 
	Eggs2 = {
		Amount = 25, 
		Tier = "Hard", 
		Description = "Hatch {Amount} Shiny Pegasus Pets!", 
		Egg = {
			Pattern = "Heaven", 
			Pet = "87", 
			Attributes = {
				sh = true
			}
		}
	}
};
