-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Booth = {
		Amount = 25, 
		Tier = "Easy", 
		Description = "Sell {Amount} Pets in Trading Booths!"
	}, 
	Eggs = {
		Amount = 5, 
		Tier = "Medium", 
		Description = "Hatch {Amount} Shiny Samurai Dragon Pets!", 
		Egg = {
			Pattern = "Samurai", 
			Pet = "89", 
			Attributes = {
				sh = true
			}
		}
	}, 
	Diamond = {
		Amount = 10000, 
		Tier = "Hard", 
		Description = "Break {Amount} Diamonds in the Diamond Mine!"
	}
};
