--[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⣿⣿⣿⣷⣦⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣿⣿⣷⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⡿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⡇⠀⠀⢀⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⡇⠀⠀⢸⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⣿⣿⣿⣧⠀⠀⠘⣿⣿⣿⣷⣤⣀⣀⠀⠀⣀⣀⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⡄⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣷⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⡆⠀⠀⠀⠈⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠿⠀⠀⠀⠀⠀⠀⠈⠉⠛⠻⠿⠿⠿⠟⠛⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
	Velvet Groups rbx.lua Framework [2025] - [2025]
	Written by kalidrios - 1037898275229020250
	Developed with a VScode and Rojo.
	
	-+-+-+- SPECIFICS -+-+-+-
	_L.Interact
	===========
		
	===========
	
--]]
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

local ReplicatedStorage = game:GetService("ReplicatedStorage");
local RunService = game:GetService("RunService");
local UserInputService = game:GetService("UserInputService");
local Players = game:GetService("Players");
local Library = ReplicatedStorage:WaitForChild("Library");
local Assets = ReplicatedStorage:WaitForChild("Assets");
local m_Audio = require(Library.Audio);
local m_Variables = require(Library.Variables);
local m_Functions = require(Library.Functions);
local table1 = {};
local table2 = {};
local u1 = nil;
local u2 = nil;
local bool1 = false;
function table1.Add(p1, p2) -- Line: 90
	--[[
		Upvalues:
			[1] = m_Functions
			[2] = table2
			[3] = bool1
			[4] = m_Audio
			[5] = u1
			[6] = RunService
			[7] = m_Variables
			[8] = UserInputService
			[9] = Assets
			[10] = Players
			[11] = u2
	--]]
	assert(p1);
	local v1 = p2 or {};
	local v2 = v1.dist or 10;
	local u3 = v1.label or "";
	local u4 = v1.timer or 0;
	local table3 = {};
	local bool2 = false;
	local u5 = nil;
	local u6 = m_Functions.GenerateUID();
	local bool3 = false;
	local bool4 = false;
	local bool5 = false;
	local u7 = nil;
	if typeof(p1) ~= "Instance" then
		u7 = m_Functions.CreateParticleHost(p1);
		bool5 = true;
	elseif p1:IsA("Model") then
		local t_PrimaryPart = p1.PrimaryPart;
		assert(t_PrimaryPart);
		u7 = t_PrimaryPart;
	elseif p1:IsA("BasePart") then
		u7 = p1;
	else
		error("Unknown host type: " .. p1.ClassName);
	end
	local Activated = Instance.new("BindableEvent");
	Activated.Name = "Activated";
	Activated.Parent = u7;
	table2[u6] = {
		id = u6,
		host = u7,
		lastDist = 0,
		lastCheck = 0,
		maxDist = v2
	};
	local function ButtonActivate() -- Line: 139
		--[[
			Upvalues:
				[1] = Activated
		--]]
		Activated:Fire();
	end
	local function ButtonUpFX() -- Line: 144
		--[[
			Upvalues:
				[1] = bool4
				[2] = bool1
				[3] = m_Audio
				[4] = u5
				[5] = m_Functions
				[6] = u4
				[7] = Activated
		--]]
		if not bool4 and bool1 then
			bool4 = true;
			bool1 = false;
			m_Audio.Play("rbxassetid://7000715003", script, 1.75, 0.1);
			if u5:FindFirstChild("Button") then
				u5.Button.Back.BackgroundColor3 = Color3.new(1, 1, 1);
				m_Functions.Tween(u5.Button.Back, {Size = UDim2.new(1, 0, 1, 0)}, {
					0.3,
					Enum.EasingStyle.Elastic,
					Enum.EasingDirection.Out
				});
			end
			u5.Button.Back.Fill.Visible = false;
			if u4 <= 0 then
				Activated:Fire();
			end
			bool4 = false;
		end
	end
	local function ButtonDownFX() -- Line: 165
		--[[
			Upvalues:
				[1] = bool4
				[2] = bool1
				[3] = m_Audio
				[4] = m_Functions
				[5] = u5
				[6] = u4
				[7] = u1
				[8] = u6
				[9] = RunService
				[10] = ButtonUpFX
				[11] = Activated
		--]]
		if not bool4 and not bool1 then
			bool4 = true;
			bool1 = true;
			m_Audio.Play("rbxassetid://7000714975", script, 1.75, 0.1);
			m_Functions.Tween(u5.Button.Back, {Size = UDim2.new(0.85, 0, 0.85, 0)}, {
				0.3,
				Enum.EasingStyle.Elastic,
				Enum.EasingDirection.Out
			});
			if u4 > 0 then
				u5.Button.Back.Fill.Visible = true;
				task.spawn(function() -- Line: 175
					--[[
						Upvalues:
							[1] = u4
							[2] = bool1
							[3] = u5
							[4] = u1
							[5] = u6
							[6] = RunService
							[7] = ButtonUpFX
							[8] = Activated
					--]]
					local os_clock_ret = os.clock();
					while os.clock() - os_clock_ret < u4 and bool1 and u5 and u1 == u6 do
						local v4 = (os.clock() - os_clock_ret) / u4;
						u5.Button.Back.Fill.Size = UDim2.new(v4, 0, v4, 0);
						RunService.RenderStepped:Wait();
					end
					if os.clock() - os_clock_ret >= u4 and u1 == u6 then
						ButtonUpFX();
						Activated:Fire();
					end
				end);
			else
				u5.Button.Back.Fill.Visible = false;
				u5.Button.Back.BackgroundColor3 = Color3.new(0.75, 0.75, 0.75);
			end
			bool4 = false;
		end
	end
	local function Events() -- Line: 199
		--[[
			Upvalues:
				[1] = u5
				[2] = m_Variables
				[3] = table2
				[4] = u6
				[5] = table3
				[6] = UserInputService
				[7] = ButtonDownFX
				[8] = ButtonUpFX
		--]]
		if u5 then
			local function EnabledCheck() -- Line: 201
				--[[
					Upvalues:
						[1] = m_Variables
						[2] = table2
						[3] = u6
				--]]
				if not m_Variables.Typing and not m_Variables.MessageOpen and table2[u6] then
					return true;
				end
				return false;
			end
			table3[#table3 + 1] = UserInputService.InputBegan:Connect(function(input) -- Line: 209
				--[[
					Upvalues:
						[1] = m_Variables
						[2] = table2
						[3] = u6
						[4] = ButtonDownFX
				--]]
				if (not m_Variables.Typing and not m_Variables.MessageOpen and table2[u6] and true or false) and (input.KeyCode == Enum.KeyCode.ButtonX or input.KeyCode == Enum.KeyCode.E) then
					ButtonDownFX();
				end
			end);
			table3[#table3 + 1] = UserInputService.InputEnded:Connect(function(input2) -- Line: 217
				--[[
					Upvalues:
						[1] = m_Variables
						[2] = table2
						[3] = u6
						[4] = ButtonUpFX
				--]]
				if (not m_Variables.Typing and not m_Variables.MessageOpen and table2[u6] and true or false) and (input2.KeyCode == Enum.KeyCode.ButtonX or input2.KeyCode == Enum.KeyCode.E) then
					ButtonUpFX();
				end
			end);
			table3[#table3 + 1] = u5.Button.InputBegan:Connect(function(input3) -- Line: 226
				--[[
					Upvalues:
						[1] = m_Variables
						[2] = table2
						[3] = u6
						[4] = ButtonDownFX
				--]]
				local t_UserInputType = input3.UserInputType;
				local t_UserInputState = input3.UserInputState;
				local t_KeyCode = input3.KeyCode;
				if (t_UserInputType == Enum.UserInputType.MouseButton1 or t_UserInputType == Enum.UserInputType.Touch and t_UserInputState == Enum.UserInputState.Begin or t_KeyCode == Enum.KeyCode.ButtonX) and (not m_Variables.Typing and not m_Variables.MessageOpen and table2[u6] and true or false) then
					ButtonDownFX();
				end
			end);
			table3[#table3 + 1] = u5.Button.InputEnded:Connect(function(input4) -- Line: 235
				--[[
					Upvalues:
						[1] = m_Variables
						[2] = table2
						[3] = u6
						[4] = ButtonUpFX
				--]]
				local t_UserInputType2 = input4.UserInputType;
				local _ = input4.UserInputState;
				local t_KeyCode2 = input4.KeyCode;
				if (t_UserInputType2 == Enum.UserInputType.MouseButton1 or t_UserInputType2 == Enum.UserInputType.Touch or t_KeyCode2 == Enum.KeyCode.ButtonX) and (not m_Variables.Typing and not m_Variables.MessageOpen and table2[u6] and true or false) then
					ButtonUpFX();
				end
			end);
		end
	end
	local function Show() -- Line: 247
		--[[
			Upvalues:
				[1] = u5
				[2] = bool2
				[3] = bool3
				[4] = Assets
				[5] = m_Variables
				[6] = u3
				[7] = m_Functions
				[8] = u7
				[9] = Players
				[10] = Events
		--]]
		if not u5 and not bool2 and not bool3 then
			bool2 = true;
			bool3 = false;
			u5 = Assets.Billboards:FindFirstChild("Interact"):Clone();
			if m_Variables.Console then
				u5.Button.Back.Icon.Image = "rbxassetid://5083555478";
			elseif m_Variables.Mobile then
				u5.Button.Back.Icon.Image = "rbxassetid://5083554875";
			else
				u5.Button.Back.Icon.Image = "rbxassetid://5083555193";
			end
			if u3 ~= "" then
				u5.Label.Visible = true;
				u5.Label.Text = u3;
			else
				u5.Label.Visible = false;
			end
			local t_Size = u5.Size;
			u5.Size = UDim2.new();
			m_Functions.Tween(u5, {Size = t_Size}, {
				0.2,
				Enum.EasingStyle.Back,
				Enum.EasingDirection.Out
			});
			u5.Adornee = u7;
			u5.Parent = Players.LocalPlayer.PlayerGui;
			Events();
		end
	end
	local function Hide() -- Line: 285
		--[[
			Upvalues:
				[1] = u5
				[2] = bool2
				[3] = bool3
				[4] = m_Functions
				[5] = bool1
				[6] = table3
		--]]
		if u5 and bool2 and not bool3 then
			bool3 = true;
			m_Functions.Tween(u5, {Size = UDim2.new()}, {
				0.15,
				Enum.EasingStyle.Back,
				Enum.EasingDirection.In
			}).Completed:Wait();
			bool2 = false;
			u5:Destroy();
			u5 = nil;
			bool1 = false;
			for index1 = 1, #table3 do
				table3[index1]:Disconnect();
			end
			table3 = {};
			bool3 = false;
		end
	end
	local function Remove() -- Line: 311
		--[[
			Upvalues:
				[1] = table2
				[2] = u6
				[3] = u5
				[4] = bool5
				[5] = u7
				[6] = u1
				[7] = u2
				[8] = bool1
		--]]
		table2[u6] = nil;
		if u5 then
			u5:Destroy();
		end
		if bool5 and u7 then
			u7:Destroy();
			u7 = nil;
		end
		if u1 == u6 then
			u1 = nil;
			u2 = nil;
			bool1 = false;
		end
	end
	task.spawn(function() -- Line: 337
		--[[
			Upvalues:
				[1] = table2
				[2] = u6
				[3] = u7
				[4] = u1
				[5] = u5
				[6] = Show
				[7] = Hide
				[8] = RunService
				[9] = bool5
				[10] = u2
				[11] = bool1
		--]]
		while table2[u6] and u7 and u7.Parent do
			if u1 == u6 then
				if not u5 then
					Show();
				end
			elseif u5 then
				Hide();
			end
			RunService.RenderStepped:Wait();
		end
		table2[u6] = nil;
		if u5 then
			u5:Destroy();
		end
		if bool5 and u7 then
			u7:Destroy();
			u7 = nil;
		end
		if u1 == u6 then
			u1 = nil;
			u2 = nil;
			bool1 = false;
		end
	end);
	return Activated.Event, Remove;
end
task.spawn(function() -- Line: 364
	--[[
		Upvalues:
			[1] = Players
			[2] = table2
			[3] = bool1
			[4] = u1
			[5] = u2
			[6] = RunService
	--]]
	local t_LocalPlayer = Players.LocalPlayer;
	while true do
		for key1, val1 in pairs(table2) do
			local t_host = val1.host;
			if not t_host or not t_host.Parent then
				table2[key1] = nil;
				continue;
			end
			if os.clock() - val1.lastCheck < math.min(val1.lastDist / 150, 0.5) then continue end
			local DistanceFromCharacter_ret = t_LocalPlayer:DistanceFromCharacter(t_host.CFrame.Position);
			val1.lastDist = DistanceFromCharacter_ret;
			val1.lastCheck = os.clock();
			if DistanceFromCharacter_ret <= val1.maxDist then
				if bool1 or u1 and u2 and DistanceFromCharacter_ret >= u2 - 1 and u1 ~= key1 then continue end
				u2 = DistanceFromCharacter_ret;
				u1 = key1;
				continue;
			end
			if u1 ~= key1 then continue end
			u2 = nil;
			u1 = nil;
			bool1 = false;
		end
		RunService.Heartbeat:Wait();
	end
end);
return table1;
