--[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⣿⣿⣿⣷⣦⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣿⣿⣷⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⡿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⡇⠀⠀⢀⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⡇⠀⠀⢸⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⣿⣿⣿⣧⠀⠀⠘⣿⣿⣿⣷⣤⣀⣀⠀⠀⣀⣀⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⡄⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣷⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⡆⠀⠀⠀⠈⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠿⠀⠀⠀⠀⠀⠀⠈⠉⠛⠻⠿⠿⠿⠟⠛⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
	Velvet Groups rbx.lua Framework [2025] - [2025]
	Written by kalidrios - 1037898275229020250
	Developed with a VScode and Rojo.
	
	-+-+-+- SPECIFICS -+-+-+-
	_L.Message
	===========
		
	===========
	
--]]
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

local table1 = {};
local ReplicatedStorage = game:GetService("ReplicatedStorage");
local RunService = game:GetService("RunService");
local GuiService = game:GetService("GuiService");
local Players = game:GetService("Players");
local UserInputService = game:GetService("UserInputService");
local Library = ReplicatedStorage:WaitForChild("Library");
local Client = Library:WaitForChild("Client");
local m_Variables = require(Library.Variables);
local m_GUI = require(Client.GUI);
local m_GUIFX = require(Client.GUIFX);
local m_Audio = require(Library.Audio);
local t_Message = m_GUI.Message;
local bool1 = false;
local Connect_ret = nil;
local table2 = {};
function table1.New(p1, ...) 
	local table3 = {...};
	if m_Variables.MessageOpen == true then
		repeat
			RunService.RenderStepped:Wait();
		until not m_Variables.MessageOpen;
	end
	local v1 = table3[1] == nil and table3[2] == nil or false;
	local v2 = type(table3[1]) == "boolean" and (table3[2] == nil and true or typeof(table3[2]) == "number") or false;
	local v3 = table3[1] and table3[2];
	local v4 = v2 and table3[2] ~= nil and typeof(table3[2]) == "number" and table3[3] == true and table3[2] or nil;
	local _ = workspace:GetServerTimeNow();
	t_Message.Yes.Visible = false;
	t_Message.No.Visible = false;
	t_Message.Ok.Visible = false;
	t_Message.Option1.Visible = false;
	t_Message.Option2.Visible = false;
	t_Message.OptionA.Visible = false;
	t_Message.OptionB.Visible = false;
	t_Message.OptionC.Visible = false;
	t_Message.Cancel.Visible = false;
	t_Message.Desc.Text = p1;
	for _, child1 in ipairs(t_Message.Desc:GetChildren()) do
		if child1.ClassName ~= "TextLabel" then continue end
		child1.Text = t_Message.Desc.Text;
	end
	if not v1 then
		if v2 then
			local _ = table3[1];
			t_Message.Yes.Visible = true;
			t_Message.No.Visible = true;
			if v4 ~= nil then
				local u11 = v4;
				local t_Image = t_Message.Yes.Image;
				local t_HoverImage = t_Message.Yes.HoverImage;
				local t_PressedImage = t_Message.Yes.PressedImage;
				t_Message.Yes.Image = "rbxassetid://11632629004";
				t_Message.Yes.HoverImage = "rbxassetid://11632629074";
				t_Message.Yes.PressedImage = "rbxassetid://11632629074";
				t_Message.Yes.Active = false;
				t_Message.Yes.TextLabel.Text = "Wait " .. tostring(u11);
				local u12 = 0;
				Connect_ret = RunService.Heartbeat:Connect(function(p4)
					u12 = u12 + p4;
					if u12 >= 1 then
						u12 = 0;
						u11 = u11 - 1;
						if u11 == 0 then
							t_Message.Yes.Active = true;
							t_Message.Yes.TextLabel.Text = "Yes";
							local t_Yes2 = t_Message.Yes;
							local t_Yes3 = t_Message.Yes;
							local t_Yes4 = t_Message.Yes;
							local v10 = t_HoverImage;
							local v11 = t_PressedImage;
							t_Yes2.Image = t_Image;
							t_Yes3.HoverImage = v10;
							t_Yes4.PressedImage = v11;
							Connect_ret:Disconnect();
							return;
						end
						t_Message.Yes.TextLabel.Text = "Wait " .. tostring(u11);
					end
				end);
			end
		elseif v3 then
			if not table3[3] then
				local v5 = table3[1];
				local v6 = table3[2];
				t_Message.Option1.TextLabel.Text = v5;
				t_Message.Option2.TextLabel.Text = v6;
				t_Message.Option1.Visible = true;
				t_Message.Option2.Visible = true;
				t_Message.Cancel.Visible = true;
			else
				local v7 = table3[1];
				local v8 = table3[2];
				local v9 = table3[3];
				t_Message.OptionA.TextLabel.Text = v7;
				t_Message.OptionB.TextLabel.Text = v8;
				t_Message.OptionC.TextLabel.Text = v9;
				t_Message.OptionA.Visible = true;
				t_Message.OptionB.Visible = true;
				t_Message.OptionC.Visible = true;
				t_Message.Cancel.Visible = true;
			end
		end
	else
		t_Message.Ok.Visible = true;
	end
	local u1 = nil;
	local function SetupClickEvent(p2, p3) 
		table2[#table2 + 1] = p2.Activated:Connect(function()
			if bool1 == false then
				bool1 = true;
				p3();
				bool1 = false;
			end
		end);
	end
	if t_Message.No.Visible then
		local t_No = t_Message.No;
		local function u2() 
			Close();
			u1 = false;
		end
		table2[#table2 + 1] = t_No.Activated:Connect(function() 
			if bool1 == false then
				bool1 = true;
				u2();
				bool1 = false;
			end
		end);
	end
	if t_Message.Yes.Visible then
		local t_Yes = t_Message.Yes;
		local function u3()
			Close();
			u1 = true;
		end
		table2[#table2 + 1] = t_Yes.Activated:Connect(function()
			if bool1 == false then
				bool1 = true;
				u3();
				bool1 = false;
			end
		end);
	end
	if t_Message.Ok.Visible then
		local t_Ok = t_Message.Ok;
		local function u4() 
			Close();
			u1 = true;
		end
		table2[#table2 + 1] = t_Ok.Activated:Connect(function() 
			if bool1 == false then
				bool1 = true;
				u4();
				bool1 = false;
			end
		end);
	end
	if t_Message.Option1.Visible then
		local t_Option1 = t_Message.Option1;
		local function u5() 
			Close();
			u1 = 1;
		end
		table2[#table2 + 1] = t_Option1.Activated:Connect(function() 
			if bool1 == false then
				bool1 = true;
				u5();
				bool1 = false;
			end
		end);
	end
	if t_Message.Option2.Visible then
		local t_Option2 = t_Message.Option2;
		local function u6() 
			Close();
			u1 = 2;
		end
		table2[#table2 + 1] = t_Option2.Activated:Connect(function() 
			if bool1 == false then
				bool1 = true;
				u6();
				bool1 = false;
			end
		end);
	end
	if t_Message.OptionA.Visible then
		local t_OptionA = t_Message.OptionA;
		local function u7() 
			Close();
			u1 = 1;
		end
		table2[#table2 + 1] = t_OptionA.Activated:Connect(function() 
			if bool1 == false then
				bool1 = true;
				u7();
				bool1 = false;
			end
		end);
	end
	if t_Message.OptionB.Visible then
		local t_OptionB = t_Message.OptionB;
		local function u8() 
			Close();
			u1 = 2;
		end
		table2[#table2 + 1] = t_OptionB.Activated:Connect(function()
			if bool1 == false then
				bool1 = true;
				u8();
				bool1 = false;
			end
		end);
	end
	if t_Message.OptionC.Visible then
		local t_OptionC = t_Message.OptionC;
		local function u9() 
			Close();
			u1 = 3;
		end
		table2[#table2 + 1] = t_OptionC.Activated:Connect(function() 
			if bool1 == false then
				bool1 = true;
				u9();
				bool1 = false;
			end
		end);
	end
	if t_Message.Cancel.Visible then
		local t_Cancel = t_Message.Cancel;
		local function u10() 
			Close();
			u1 = false;
		end
		table2[#table2 + 1] = t_Cancel.Activated:Connect(function()
			if bool1 == false then
				bool1 = true;
				u10();
				bool1 = false;
			end
		end);
	end
	if m_Variables.Console then
		if t_Message.Ok.Visible then
			GuiService.SelectedObject = t_Message.Ok;
		elseif t_Message.Yes.Visible then
			GuiService.SelectedObject = t_Message.Yes;
		elseif t_Message.Option1.Visible then
			GuiService.SelectedObject = t_Message.Option1;
		end
		local bool2 = false;
		local bool3 = false;
		table2[#table2 + 1] = UserInputService.InputBegan:Connect(function(input, gameProcessedEvent) 
			if not bool3 then
				bool3 = true;
				if input.KeyCode == Enum.KeyCode.ButtonB then
					bool2 = true;
				end
				bool3 = false;
			end
		end);
		local bool4 = false;
		table2[#table2 + 1] = UserInputService.InputEnded:Connect(function(input2, gameProcessedEvent2) 
			if not bool2 then return end
			if not bool4 then
				bool4 = true;
				if input2.KeyCode == Enum.KeyCode.ButtonB then
					m_Audio.Play(5074101610, Players.LocalPlayer.PlayerGui);
					Close();
					u1 = false;
				end
				bool4 = false;
			end
		end);
	end
	m_Audio.Play("rbxassetid://7139316734", script, 1, 0.5);
	if not v1 and (v2 or v3) then
		m_Audio.Play("rbxassetid://7009855114", script, 1, 0.5);
	end
	Open();
	repeat
		RunService.RenderStepped:Wait();
	until u1 ~= nil;
	assert(u1 ~= nil);
	return u1;
end
m_GUIFX.ButtonFX(t_Message.Ok);
m_GUIFX.ButtonFX(t_Message.Cancel);
m_GUIFX.ButtonFX(t_Message.Yes);
m_GUIFX.ButtonFX(t_Message.No);
m_GUIFX.ButtonFX(t_Message.Option1);
m_GUIFX.ButtonFX(t_Message.Option2);
function table1.IsOpen() 
	return t_Message.Gui.Enabled;
end
function Close() 
	for _, val2 in ipairs(table2) do
		val2:Disconnect();
	end
	table2 = {};
	if Connect_ret then
		Connect_ret:Disconnect();
	end
	t_Message.Gui.Enabled = false;
	m_Variables.MessageOpen = false;
	if m_Variables.Console then
		GuiService.SelectedObject = nil;
	end
end
function Open() 
	t_Message.Gui.Enabled = true;
	m_Variables.MessageOpen = true;
end

local Network = require(game:GetService("ReplicatedStorage"):WaitForChild("Library"):WaitForChild("Client").Network)
Network.Fired("Message"):Connect(function(p1, ...)
	table1.New(p1, ...)
end)

return table1;
