--[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⣿⣿⣿⣷⣦⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣿⣿⣷⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⡿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⡇⠀⠀⢀⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⡇⠀⠀⢸⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⣿⣿⣿⣧⠀⠀⠘⣿⣿⣿⣷⣤⣀⣀⠀⠀⣀⣀⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⡄⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣷⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⡆⠀⠀⠀⠈⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠿⠀⠀⠀⠀⠀⠀⠈⠉⠛⠻⠿⠿⠿⠟⠛⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
                                 

	Velvet Groups rbx.lua Framework [2025] - [2025]
	Written by kalidrios - 1037898275229020250
	Developed with a VScode and Rojo.
	
	-+-+-+- SPECIFICS -+-+-+-
	_L.Pets
	===========
	TODO: Rescript the reset of this.
	===========

	===========
--]]
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- | load library | --
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Library = ReplicatedStorage:WaitForChild("Library")
local ClientLibrary = Library:WaitForChild("Client")
local Modules = Library:WaitForChild("Modules")
local Types = Library:WaitForChild("Types")

-- | shared modules | --
local Shared = require(Library.Shared)
local Signal = require(Library.Signal)
local Directory = require(Library.Directory)
local Functions = require(Library.Functions)
local Variables = require(Library.Variables)
local Audio = require(Library.Audio)
local Save = require(ClientLibrary.Save)
local Network = require(ClientLibrary.Network)
local GUIFX = require(ClientLibrary.GUIFX)
local WorldCmds = require(ClientLibrary.WorldCmds)
local Pets = require(Modules.Pets)
local DefaultStats = require(Modules.DefaultStats)

--------|       Top       |--------
local PetCmds = {}

--------|     Setting     |--------
local WalkSounds = { 101658504598631, 92554500744038, 94577744304758, 79435629058763 }

--------|    Reference    |--------
local Assets = ReplicatedStorage:WaitForChild("Assets")
local X = ReplicatedStorage:WaitForChild("X")
local Players = game:GetService("Players")
local debris = workspace:WaitForChild("__DEBRIS")


--------|    Variables    |--------
local LeftistHeap = require(X:WaitForChild("Util").LeftistHeap)
local rng = Random.new()
local Indices = {}
local Pets = {}


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

local u1 = {}
function PetCmds.GetIndices(p1, p2) -- Line: 48
	--[[
		Upvalues:
			[1] = table3
			[2] = table4
	--]]
	local v1 = u1[p1]
	if v1 then
		return v1
	end
	local table5 = {}
	for key1, val1 in ipairs(p2.Pets) do
		table5[val1.uid] = key1
		if Pets[val1.uid] then continue end
		Pets[val1.uid] = p1
	end
	Indices[p1] = table5
	return table5
end
function PetCmds.DeleteIndices(p3) -- Line: 64
	--[[
		Upvalues:
			[1] = table3
	--]]
	if Indices[p3] then
		Indices[p3] = nil;
	end
end
function PetCmds.GetIndex(p4, p5, p6) -- Line: 70
	--[[
		Upvalues:
			[1] = PetCmds
	--]]
	return PetCmds.GetIndices(p4, p5)[p6]
end
function PetCmds.GetFrom(p7, p8, p9) 
	local Index = PetCmds.GetIndex(p7, p8, p9);
	if not Index then
		return nil, 0;
	end
	assert(Index);
	local v2 = p8.Pets[Index];
	if not v2 then
		return nil, 0;
	end
	assert(v2);
	if p9 ~= v2.uid then
		warn("Pet mismatch:", p9, Index, v2 and v2.uid or "nil");
		return nil, 0;
	end
	return v2, Index;
end

function PetCmds.Get(uid) 
	debug.profilebegin("PetCmds.Get");
	local v3 = Pets[uid];
	if v3 then
		local v36 = Save.Get(v3);
		if v36 then
			local v56, v57 = PetCmds.GetFrom(v3, v36, uid);
			if v56 then
				debug.profileend();
				return v56, v3, v57;
			end
		end
		Pets[uid] = nil;
	end
	for key2, val2 in pairs(Save.GetSaves()) do
		local v37, v38 = PetCmds.GetFrom(key2, val2, uid);
		if not v37 then continue end
		Pets[uid] = key2;
		debug.profileend();
		return v37, key2, v38;
	end
	debug.profileend();
	return nil, nil, 0;
end

Signal.Fired("Stats Removed"):Connect(function(player) 
	PetCmds.DeleteIndices(player)
	for index, _player in pairs(Pets) do
		if _player == player then
			Pets[index] = nil
		end	
	end
end)

function PetCmds.GetEquipped(p12, p13, p14)
	local v35;
	if p12 == nil then
		v35 = Players.LocalPlayer;
	else
		assert(typeof(p12) == "Instance" and p12:IsA("Player") or false);
		v35 = p12;
	end
	debug.profilebegin("PetCmds.GetEquipped");
	local table6 = {};
	local v4 = Save.Get(v35, true);
	if v4 then
		local v39 = Shared.IsHardcore and v4.HardcorePetsEquipped or v4.PetsEquipped;
		if p14 then
			if p13 then
				for key25, val25 in pairs(v39) do
					if not val25 then continue end
					table6[key25] = true;
				end
			else
				for key26, val26 in pairs(v39) do
					if not val26 then continue end
					local From2 = PetCmds.GetFrom(v35, v4, key26);
					if not From2 then continue end
					table6[key26] = From2;
				end
			end
		elseif p13 then
			for key27, val27 in pairs(v39) do
				if not val27 then continue end
				table.insert(table6, key27);
			end
		else
			for key28, val28 in pairs(v39) do
				if not val28 then continue end
				local From = PetCmds.GetFrom(v35, v4, key28);
				if not From then continue end
				table.insert(table6, From);
			end
		end
	end
	debug.profileend();
	return table6;
end
function PetCmds.LocalEquipPet(player, uid, equip)  
	local save = Save.Get(player)
	if save then
		local changed = false
		local pets = Shared.IsHardcore and save.HardcorePetsEquipped or save.PetsEquipped
		if equip then
			if not pets[uid] then
				pets[uid] = true
				changed = true
			end
		elseif pets[uid] then
			pets[uid] = nil
			changed = true
		end
		if changed then
			if player == Players.LocalPlayer then
				Signal.Fire("Pet Equips Changed")
				return
			end
			Signal.Fire("Other Pet Equips Changed", player)
		end
	end
end

Network.Fired("Pet Added"):Connect(function(player, pdata) 
	local save = Save.Get(player)
	if not save then
		return
	end
	assert(save)
	local PetIndices = PetCmds.GetIndices(player, save)
	table.insert(save.Pets, pdata)
	local petindice = #save.Pets
	PetIndices[pdata.uid] = petindice
	local islocalplayer = player == Players.LocalPlayer
	if islocalplayer then
		Signal.Fire("Stat Changed", "Pets")
	else
		Signal.Fire("Other Stat Changed", player, "Pets")
	end
	if islocalplayer then
		Signal.Fire("Stats Changed")
		return
	end
	Signal.Fire("Other Stats Changed", player)
end)


Network.Fired("Pet Removed"):Connect(function(player, uid) 
	local save = Save.Get(player)
	if not save then
		return 
	end
	assert(save)
	local playerPets = PetCmds.GetIndices(player, save)
	local pet = playerPets[uid]
	if not pet then
		return
	end
	assert(pet)
	local _pet = save.Pets[pet]
	if not _pet then
		return
	end
	assert(_pet)
	if uid ~= _pet.uid then 
		return
	end
	table.remove(save.Pets, pet)
	playerPets[uid] = nil
	for index = pet, #save.Pets do
		local __pet = save.Pets[index]
		if __pet then
			playerPets[__pet.uid] = index
		end
	end
	local IsLocalPlayer = player == Players.LocalPlayer
	if IsLocalPlayer then
		Signal.Fire("Stat Changed", "Pets")
	else
		Signal.Fire("Other Stat Changed", player, "Pets")
	end
	if IsLocalPlayer then
		Signal.Fire("Stats Changed")
	else
		Signal.Fire("Other Stats Changed", player)
	end
	PetCmds.LocalEquipPet(player, uid, false)
end)

Network.Fired("Pet Update"):Connect(function(player, pdata) 
	local save = Save.Get(player)
	if not save then
		return 
	end
	assert(save)
	local petindex = PetCmds.GetIndex(player, save, pdata.uid)
	if not petindex then
		return 
	end
	assert(petindex)
	local opdata = save.Pets[petindex]
	if not opdata then 
		return 
	end
	assert(opdata)
	if pdata.uid ~= opdata.uid then
		return
	end
	if Functions.DeepEqualsUnsafe(opdata, pdata) then
		return 
	end
	save.Pets[petindex] = pdata
	
	local islocalplayer = player == Players.LocalPlayer
	if islocalplayer then
		Signal.Fire("Stat Changed", "Pets")
	else
		Signal.Fire("Other Stat Changed", player, "Pets")
	end
	
	if islocalplayer then
		Signal.Fire("Stats Changed")
		return
	end
	
	Signal.Fire("Other Stats Changed", player)
end)

Network.Fired("Pet Equip Changed"):Connect(function(player, uid, equip)
	PetCmds.LocalEquipPet(player, uid, equip)
end)

function IsGameWorld(plr)
	local v32 = Save.Get(plr)
	if not v32 then
		return false
	end
	local world = Shared.IsHardcore and v32.Hardcore.World or v32.World  
	if world ~= "Yeet" then
		return false
	end
	return true
end

function PetCmds.HasBestEquipped(player)
	assert(player == nil and true or typeof(player) == "Instance" and player:IsA("Player") or false)
	debug.profilebegin("PetCmds.HasBestEquipped")
	local save = Save.Get(player)
	if not save then
		debug.profileend()
		return false
	end
	assert(save)
	local playerEquipped = PetCmds.GetEquipped(player, true, true)
	local maxeqipslots = save.InfPetsEnabled and #save.Pets or Shared.GetMaxEquippedSlots(save)
	local yeetPower
	if IsGameWorld(player) then
		yeetPower = function(pet)
			return Shared.GetYeetPower(pet, save.Pets)
		end
	end
	local petOrder = function(i, v)
		return Shared.PetOrderBest(i, v, nil, nil, nil, nil, yeetPower)
	end
	local n = LeftistHeap.new(petOrder)
	for _, pet in ipairs(save.Pets) do
		if Directory.Pets[pet.id].isGift then
			continue 
		end
		n.insert(pet)
	end
	local hasbestequipped = true
	for index = 1, maxeqipslots do
		local v, pet = n.tryPop()
		if not v then 
			break 
		end
		if not playerEquipped[pet.uid] then
			hasbestequipped = false
			break
		end
	end
	debug.profileend()
	return hasbestequipped
end

function PetCmds.Match(pet, a) 
	assert(typeof(pet) == "table")
	if #a == 0 then
		return true
	end
	
	local dir = Directory.Pets[pet.id]
	if not dir then
		return false
	end
	local _match = {}
	if dir.rarity then
		table.insert(_match, dir.rarity)
	end
	if pet.sh then
		table.insert(_match, "Shiny")
	end
	if dir.name then
		table.insert(_match, dir.name)
	end
	if pet.nk then
		table.insert(_match, pet.nk)
	end
	
	return true
end

function PetCmds.Scaler(pet)  
	local scaler = pet.scaler
	if not scaler then
		scaler = Functions.Scaler()
		pet.scaler = scaler
	end
	assert(scaler)
	return scaler
end

function PetCmds.Spawn(p110, p111, p112, p113)
	debug.profilebegin("PetCmds.Spawn")
	assert(p110)
	assert(p111)
	local v114 = WorldCmds.Get()
	assert(v114)
	local v115 = Directory.Pets[p110.id]
	assert(v115)
	local v116 = p110.g == true
	local v117 = p110.r == true
	local v118 = p110.dm == true
	local v119 = p110.hc == true
	local v120 = p110.sh == true
	local model = (v116 and v115.modelGold or v115.model) 
	if not model then
		local parent = v115._script.Parent
		if parent then
			model = parent:WaitForChild(v116 and "Golden" or "Pet")
		end
	end
	local Directory1 = model:Clone()
	if v115.replacements and p110.rep then
		for _, v122 in ipairs(p110.rep) do
			local v123 = v115.replacements[v122]
			if v123 then
				local v124 = v123.dst:Clone()
				local v125 = v123.src
				local v126
				if v125 then
					local v127 = Directory1:FindFirstChild(v125.Name)
					if v127 then
						v126 = v127.Parent or Directory1
						if v127:IsA("PVInstance") and v124:IsA("PVInstance") then
							v124:PivotTo(v127:GetPivot())
						end
						v127:Destroy()
					else
						v126 = Directory1
					end
				else
					v126 = Directory1
				end
				v124.Parent = v126
			end
		end
	end
	local v128 = { Directory1 }
	local v129 = {}
	for _, v130 in ipairs(Directory1:GetDescendants()) do
		if v130:IsA("BasePart") then
			table.insert(v128, v130)
			table.insert(v129, v130)
		end
	end
	local v131 = Directory1:FindFirstChildOfClass("SpecialMesh")
	local v132 = {}
	if v131 then
		v132[1] = v131
	end
	if v131 then
		local scale = v131.Scale
		if not scale then
			scale = Vector3.one
		end
		for _, v133 in ipairs(v128) do
			local v134 = v133:FindFirstChildOfClass("SpecialMesh")
			if v134 then
				if  v134 ~= v131 then
					table.insert(v132, v134)
				end
				local size = v134:GetAttribute("OriginalSize")
				if size then
					v133.Size = (size) * scale
				end
			end	
		end
	end	
	local v135 = Directory1:WaitForChild("center")
	local v136 = Directory1:WaitForChild("bottom")
	local v137 = Directory1:FindFirstChild("mount", true)
	local v138 = Directory1:FindFirstChild("mount_character") or v137
	Directory1:SetAttribute("Owner", p111.Name)
	Directory1:SetAttribute("Dir", p110.id)
	Directory1:SetAttribute("ID", p110.uid)
	Directory1.Name = p110.uid
	Directory1.Anchored = true
	for _, v140 in ipairs(v128) do
		v140.Massless = true
		v140.CanCollide = false
		v140.CanQuery = true
		v140.CanTouch = true
		v140.CastShadow = false
		if v140.Material == Enum.Material.SmoothPlastic then
			v140.Material = Enum.Material.Plastic
			v140.MaterialVariant = ""
			if v115.balloon or p110.sh then
				v140.Material = Enum.Material.Metal
				v140.MaterialVariant = "MetalFineGold"
			end
			if v115.evolved then
				v140.Material = Enum.Material.SmoothPlastic
				v140.MaterialVariant = ""
			end
		end
		if v115.weld then
			v140.Anchored = true
		end
	end
	local v141 = p113 or Vector3.one
	local v142 = Vector3.one
	if #v132 > 0 then
		local part = v132[1]
		v142 = part.Offset
	else
		if v131 then 
			v142 = v131.Offset
		end
	end
	local v143 = v135.CFrame
	local v144 = CFrame.new(v142.X, v143.Y, v143.Z) * CFrame.fromOrientation(0, 1.5707963267948966, 0)
	v135.CFrame = v144
	local v145 = v136.CFrame
	local v146
	local part = v128[1]
	if #v132 > 0 then
		--part = v132[1]
		--local v614 = CFrame.new(v142.X, v136.CFrame.Y, v136.CFrame.Z)
		--v614 = (v614) * CFrame.fromOrientation(0, 1.5707963267949, 0)
		--v136.CFrame = v614
		local originalSize = part:GetAttribute("OriginalSize")
		if not originalSize then
			part = v132[1]
		end
	end
	if part:IsA("MeshPart") then
		v146 = CFrame.new(v144.X, (-model.Size.Y) / 2 + v142.Y, v144.Z)
	else
		v146 = CFrame.new(v144.X, v145.Y, v144.Z)
	end
	if not v115.parralax then
		v136.CFrame = v146 * CFrame.fromOrientation(0, 1.5707963267949, 0)
	end	
	for _, v147 in ipairs(v132) do
		if v147.VertexColor == Vector3.one then
			v147.VertexColor = Vector3.new(1.125, 1.125, 1.125)
		end
	end
	if v116 then
		for _, v148 in ipairs(v132) do
			v148.VertexColor = Vector3.new(1.45, 1.45, 1.45)
		end
		for _, v149 in ipairs(Assets.Particles:WaitForChild("Golden Pet"):GetChildren()) do
			v149:Clone().Parent = Directory1
		end
	end
	local v658 = {}

	if v115.parralax then
		for _, v663 in ipairs(v115.parralax) do
			local v666 = v663.CameraDirection or Vector3.new(0, 0, 0)
			local v667 = v663.AnimSpeed or Vector3.new(0, 0, 0)
			local v669 = v663.NoiseCameraRatio or 0
			local v671 = v663.BrightnessNoiseRange or { Vector3.new(0, 0, 0), Vector3.new(0, 0, 0) }
			local LinearSpeed = v663.LinearSpeed or Vector3.new(0.75, 0.75, 1)
			local v678 = v663.LogScale or 0.5

			v663.Color = v663.Color or Color3.new(1, 1, 1)
			local v688 = Vector3.new(v663.Color.R, v663.Color.G, v663.Color.B)
			v663.Brightness = v663.Brightness or Vector3.new(1, 1, 1)
			local v689 = Vector3.new(v663.Brightness.X, v663.Brightness.Y, v663.Brightness.Z)
			local v690 = v688 * v689

			local v697 = v663.Transparency or 0

			v663.FixedOffset = v663.FixedOffset or Vector3.new(math.random() * 2 - 1, math.random() * 2 - 1, 1)
			v663.FixedScale = v663.FixedScale or Vector3.new(2, 2, 1)

			for _, v716 in ipairs(v128) do
				if v716:GetAttribute("ApplyParralax") ~= false and not v116 then
					if not v658[v716] then
						v658[v716] = {}
					end
					for _, v726 in ipairs(Enum.NormalId:GetEnumItems()) do
						local v728 = Functions.FaceSize(v726, v716.Size)
						local v732 = Vector3.new(0, 0, 0) + v663.FixedOffset * v728
						local v1026 = v728 * v663.FixedScale

						local v736 = Instance.new("Texture")
						v736.Name = "Tex" .. v726.Name
						v736.Face = v726
						v736.Color3 = Color3.new(v690.X, v690.Y, v690.Z)
						v736.Transparency = v697
						v736.ZIndex = v663.ZIndex or 1
						v736.Texture = v663.TextureId or ""
						v736.OffsetStudsU = v732.X
						v736.OffsetStudsV = v732.Y
						v736.StudsPerTileU = v1026.X
						v736.StudsPerTileV = v1026.Y
						v736.Parent = v716

						table.insert(v658[v716], {
							instance = v736,
							transparency = v697,
							brightness = v689,
							color = v688,
							face = v726,
							faceNormal = Vector3.FromNormalId(v726),
							fixedOffset = v663.FixedOffset,
							fixedScale = v663.FixedScale,
							linearSpeed = LinearSpeed,
							logScale = v678,
							nearPlaneZ = v663.NearPlaneZ or 15,
							cameraDirection = v666,
							animSpeed = v667,
							animPos = Vector3.new(0, 0, 0),
							tickColor = Vector3.new(1, 1, 1),
							noiseCameraRatio = v669,
							brightnessNoiseRange = v671,
							transparencyNoiseRange = v663.TransparencyNoiseRange,
							kalidriosCameraFix = v115.titanic and 6 or v115.huge and 2 or 0.75
						})
					end
				end
			end
		end
	end

	local v150 = {}
	local v151 = {}
	if v117 then
		local v152 = Assets.Particles:WaitForChild("Rainbow Pet"):WaitForChild("Sparkles"):Clone()
		v152.Name = "__RAINBOWPARTICLES"
		v152.Parent = Directory1
		table.insert(v151, v152)
		for _, v153 in ipairs(v128) do
			local v154 = Assets.Other:WaitForChild("Rainbow Pet"):WaitForChild("Decal"):Clone()
			v154.Name = "__RAINBOWFX"
			v154.Parent = v153
			table.insert(v150, v154)
		end
		for _, v155 in ipairs(v132) do
			v155.VertexColor = Vector3.new(2, 2, 2)
		end
	end
	if v118 then
		for _, v156 in ipairs(v132) do
			if v119 then
				v156.VertexColor = Vector3.new(0.8, 20, 20)
			else
				v156.VertexColor = Vector3.new(20, 0.6, 20)
			end
		end
	end
	local v157 = v115.colorVariants and p110.cv and v115.colorVariants[p110.cv]
	if v157 then
		local v158 = v157.Color
		local v159 = Functions.Map3(Vector3.new(v158.R, v158.G, v158.B) * v157.Magnitude, Vector3.zero, Vector3.one, Vector3.new(0.1, 0.1, 0.1), Vector3.one)
		for _, v160 in ipairs(v132) do
			v160.VertexColor = v159
		end
		local Save1 = {
			{
				["a"] = Color3.new(1, 1, 1), 
				["b"] = v158
			}
		}
		local function v165(p162)
			-- upvalues: (ref) Functions, (copy) Save1
			local v163 = {}
			for _, v164 in ipairs(p162.Keypoints) do
				table.insert(v163, ColorSequenceKeypoint.new(v164.Time, (Functions.Recolor(v164.Value, Save1))))
			end
			return ColorSequence.new(v163)
		end
		for _, v166 in ipairs(Directory1:GetDescendants()) do
			if v166:IsA("ParticleEmitter") then
				v166.Color = v165(v166.Color)
			elseif v166:IsA("Trail") then
				v166.Color = v165(v166.Color)
			elseif v166:IsA("Light") then
				v166.Color = Functions.Recolor(v166.Color, Save1)
			end
		end
	end
	local v167 = nil
	if p110.vc then
		v167 = Vector3.new(table.unpack(p110.vc))
	elseif v115.vertexColor then
		v167 = v115.vertexColor
	end
	if v167 then
		local Save8 = Color3.new(v167.X, v167.Y, v167.Z)
		for _, v169 in ipairs(v132) do
			v169.VertexColor = v167
		end
		local function v174(p170)
			-- upvalues: (copy) Save8, (ref) Functions
			local v171 = {
				{
					["a"] = Color3.new(1, 1, 1), 
					["b"] = Save8
				}
			}
			local v172 = {}
			for _, v173 in ipairs(p170.Keypoints) do
				table.insert(v172, ColorSequenceKeypoint.new(v173.Time, (Functions.Recolor(v173.Value, v171))))
			end
			return ColorSequence.new(v172)
		end
		for _, v175 in ipairs(Directory1:GetDescendants()) do
			if v175:IsA("ParticleEmitter") then
				v175.Color = v174(v175.Color)
			elseif v175:IsA("Trail") then
				v175.Color = v174(v175.Color)
			end
		end
	end
	local v176 = {}
	if v119 then
		for _, v177 in ipairs((Assets.Particles["Hardcore Pets"]:GetChildren())) do
			v177:Clone().Parent = v135
		end
		if not (v117 or v118) then
			for _, _ in ipairs(v128) do
				local v178 = Assets.Other:WaitForChild("Hardcore Pet"):WaitForChild("Decal"):Clone()
				v178.Name = "__HARDCOREFX"
				v178.Parent = Directory1
				table.insert(v176, v178)
			end
		end
		v141 = v141 * 1.25
	end
	if p110.id == "294" then
		v141 = v141 * (0.2 + 1.3 * math.random())
	end
	if v120 then
		local v_u_179
		if v115.titanic then
			v_u_179 = Assets.Particles.Shiny:WaitForChild("TitanicShinyParticle"):Clone()
			Functions.Scaler()(v_u_179, 3.25)
		elseif v115.huge then
			v_u_179 = Assets.Particles.Shiny:WaitForChild("HugeShinyParticle"):Clone()
			Functions.Scaler()(v_u_179, 1.5)
		else
			v_u_179 = Assets.Particles.Shiny:WaitForChild("ShinyParticle"):Clone()
		end
		v_u_179.Parent = v135
		task.defer(function()
			-- upvalues: (ref) v_u_179
			v_u_179:Emit(1)
		end)
	end
	local v180 = string.find(v115.name, "Pixel") ~= nil and "Pixel" or nil
	local v181 = nil
	local v182
	if p112 then
		v182 = nil
	else
		v182 = Assets.Billboards.Pet:Clone()
		v182.Name = "__BILLBOARD"
		v182.Nickname.AutoLocalize = false
		v182.Nickname.Text = p110.nk or ""
		v182.StudsOffset = Vector3.new(0, (v135.Position - v136.Position).Y * 2, 0)
		if p110.snk then
			v181 = GUIFX.Rainbow(v182.Nickname, "TextColor3", 3)
		end
		if 2 <= Shared.PetRarityNumbers[v115.rarity] then
			local v183 = v182.Rarity
			v183.Text = v115.rarity
			Shared.ApplyRarityColor(v183, v115.rarity)
			v183.Visible = true
			v182.StudsOffset = v182.StudsOffset + Vector3.new(0, 1, 0)
		end
		v182.Parent = Directory1
	end
	local v184 = {}
	if v115.weld then
		for _, v185 in ipairs(v129) do
			local v186 = v185:FindFirstAncestorWhichIsA("Model")
			local v187
			if v186 then
				v187 = v186.PrimaryPart
			else
				v187 = nil
			end
			local v188 = v187 or v185:FindFirstAncestorWhichIsA("BasePart") or v185.AssemblyRootPart or Directory1
			assert(v188)
			local v189 = v188:GetPivot():ToObjectSpace(v185:GetPivot())
			local v190 = v185:GetAttribute("RotationRate")
			if v190 then
				v190 = v190 * math.pi / 180
			end
			v184[v185] = {
				["part"] = v185, 
				["root"] = v188, 
				["offset"] = v189, 
				["lastOffset"] = v189, 
				["scaling"] = not v188:GetAttribute("NoScale"), 
				["rotationRate"] = v190
			}
		end
	end
	task.defer(function()
		-- upvalues: (ref) Audio, (copy) Directory1, (ref) rng, (ref) Functions, (ref) Assets
		Audio.Play("rbxassetid://7000720081", Directory1, rng:NextNumber(0.95, 1.05), 0.125, 125)
		local v191, v192 = Functions.Emit(Directory1, nil, Assets.Particles:WaitForChild("Pet Spawn"))
		for _, v193 in ipairs(v191) do
			Functions.AddDebris(v193, v192)
		end
	end)
	local v194 = Vector3.one
	local v195 = Vector3.one * v141
	local v196
	if v194 == v195 then
		v195 = v194
		v196 = nil
	else
		v196 = Functions.Scaler(nil, function(p197)
			return not p197:GetAttribute("NoScale")
		end)
		assert(v196)
		v196(Directory1, v195)
	end
	debug.profileend()
	return {
		["id"] = p110.id, 
		["uid"] = p110.uid, 
		["golden"] = v116, 
		["rainbow"] = v117, 
		["darkMatter"] = v118, 
		["shiny"] = v120, 
		["hardcore"] = v119, 
		["world"] = v114, 
		["owner"] = p111, 
		["part"] = Directory1, 
		--["mesh"] = v131, 
		["meshes"] = v132, 
		["parralax"] = v658,
		["childParts"] = v129, 
		["scriptedWelds"] = v184, 
		["center"] = v135, 
		["bottom"] = v136, 
		["mount"] = v137, 
		["mountCharacter"] = v138, 
		["rainbowParticles"] = v151, 
		["rainbowDecals"] = v150, 
		["hardcoreDecals"] = v176, 
		["specialType"] = v180, 
		["billboard"] = v182, 
		["signedAnimation"] = v181, 
		["scale"] = v195, 
		["overrideScale"] = v141, 
		["scaler"] = v196, 
		["moving"] = false, 
		["farming"] = false, 
		["movingTick"] = 0, 
		["spinTick"] = 0, 
		["jumping"] = false, 
		["riding"] = false
	}
end
function PetCmds.BasketballBounce(p198, p199, p200, p201)
	local v202 = p198 % p199
	return (p200 - v202) * math.exp(-v202) * math.abs((math.sin(math.pi * p201 * p198)))
end 
function processParalax(p47, p48, p49, p50, p51)
	--warn('parlax | ', p47, p48, p49, p50, p51)
	local v1113 = p47.Size
	if p51 then
		local v1115 = p51[p47]
		if not v1115 then
			v1115 = p47.CFrame
		end
		for v1185, v1124 in ipairs(p48) do  
			local v1188 = v1124.instance
			local v1130 = v1124.fixedOffset
			local v1135 = Functions.FaceSize(v1124.face, v1113) 
			local v1137 = ((workspace.CurrentCamera.CFrame:Inverse()) * v1115) * (v1124.faceNormal) * (v1113) * 0.5
			v1137 = (v1137) * v1124.linearSpeed
			v1137 = v1137 / (v1124.kalidriosCameraFix*2) --/3--p47.--3
			local v1191 = 1 + (math.log10((-v1124.nearPlaneZ) / math.min(-0.1, v1137.Z))) * v1124.logScale
			local v1148 = Vector3.new(v1137.X, -v1137.Y, 0)
			local v1150 = v1124.animPos
			v1150 = v1150 + ((v1124.animSpeed) * v1148.Unit) * p49
			v1124.animPos = v1150
			local v1197 = (v1148) * v1124.cameraDirection
			local v1198 = Vector3.zero
			local v1204 = (v1197 + v1150) * v1191 - (v1135) * 0.5 + (v1130) * v1135
			local v1207 = ((v1135) * v1191) * v1124.fixedScale
			v1188.OffsetStudsU = v1204.X
			v1188.OffsetStudsV = v1204.Y
			v1188.StudsPerTileU = v1207.X
			v1188.StudsPerTileV = v1207.Y
			local v1217 = ((v1197) * v1124.noiseCameraRatio + v1150) * v1191 - (v1135) * 0.5 + (v1130) * v1135
			local v1218 = v1124.transparencyNoiseRange
			if v1218 then
				local v1220 = 1 - v1124.transparency
				v1188.Transparency = math.clamp(1 - Functions.Lerp(v1218[1], v1218[2], (math.noise(v1217.X, v1217.Y, v1217.Z) + 1) * 0.5), 0, 1)
			end
			local brightnessNoiseRange = v1124.brightnessNoiseRange
			local brightness = Vector3.one
			if brightnessNoiseRange then
				brightness = v1124.brightness * brightnessNoiseRange[1]:Lerp(brightnessNoiseRange[2], (math.noise(-v1217.X, -v1217.Y, -v1217.Z) + 1) * 0.5)
			end 
			--local color = ((v1124.tickColor) * (v1124.color + v1124.brightness))
			local color = (v1124.tickColor * v1124.color) * brightness
			--color = color/2
			v1188.Color3 = Color3.new(color.X, color.Y, color.Z) 
		end
	end
end 
function PetCmds.Effects(p_u_203, p204, p205, p206, p207, p57)
	-- upvalues: (copy) Directory, (copy) v_u_2, (copy) rng, (copy) Audio, (copy) Variables, (copy) v_u_9, (copy) Functions, (copy) v_u_1, (copy) GUIFX
	debug.profilebegin("PetCmds.Effects")
	local v208 = Directory.Pets[p_u_203.id]
	assert(v208)
	local v_u_209 = p_u_203.part
	local v210 = Vector3.one
	local v211 = p_u_203.world == "Void"
	local v212 = p_u_203.walkSoundTick or p205
	p_u_203.walkSoundTick = v212
	local v213 = v211 and 0.65 or 0.3
	local v214 = 1
	if v211 then
		v214 = v214 * 0.4090909090909091
	end
	if v208.balloon then
		v214 = v214 * 0.5
	end
	if v208.jelly then
		v214 = v214 * 0.5
	end
	if p_u_203.moving and not v208.fly and not p_u_203.jumping and p_u_203.movingTick % v213 / v214 <= 0.1 and 0.2 < p205 - v212 then
		p_u_203.walkSoundTick = p205
		local v215 = v208.sounds.walk or WalkSounds
		if 0 < #v215 then
			local rng6 = v215[math.random(1, #v215)]
			local rng7 = rng:NextNumber(0.95, 1.2)
			local rng8 = 0.01
			if p_u_203.riding then
				rng7 = rng7 * 0.75
				rng8 = rng8 * 5
			end
			task.spawn(function()
				-- upvalues: (ref) Audio, (copy) rng6, (copy) v_u_209, (ref) rng7, (ref) rng8
				Audio.Play(rng6, v_u_209, rng7, rng8, 60)
			end)
		end
	end
	local v219 = p_u_203.randomSoundTick or p205
	p_u_203.randomSoundTick = v219
	if not p_u_203.moving and rng:NextNumber() <= 0.001 and 6 <= p205 - v219 and Variables.PetSoundsEnabled then
		p_u_203.randomSoundTick = p205
		local v220 = v208.sounds.random
		if 0 < #v220 then
			local v_u_221 = v220[math.random(1, #v220)]
			task.spawn(function()
				-- upvalues: (ref) Audio, (copy) v_u_221, (copy) v_u_209
				Audio.Play(v_u_221, v_u_209, 1, 0.5, 140)
			end)
		end
	end
	local v222 = p_u_203.specialType
	if v222 and v222 == "Pixel" and p_u_203.moving and not v208.fly and rng:NextInteger(1, 10) == 1 then
		(function()
			-- upvalues: (ref) rng, (copy) v_u_209, (copy) p_u_203, (ref) v_u_9, (ref) Functions
			debug.profilebegin("Pets.Tick.MakeCube")
			local v223 = Instance.new("Part")
			v223.Anchored = true
			v223.Massless = true
			v223.CanCollide = false
			v223.CastShadow = false
			v223.Size = Vector3.one * rng:NextNumber(0.4, 0.66)
			v223.Color = Color3.fromRGB(255, 255, 255)
			v223.CFrame = v_u_209.CFrame + Vector3.new(rng:NextNumber(-1, 1), p_u_203.bottom.CFrame.Y + rng:NextNumber(-1, 1), rng:NextNumber(-1, 1))
			v223.Name = "pixelFX"
			v223.Parent = debris
			local v224 = rng:NextNumber(0.33, 0.6)
			Functions.Tween(v223, {
				["Size"] = v223.Size * rng:NextNumber(0.25, 0.4), 
				["CFrame"] = v223.CFrame * CFrame.new(0, 0, rng:NextNumber(1, 2)) + Vector3.new(0, rng:NextNumber(0.25, 1.5), 0)
			}, { v224, "Linear" })
			Functions.AddDebris(v223, v224)
			debug.profileend()
		end)()
	end
	for v1375, v1368 in pairs(p_u_203.parralax) do
		for v1374, v1373 in ipairs(v1368) do
			v1373.tickColor = Vector3.one
		end
	end
	if p_u_203.rainbow then
		local _ = p_u_203.highlight
		local v225 = Color3.fromHSV(p205 / 1.5 % 1, 1, 1)
		local v226 = ColorSequence.new(v225)
		for _, v227 in ipairs(p_u_203.rainbowParticles) do
			v227.Color = v226
		end
		for _, v228 in ipairs(p_u_203.rainbowDecals) do
			v228.Color3 = v225
		end
		for v1371, v1374 in pairs(p_u_203.parralax) do
			for v1395, v1394 in ipairs(v1374) do 
				v1394.tickColor = (v1394.tickColor) * Functions.ColorToVec(v225)
			end
		end
	end
	if p_u_203.darkMatter then
		local v229 = math.sin(p205)
		if p_u_203.hardcore then
			local v230 = 0.8 + v229 * 0.2
			local vvvv = Vector3.new(v230, 13 + 7 * v229, 15 + 5 * v229)
			for _, v231 in ipairs(p_u_203.meshes) do
				v231.VertexColor = vvvv
			end
			for v1370, v1371 in pairs(p_u_203.parralax) do
				for v1392, v1395 in ipairs(v1371) do
					v1395.tickColor = (v1395.tickColor) * vvvv
				end
			end
		else
			local v232 = not p_u_203.shiny and 0.6 or 0.75 + math.sin(p205) * 0.2
			local vvvv = Vector3.new(15 + 5 * v229, v232, 13 + 7 * v229)
			for _, v233 in ipairs(p_u_203.meshes) do
				v233.VertexColor = vvvv
			end
			for v1370, v1371 in pairs(p_u_203.parralax) do
				for v1392, v1395 in ipairs(v1371) do
					v1395.tickColor = (v1395.tickColor) * vvvv
				end
			end
		end
	end
	if p_u_203.shiny then
		if p_u_203.golden then
			local v234 = math.sin(p205) * 0.25
			local vvvv = Vector3.new(2.2 + v234, 2.2 + v234, 2.2 + v234)
			for _, v235 in ipairs(p_u_203.meshes) do
				v235.VertexColor = vvvv
			end
			for v1370, v1371 in pairs(p_u_203.parralax) do
				for v1392, v1395 in ipairs(v1371) do
					v1395.tickColor = (v1395.tickColor) * vvvv
				end
			end
		elseif not (p_u_203.golden or p_u_203.rainbow or p_u_203.darkMatter) then
			local v236 = math.sin(p205) * 0.2
			local vvvv = Vector3.new(1.8 + v236, 1.8 + v236, 1.8 + v236)
			for _, v237 in ipairs(p_u_203.meshes) do
				v237.VertexColor = vvvv
			end
			for v1370, v1371 in pairs(p_u_203.parralax) do
				for v1392, v1395 in ipairs(v1371) do
					v1395.tickColor = (v1395.tickColor) * vvvv
				end
			end
		end
	end
	for v1441, v1439 in pairs(p_u_203.parralax) do
		if not p_u_203.golden then
			processParalax(v1441, v1439, p206, p207, p57)
		end	
	end
	if p_u_203.hardcore then
		local v238 = math.sin(p205 * 5) * 0.2 + 0.8
		for _, v239 in ipairs(p_u_203.hardcoreDecals) do
			v239.Transparency = v238
		end 
	end
	if v208.christmasLights then
		local v240 = math.floor(p205) % 2 == 0
		local v241 = v_u_209:FindFirstChild("LightsA")
		local v242 = v_u_209:FindFirstChild("LightsB")
		local v243, v244
		if p_u_203.golden then
			v243 = v240 and Color3.fromRGB(255, 255, 0) or Color3.fromRGB(255, 255, 255)
			v244 = v240 and Color3.fromRGB(255, 255, 255) or Color3.fromRGB(255, 255, 0)
		elseif p_u_203.darkMatter then
			v243 = v240 and Color3.fromRGB(255, 255, 0) or Color3.fromRGB(255, 255, 255)
			v244 = v240 and Color3.fromRGB(255, 255, 255) or Color3.fromRGB(255, 255, 0)
		else
			v243 = v240 and Color3.fromRGB(126, 255, 0) or Color3.fromRGB(255, 44, 26)
			v244 = v240 and Color3.fromRGB(255, 44, 26) or Color3.fromRGB(126, 255, 0)
		end
		v241.Color = v243
		v242.Color = v244
	end
	if p_u_203.id == "402" then
		local v245 = v_u_209:FindFirstChild("Back")
		if v245 and v245:IsA("Attachment") then
			local v246 = v245:FindFirstChild("Sparkles")
			if v246 and v246:IsA("ParticleEmitter") then
				v246.Enabled = p_u_203.moving
			end
		end
	end
	if v208.balloon then
		local v247 = v208.balloonScale or Vector3.one
		v210 = v210 * (v247 * Functions.Lerp(0.95, 1.05, (1 + math.sin(p205 * (v208.flySpeed or 1) * (v208.balloonSpeed or 1) * 4)) / 2) + Vector3.one - v247)
	end
	if v208.jelly then
		local v248 = (0.87535218700542) * 2 --5.5 / 2 * math.pi * 2
		local v249, v250 =  0, 0.025
		if p_u_203.moving or p_u_203.farming then  
			v249 = 1
			v250 = 0.14285714285714 
		end
		local v251 = 1 - math.pow(1 - v250, p206 * 60)
		local v252 = (p_u_203.jellyMoving or v249) * (1 - v251) + v249 * v251
		p_u_203.jellyMoving = v252
		local v253 = (p_u_203.jellyTick or 0) + p206 * (0.3 * (1 - v252) + v248 * v252)
		p_u_203.jellyTick = v253
		local v254 = 1 * (1 - v252) + 1.25 * v252
		local v255 = 2 * math.pi * v253
		local v256 = Functions.Map(math.sin(v255 + math.pi / 4), -1, 1, 0.9, 1.1) * v254
		v210 = v210 * Vector3.new(v256, Functions.Map(math.sin(v255), -1, 1, 0.8, 1.2) * v254, v256)
	end
	if p_u_203.id == "988" or p_u_203.id == "989" then
		local v257 = { "rbxassetid://13560436163", "rbxassetid://13560436029", "rbxassetid://13560435915" }
		if p_u_203.mesh.TextureId == "rbxassetid://13560728786" and math.random() < 0.01 then
			p_u_203.mesh.TextureId = v257[math.random(1, #v257)]
			task.delay(0.1, function()
				-- upvalues: (copy) p_u_203
				if p_u_203 and p_u_203.part.Parent and p_u_203.mesh then
					p_u_203.mesh.TextureId = "rbxassetid://13560728786"
				end
			end)
		end
	end
	local v258 = v210 * p_u_203.overrideScale
	if p_u_203.scale ~= v258 then
		p_u_203.scale = v258
		local v259 = p_u_203.scaler
		if not v259 then
			v259 = Functions.Scaler(nil, function(p260)
				local noscale = p260:GetAttribute("NoScale")
				return not noscale
			end)
			p_u_203.scaler = v259
		end
		assert(v259)
		v259(v_u_209, v258)
	end
	if p207 then
		for _, v261 in pairs(p_u_203.scriptedWelds) do
			local v262 = v261.part
			local v263 = v261.offset
			if v261.scaling then
				v263 = v263 - v263.Position + v263.Position * p_u_203.scale
			end
			local v264 = v261.rotationRate
			if v264 then
				local v265 = v264 * p205
				v263 = v263 * CFrame.fromOrientation(v265.X, v265.Y, v265.Z)
			end
			if p_u_203.id == "606" or p_u_203.id == "2148" then
				if v262.Name == "Basketball" then
					v263 = v263 + Vector3.new(0, PetCmds.BasketballBounce(p205, 3, p_u_203.id == "606" and 2 or 5, 2), 0) * p_u_203.scale
				end
			end
			if p_u_203.id == "630" or p_u_203.id == "631" then
				if v262.Name == "Beachball" then
					v263 = v263 + Vector3.new(0, PetCmds.BasketballBounce(p205, 3, (p_u_203.id == "630" or p_u_203.id == "631") and 2 or 5, 2), 0) * p_u_203.scale
				end
			end
			v262:PivotTo((v261.root:GetPivot():ToWorldSpace(v263)))
		end
	end
	if v208.flipbookAnimationSpeed then
		local v52 = p57.golden and v208.flipbookAnimationGold or v208.flipbookAnimation;
		assert(v52);
		local v53 = v52[(math.floor(p57 / v208.flipbookAnimationSpeed) - 1) % #v52 + 1];
		local t_mesh = p57.mesh;
		if t_mesh.TextureId ~= v53 then
			t_mesh.TextureId = v53;
		end
	end
	local v269 = p_u_203.billboard
	if v269 and p204 then
		if not p_u_203.nicknameUpdateTick or p_u_203.nicknameUpdateTick <= p205 then
			v269.Nickname.Text = p204.nk or ""
			p_u_203.nicknameUpdateTick = p205 + 2 + 2 * math.random()
		end
		if p204.snk and not p_u_203.signedAnimation then
			p_u_203.signedAnimation = GUIFX.Rainbow(v269.Nickname, "TextColor3", 3)
		elseif not p204.snk and p_u_203.signedAnimation then
			p_u_203.signedAnimation()
			p_u_203.signedAnimation = nil
			v269.Nickname.TextColor3 = Color3.new(1, 1, 1)
		end
	end
	debug.profileend()
end

return PetCmds
