--[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⣿⣿⣿⣷⣦⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣿⣿⣷⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⡿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⡇⠀⠀⢀⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⡇⠀⠀⢸⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⣿⣿⣿⣧⠀⠀⠘⣿⣿⣿⣷⣤⣀⣀⠀⠀⣀⣀⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⡄⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣷⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⡆⠀⠀⠀⠈⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠿⠀⠀⠀⠀⠀⠀⠈⠉⠛⠻⠿⠿⠿⠟⠛⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

	Velvet Groups rbx.lua Framework [2025] - [2025]
	Written by kalidrios - 1037898275229020250
	Developed with a VScode and Rojo.
	
	-+-+-+- SPECIFICS -+-+-+-
	_L.PetUI
	===========
		
	===========
	
--]]
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

local table1 = {};
local table2 = {
	Rare = 1,
	Epic = 2,
	Legendary = 2,
	Mythical = 1,
	Secret = 1,
	Event = 1,
	Exclusive = 1
};
local ReplicatedStorage = game:GetService("ReplicatedStorage");
local Players = game:GetService("Players");
local RunService = game:GetService("RunService");
local Assets = ReplicatedStorage:WaitForChild("Assets");
local Library = ReplicatedStorage:WaitForChild("Library");
local Modules = Library:WaitForChild("Modules");
local Client = Library:WaitForChild("Client");
local m_Shared = require(Library.Shared);
local m_Variables = require(Library.Variables);
local m_Directory = require(Library.Directory);
local _ = require(Modules.Pets);
local m_Functions = require(Library.Functions);
local m_Audio = require(Library.Audio);
local m_RAPShared = require(Library.RAPShared);
local m_PetCmds = require(Client.PetCmds);
local m_Network = require(Client.Network);
local m_Save = require(Client.Save);
local m_Settings = require(Client.Settings);
local m_InfoOverlay = require(Client.InfoOverlay);
local _ = require(Client.RAPCmds);
local m_FFlags = require(Client.FFlags);
local t_LocalPlayer = Players.LocalPlayer;
local Random_new_ret = Random.new();
local u1 = nil;
local Color3_fromHSV_ret = nil;
local u2 = nil;
function prepareColor(p5)
	return m_Functions.ClampColor((m_Functions.CorrectColor((m_Functions.VecToColor(p5)))));
end;
function table1.CreateStaticHover(p1, p2, p3) -- Line: 75
	--[[
		Upvalues:
			[1] = t_LocalPlayer
			[2] = m_Directory
			[3] = m_Save
			[4] = m_Shared
			[5] = m_Functions
			[6] = m_Settings
			[7] = m_FFlags
			[8] = m_RAPShared
			[9] = m_InfoOverlay
			[10] = m_Audio
	--]]
	debug.profilebegin("PetUI.CreateStaticHover");
	local v1 = t_LocalPlayer;
	local table3 = {
		id = p2,
		uid = "",
		idt = 0,
		s = 0,
		e = false,
		nk = t_LocalPlayer.DisplayName
	};
	if p3 then
		for key3, val3 in pairs(p3) do
			table3[key3] = val3;
		end
	end
	local t_id = table3.id;
	local u4 = m_Directory.Pets[t_id];
	local _ = table3.idt;
	local v2 = m_Save.Get(v1);
	if v2 then
		local _ = m_Shared.HasPetEquipped(v2, table3);
	end
	local _ = table3.s;
	local _ = table3.l;
	local t_g = table3.g;
	local t_r = table3.r;
	local t_dm = table3.dm;
	local t_sh = table3.sh;
	local t_hc = table3.hc;
	local t_powers = table3.powers;
	local t_isGift = u4.isGift;
	if (not t_dm or not u4.darkMatterThumbnail) and (not t_g or not u4.goldenThumbnail) then
		local _ = u4.thumbnail;
	end
	local _ = u4.name;
	local _ = u4.tradeable;
	local t_rarity = u4.rarity;
	local bool1 = false;
	local bool2 = false;
	local bool3 = false;
	for _, val1 in ipairs(t_powers or {}) do
		if val1[1] == "Titanic" then
			bool1 = true;
			break;
		end
		if val1[1] == "Best Friend" then
			bool2 = true;
			break;
		end
		if val1[1] ~= "Companion" then continue end
		bool3 = true;
	end
	if u4.titanic then
		bool1 = true;
	elseif u4.huge then
		bool2 = true;
	elseif u4.companionEnchantLevel ~= nil then
		bool3 = true;
	end
	local FindFirstAncestorWhichIsA_ret = nil;
	local u5 = false;
	local coroutine_wrap_ret = coroutine.wrap(function() -- Line: 143
		--[[
			Upvalues:
				[1] = p1
				[2] = FindFirstAncestorWhichIsA_ret
				[3] = u5
		--]]
		while not p1.Parent do
			wait(0.5);
		end
		FindFirstAncestorWhichIsA_ret = p1:FindFirstAncestorWhichIsA("ScreenGui");
		local t_Parent = p1.Parent;
		local bool4 = true;
		if t_Parent and t_Parent.ClassName == "ScrollingFrame" then
			local u22 = 0;
			local u23 = 0;
			local Connect_ret = nil;
			Connect_ret = game:GetService("RunService").RenderStepped:Connect(function(p10) -- Line: 180
				--[[
					Upvalues:
						[1] = u22
						[2] = u23
						[3] = p1
						[4] = Connect_ret
						[5] = u5
						[6] = FindFirstAncestorWhichIsA_ret
						[7] = t_Parent
						[8] = bool4
				--]]
				u22 = u22 + p10;
				if u22 < u23 then return end
				u23 = u22 + (math.random() * 0.5 + 0.25);
				debug.profilebegin("PetUI.Create.Culling");
				if not p1.Parent then
					Connect_ret:Disconnect();
					debug.profileend();
					return;
				end
				local bool5;
				if FindFirstAncestorWhichIsA_ret.Enabled then
					if p1.Visible then
						local t_Y = p1.AbsolutePosition.Y;
						local t_Y2 = t_Parent.AbsolutePosition.Y;
						local v30 = t_Parent.AbsoluteWindowSize.Y * 2;
						if t_Y2 + v30 <= t_Y or t_Y <= t_Y2 - v30 then
							bool5 = false;
						else
							bool5 = true;
						end
					else
						bool5 = false;
					end
				else
					bool5 = false;
				end
				if u5 ~= bool5 or bool4 then
					bool4 = false;
					u5 = bool5;
					p1:SetAttribute("isVisible", u5);
				end
				debug.profileend();
			end);
		else
			p1:SetAttribute("isVisible", true);
			u5 = true;
		end
	end);
	coroutine_wrap_ret();
	local function ShowOverlay() -- Line: 224
		--[[
			Upvalues:
				[1] = table3
				[2] = u4
				[3] = t_rarity
				[4] = t_isGift
				[5] = t_hc
				[6] = t_dm
				[7] = t_r
				[8] = t_g
				[9] = t_sh
				[10] = bool3
				[11] = m_Shared
				[12] = bool2
				[13] = bool1
				[14] = m_Save
				[15] = t_id
				[16] = m_Functions
				[17] = m_Settings
				[18] = p1
				[19] = m_Directory
				[20] = m_FFlags
				[21] = m_RAPShared
				[22] = m_InfoOverlay
		--]]
		debug.profilebegin("PetUI.Create.ShowOverlay");
		if not table3 then
			debug.profileend();
			return;
		end
		if not table3 then
			debug.profileend();
			return;
		end
		local table4 = {{
			"Title",
			u4.name,
			t_rarity
		}};
		if not t_isGift then
			table.insert(table4, {
				"Nickname",
				'"' .. (table3.nk or "???") .. '"',
				table3.snk
			});
		end
		if t_hc then
			table.insert(table4, {
				"Block",
				"Hardcore",
				"Hardcore"
			});
		end
		table.insert(table4, {
			"Rarity",
			t_rarity
		});
		if t_dm then
			table.insert(table4, {
				"Block",
				"Dark Matter",
				"Dark Matter"
			});
		elseif t_r then
			table.insert(table4, {
				"Block",
				"Rainbow",
				"Rainbow"
			});
		elseif t_g then
			table.insert(table4, {
				"Block",
				"Golden",
				"Golden"
			});
		end
		if t_sh then
			table.insert(table4, {
				"Block",
				"Shiny",
				"Shiny"
			});
		end
		local v8 = nil;
		local v9 = nil;
		if bool3 then
			v8, v9 = m_Shared.GetPowerDir("Companion", tostring(u4.companionEnchantLevel));
		elseif bool2 then
			v8, v9 = m_Shared.GetPowerDir("Best Friend", "1");
		elseif bool1 then
			v8, v9 = m_Shared.GetPowerDir("Titanic", "1");
		end
		--v2
		local rep = table3.rep
		if u4.replacements and rep then
			if #rep > 0 then
				for i,v in ipairs(rep) do
					table.insert(table4, {"Replacement", table3.id, v})
				end
			end
		end
		if v8 and v9 then
			table.insert(table4, {
				"Power",
				v8.title,
				v8.desc,
				v9.isUnique
			});
		end
		if u4.guarenteedEnchants then
			for _, val5 in ipairs(u4.guarenteedEnchants) do
				local unpack_ret1, unpack_ret2, _ = unpack(val5);
				local v18, v19 = m_Shared.GetPowerDir(unpack_ret1, unpack_ret2);
				if not v18 or not v19 then continue end
				table.insert(table4, {
					"Power",
					v18.title,
					v18.desc,
					v19.isUnique
				});
			end
		end
		local t_merchData = table3.merchData;
		local t_serialData = table3.serialData;
		if m_Shared.ShowPetExists(table3) then
			local v12 = m_Save.Get();
			assert(v12);
			local GetPetsInExistence_ret1, GetPetsInExistence_ret2 = GetPetsInExistence(t_id);
			if GetPetsInExistence_ret1 and GetPetsInExistence_ret2 then
				local v20 = GetPetsInExistence_ret1 < 100000 and m_Functions.Commas(GetPetsInExistence_ret1) or m_Functions.NumberShorten(GetPetsInExistence_ret1);
				table.insert(table4, {
					"Rare",
					v20 .. " Exist"
				});
			end
		end
		if t_merchData then
			table.insert(table4, {
				"MerchSerial",
				t_merchData.serial or 0
			});
			table.insert(table4, {
				"MerchPlayer",
				t_merchData.user or -1
			});
		elseif t_serialData then
			table.insert(table4, {
				"MerchSerial",
				t_serialData.serial or 0
			});
			table.insert(table4, {
				"MerchPlayer",
				t_serialData.user or -1
			});
		end
		if table3.snk then
			table.insert(table4, {"Signed"});
		end
		if m_Settings.ShowPetDebug then
			table.insert(table4, {
				"Nickname",
				"PetID: " .. table3.id
			});
			table.insert(table4, {
				"debug_UID",
				table3.uid,
				p1
			});
		end
		if u4.tradeable and t_isGift then
			if u4.giftEggId then
				local v21 = m_Directory.Eggs[u4.giftEggId];
				table.insert(table4, {
					"Nickname",
					"Contains:"
				});
				table.insert(table4, {
					"GiftPetOdds",
					u4.giftEggId,
					v21.drops
				});
			end
			if u4.tradeable then
				table.insert(table4, {"Tradeable"});
			end
		end
		if m_FFlags.Get(m_FFlags.Keys.RAP) or m_FFlags.CanBypass() then
			local v13 = m_RAPShared.CreateKey(table3);
			if v13 then
				table.insert(table4, {
					"RAP",
					v13
				});
			end
		end
		if m_FFlags.CanBypass() then
			local t_o = table3.o;
			if t_o then
				table.insert(table4, {
					"OpenedBy",
					t_o[1],
					t_o[2]
				});
			end
			local t_h = table3.h;
			if t_h then
				table.insert(table4, {
					"OwnerCount",
					t_h.n
				});
				local v22 = t_h.l[2];
				if v22 then
					table.insert(table4, {
						"LastOwner",
						v22[1],
						v22[2]
					});
				end
			end
		end
		m_InfoOverlay.Add(p1, unpack(table4));
		debug.profileend();
	end
	p1.MouseEnter:Connect(function() -- Line: 375
		--[[
			Upvalues:
				[1] = m_Audio
				[2] = ShowOverlay
		--]]
		m_Audio.Play("rbxassetid://6907626084", script, 1, 0.2);
		ShowOverlay();
	end);
	p1.SelectionGained:Connect(function() -- Line: 380
		--[[
			Upvalues:
				[1] = m_Audio
				[2] = ShowOverlay
		--]]
		m_Audio.Play("rbxassetid://6907626084", script, 1, 0.2);
		ShowOverlay();
	end);
	debug.profileend();
end
function table1.Create(p4, p5, p6) -- Line: 388
	--[[
		Upvalues:
			[1] = t_LocalPlayer
			[2] = m_PetCmds
			[3] = m_Save
			[4] = m_Shared
			[5] = m_Directory
			[6] = Assets
			[7] = RunService
			[8] = m_Functions
			[9] = table2
			[10] = Color3_fromHSV_ret
			[11] = Random_new_ret
			[12] = m_Settings
			[13] = m_Variables
			[14] = m_FFlags
			[15] = m_RAPShared
			[16] = m_InfoOverlay
			[17] = m_Audio
	--]]
	debug.profilebegin("PetUI.Create");
	local u18;
	local u19;
	if p6 then
		u19 = t_LocalPlayer;
		local table6 = {
			id = p5,
			uid = "",
			idt = 0,
			s = 0,
			e = false,
			nk = t_LocalPlayer.DisplayName
		};
		u18 = table6;
		for key4, val4 in pairs(p6) do
			u18[key4] = val4;
		end
	else
		local v6, v7 = m_PetCmds.Get(p5);
		if not v6 or not v7 then
			debug.profileend();
			return;
		end
		assert(v6 and v7);
		u18 = v6;
		u19 = v7;
	end
	local t_id2 = u18.id;
	local t_idt = u18.idt;
	local v3 = m_Save.Get(u19);
	local u7 = v3 and m_Shared.HasPetEquipped(v3, u18);
	local t_s = u18.s;
	local t_l = u18.l;
	local u8 = u18.g;
	local u9 = u18.r;
	local u10 = u18.dm;
	local t_sh2 = u18.sh;
	local t_hc2 = u18.hc;
	local t_powers2 = u18.powers;
	local u11 = m_Directory.Pets[t_id2];
	local t_isGift2 = u11.isGift;
	local u12 = u10 and u11.darkMatterThumbnail or u8 and u11.goldenThumbnail or u11.thumbnail;
	local _ = u11.name;
	local _ = u11.tradeable;
	local t_rarity2 = u11.rarity;
	local bool6 = false;
	local bool7 = false;
	local bool8 = false;
	for _, val2 in ipairs(t_powers2 or {}) do
		if val2[1] == "Titanic" then
			bool6 = true;
			break;
		end
		if val2[1] == "Best Friend" then
			bool7 = true;
			break;
		end
		if val2[1] ~= "Companion" then continue end
		bool8 = true;
	end
	local FindFirstAncestorWhichIsA_ret2 = nil;
	local u13 = false;
	local coroutine_wrap_ret2 = coroutine.wrap(function() -- Line: 467
		--[[
			Upvalues:
				[1] = p4
				[2] = FindFirstAncestorWhichIsA_ret2
				[3] = u13
		--]]
		while not p4.Parent do
			wait(0.5);
		end
		FindFirstAncestorWhichIsA_ret2 = p4:FindFirstAncestorWhichIsA("ScreenGui");
		local t_Parent2 = p4.Parent;
		local bool9 = true;
		if t_Parent2 and t_Parent2.ClassName == "ScrollingFrame" then
			local u24 = 0;
			local u25 = 0;
			local Connect_ret2 = nil;
			Connect_ret2 = game:GetService("RunService").RenderStepped:Connect(function(p11) -- Line: 504
				--[[
					Upvalues:
						[1] = u24
						[2] = u25
						[3] = p4
						[4] = Connect_ret2
						[5] = u13
						[6] = FindFirstAncestorWhichIsA_ret2
						[7] = t_Parent2
						[8] = bool9
				--]]
				u24 = u24 + p11;
				if u24 < u25 then return end
				u25 = u24 + (math.random() * 0.5 + 0.25);
				debug.profilebegin("PetUI.Create.Culling");
				if not p4.Parent then
					Connect_ret2:Disconnect();
					debug.profileend();
					return;
				end
				local bool10;
				if FindFirstAncestorWhichIsA_ret2.Enabled then
					if p4.Visible then
						local t_Y3 = p4.AbsolutePosition.Y;
						local t_Y4 = t_Parent2.AbsolutePosition.Y;
						local v31 = t_Parent2.AbsoluteWindowSize.Y * 2;
						if t_Y4 + v31 <= t_Y3 or t_Y3 <= t_Y4 - v31 then
							bool10 = false;
						else
							bool10 = true;
						end
					else
						bool10 = false;
					end
				else
					bool10 = false;
				end
				if u13 ~= bool10 or bool9 then
					bool9 = false;
					u13 = bool10;
					p4:SetAttribute("isVisible", u13);
				end
				debug.profileend();
			end);
		else
			p4:SetAttribute("isVisible", true);
			u13 = true;
		end
	end);
	coroutine_wrap_ret2();
	local coroutine_wrap_ret3 = coroutine.wrap(function() -- Line: 548
		--[[
			Upvalues:
				[1] = FindFirstAncestorWhichIsA_ret2
				[2] = p4
				[3] = Assets
				[4] = u13
				[5] = RunService
		--]]
		local Clone_ret = nil;
		local v10 = false;
		local v11 = 0;
		while not FindFirstAncestorWhichIsA_ret2 do
			wait(0.5);
		end
		while p4 and p4.Parent and not p4.PetIcon.IsLoaded do
			debug.profilebegin("PetUI.Create.PetIconAnimation");
			if not Clone_ret then
				Clone_ret = Assets.UI.Inventory.LoadingPetIcon:Clone();
				Clone_ret.Parent = p4.PetIcon;
			end
			if u13 and os.clock() - v11 >= 0.1 then
				v11 = os.clock();
				Clone_ret.TextTransparency = v10 and 0.5 or 0;
				v10 = not v10;
			end
			debug.profileend();
			if u13 and FindFirstAncestorWhichIsA_ret2.Enabled then
				RunService.RenderStepped:Wait();
			else
				wait(0.5);
			end
		end
		if Clone_ret then
			Clone_ret:Destroy();
		end
	end);
	coroutine_wrap_ret3();
	local function UpdateVisual() -- Line: 580
		--[[
			Upvalues:
				[1] = p4
				[2] = p5
				[3] = u12
				[4] = u11
				[5] = t_hc2
				[6] = u10
				[7] = t_isGift2
				[8] = t_s
				[9] = bool6
				[10] = bool7
				[11] = bool8
				[12] = m_Functions
		--]]
		debug.profilebegin("PetUI.Create.UpdateVisual");
		p4.Name = p5;
		p4.PetIcon.Image = u12;
		p4.RarityGradient.Visible = not u11.huge and not u11.titanic;
		if t_hc2 and u10 then
			p4.PetIcon.ImageColor3 = Color3.fromRGB(42, 252, 255);
		else
			p4.PetIcon.ImageColor3 = Color3.new(1, 1, 1);
		end
		if u11.colorVariants and u18.cv then
			local v91 = u11.colorVariants[u18.cv];
			if v91 then
				p4.PetIcon.ImageColor3 = v91.Color;
			end;
		end;
		local v92 = nil;
		if u18.vc then
			v92 = Vector3.new(table.unpack(u18.vc));
		elseif u11.vertexColor then
			v92 = u11.vertexColor;
		end;
		if v92 then
			p4.PetIcon.ImageColor3 = prepareColor(v92);
		end;
		local Level = p4:FindFirstChild("Level");
		if Level then
			if t_isGift2 then
				Level.Visible = false;
			elseif t_s then
				if bool6 then
					Level.Text = "????";
				elseif bool7 then
					Level.Text = "???";
				elseif bool8 then
					Level.Text = "??";
				else
					Level.Text = m_Functions.NumberShorten(t_s);
				end
			end
		end
		if t_hc2 then
			p4.HC.Visible = true;
		end
		debug.profileend();
	end
	UpdateVisual();
	local function RefreshPetData() -- Line: 618
		--[[
			Upvalues:
				[1] = p6
				[2] = m_PetCmds
				[3] = p5
				[4] = u18
				[5] = u19
				[6] = m_Save
				[7] = u7
				[8] = m_Shared
				[9] = t_s
				[10] = t_idt
				[11] = u8
				[12] = u9
				[13] = u10
				[14] = t_l
				[15] = t_hc2
				[16] = t_powers2
				[17] = u12
				[18] = u11
				[19] = UpdateVisual
		--]]
		debug.profilebegin("PetUI.Create.RefreshPetData");
		if not p6 then
			local v14, v15 = m_PetCmds.Get(p5);
			if v14 and v15 then
				u18 = v14;
				u19 = v15;
				local v23 = m_Save.Get(u19);
				u7 = v23 and m_Shared.HasPetEquipped(v23, u18);
				t_s = u18.s;
				t_idt = u18.idt;
				local t_g2 = u18.g;
				local t_r2 = u18.r;
				local t_dm2 = u18.dm;
				u8 = t_g2;
				u9 = t_r2;
				u10 = t_dm2;
				t_l = u18.l;
				t_hc2 = u18.hc;
				t_powers2 = u18.powers;
				u12 = u10 and u11.darkMatterThumbnail or u8 and u11.goldenThumbnail or u11.thumbnail;
				UpdateVisual();
			end
		end
		debug.profileend();
	end
	local UIStroke = nil;
	local Clone_ret2 = nil;
	if not t_isGift2 then
		if t_rarity2 == "Legendary" or t_rarity2 == "Mythical" or t_rarity2 == "Secret" or t_rarity2 == "Event" or t_rarity2 == "Exclusive" then
			local Clone_ret3 = Assets.UI.Raritys:FindFirstChild(t_rarity2):Clone();
			Clone_ret3.Parent = p4.RarityGradient;
			p4.RarityGradient.Visible = not u11.huge and not u11.titanic;
			p4.BackgroundTransparency = 1;
			local Level2 = p4:FindFirstChild("Level");
			if Level2 then
				UIStroke = Level2:FindFirstChildOfClass("UIStroke");
				UIStroke.Color = Color3.new(1, 1, 1);
				Clone_ret2 = Clone_ret3:Clone();
				Clone_ret2.Parent = UIStroke;
			end
			local coroutine_wrap_ret4 = coroutine.wrap(function() -- Line: 655
				--[[
					Upvalues:
						[1] = FindFirstAncestorWhichIsA_ret2
						[2] = p4
						[3] = u13
						[4] = Clone_ret3
						[5] = Clone_ret2
						[6] = RunService
				--]]
				while not FindFirstAncestorWhichIsA_ret2 do
					wait(0.5);
				end
				while p4 and p4.Parent do
					if FindFirstAncestorWhichIsA_ret2.Enabled and u13 then
						local v29 = os.clock() * 60;
						Clone_ret3.Rotation = v29;
						if Clone_ret2 then
							Clone_ret2.Rotation = v29;
						end
					end
					if u13 and FindFirstAncestorWhichIsA_ret2.Enabled then
						RunService.RenderStepped:Wait();
					else
						wait(0.5);
					end
				end
			end);
			coroutine_wrap_ret4();
		else
			p4.RarityGradient.Visible = false;
		end
	end
	if t_isGift2 then
		local Clone_ret8 = Assets.UI.Inventory.GiftboxIcon:Clone();
		Clone_ret8.Parent = p4;
		p4.BackgroundColor3 = Color3.fromRGB(240, 107, 252);
	end
	local v4 = table2[t_rarity2];
	if v4 and not t_l then
		for index1 = 1, v4 do
			local Clone_ret7 = Assets.UI.Inventory.Star:Clone();
			if t_rarity2 == "Mythical" or t_rarity2 == "Secret" or t_rarity2 == "Event" then
				Clone_ret7.Image = "rbxassetid://12370956807";
			elseif t_rarity2 == "Exclusive" then
				Clone_ret7.Image = "rbxassetid://12371216119";
			end
			if u11.titanic then
				Clone_ret7.Image = "rbxassetid://12378209702";
			end
			Clone_ret7.Parent = p4.Stars;
		end
		p4.Stars.Visible = true;
		p4.Locked.Visible = false;
	end
	if t_l then
		p4.Stars.Visible = false;
		p4.Locked.Visible = true;
	end
	if u9 then
		local coroutine_wrap_ret8 = coroutine.wrap(function() -- Line: 717
			--[[
				Upvalues:
					[1] = FindFirstAncestorWhichIsA_ret2
					[2] = p4
					[3] = u9
					[4] = u13
					[5] = Color3_fromHSV_ret
					[6] = RunService
			--]]
			while not FindFirstAncestorWhichIsA_ret2 do
				wait(0.5);
			end
			while p4 and p4.Parent and u9 do
				if u13 and FindFirstAncestorWhichIsA_ret2.Enabled and p4.PetIcon.ImageColor3 ~= Color3.new(0, 0, 0) then
					p4.PetIcon.ImageColor3 = Color3_fromHSV_ret;
				end
				if u13 and FindFirstAncestorWhichIsA_ret2.Enabled then
					RunService.RenderStepped:Wait();
				else
					wait(0.5);
				end
			end
		end);
		coroutine_wrap_ret8();
	end
	if t_rarity2 == "Mythical" or t_rarity2 == "Secret" or t_rarity2 == "Event" or t_rarity2 == "Exclusive" then
		local function Sparkle() -- Line: 737
			--[[
				Upvalues:
					[1] = Assets
					[2] = Random_new_ret
					[3] = p4
					[4] = m_Functions
			--]]
			debug.profilebegin("PetUI.Create.Sparkle");
			local Clone_ret6 = Assets.UI.Inventory.Sparkle:Clone();
			Clone_ret6.Position = UDim2.new(Random_new_ret:NextNumber(), 0, Random_new_ret:NextNumber(), 0);
			Clone_ret6.Size = UDim2.new(0, 0, 0, 0);
			Clone_ret6.Parent = p4;
			local NextNumber_ret2 = Random_new_ret:NextNumber(0.2, 0.35);
			m_Functions.Tween(Clone_ret6, {Size = UDim2.new(NextNumber_ret2, 0, NextNumber_ret2, 0)}, table.pack(Random_new_ret:NextNumber(1.5, 2.75), "Quad", "Out")).Completed:Connect(function() -- Line: 747
				--[[
					Upvalues:
						[1] = m_Functions
						[2] = Clone_ret6
						[3] = Random_new_ret
				--]]
				m_Functions.Tween(Clone_ret6, {Size = UDim2.new(0, 0, 0, 0)}, table.pack(Random_new_ret:NextNumber(0.75, 1.25), "Sine", "InOut")).Completed:Wait();
				Clone_ret6:Destroy();
			end);
			debug.profileend();
		end
		local coroutine_wrap_ret7 = coroutine.wrap(function() -- Line: 755
			--[[
				Upvalues:
					[1] = FindFirstAncestorWhichIsA_ret2
					[2] = p4
					[3] = u13
					[4] = Sparkle
					[5] = Random_new_ret
			--]]
			while not FindFirstAncestorWhichIsA_ret2 do
				wait(0.5);
			end
			while p4 and p4.Parent do
				if u13 and FindFirstAncestorWhichIsA_ret2.Enabled then
					Sparkle();
				end
				wait(Random_new_ret:NextNumber(1, 2.5));
			end
		end);
		coroutine_wrap_ret7();
	end
	if t_sh2 then
		local Clone_ret4 = Assets.UI.Inventory.ShinePulse:Clone();
		Clone_ret4.Parent = p4;
		local coroutine_wrap_ret5 = coroutine.wrap(function() -- Line: 845
			--[[
				Upvalues:
					[1] = FindFirstAncestorWhichIsA_ret2
					[2] = p4
					[3] = Random_new_ret
					[4] = u13
					[5] = Clone_ret4
					[6] = m_Functions
					[7] = RunService
			--]]
			while not FindFirstAncestorWhichIsA_ret2 do
				wait(0.5);
			end
			while p4 and p4.Parent do
				local NextNumber_ret = Random_new_ret:NextNumber(0.5, 1);
				local _ = Random_new_ret:NextNumber(0.5, 1);
				if u13 and FindFirstAncestorWhichIsA_ret2.Enabled and Clone_ret4.ShineImage then
					m_Functions.Tween(Clone_ret4.ShineImage, {Size = UDim2.new(1.7, 0, 1.7, 0)}, table.pack(NextNumber_ret, "Linear", "Out")).Completed:Wait();
					if Clone_ret4:FindFirstChild("ShineImage") then
						m_Functions.Tween(Clone_ret4.ShineImage, {Size = UDim2.new(1.05, 0, 1.05, 0)}, table.pack(NextNumber_ret, "Linear", "Out")).Completed:Wait();
					end
				else
					RunService.RenderStepped:Wait();
				end
			end
		end);
		coroutine_wrap_ret5();
		local function Shine() -- Line: 868
			--[[
				Upvalues:
					[1] = Assets
					[2] = p4
					[3] = m_Functions
			--]]
			debug.profilebegin("PetUI.Create.Shine");
			local Clone_ret5 = Assets.UI.Inventory.Shine:Clone();
			Clone_ret5.Position = UDim2.new(0.5, 0, 0.5, 0);
			Clone_ret5.Parent = p4;
			local t_ShineImage = Clone_ret5.ShineImage;
			m_Functions.Tween(t_ShineImage, {Position = UDim2.new(1.2, 0, 1.2, 0)}, table.pack(0.75, "Linear", "Out")).Completed:Connect(function() -- Line: 878
				--[[
					Upvalues:
						[1] = Clone_ret5
				--]]
				Clone_ret5:Destroy();
			end);
			debug.profileend();
		end
		local coroutine_wrap_ret6 = coroutine.wrap(function() -- Line: 885
			--[[
				Upvalues:
					[1] = FindFirstAncestorWhichIsA_ret2
					[2] = p4
					[3] = u13
					[4] = Shine
					[5] = Random_new_ret
			--]]
			while not FindFirstAncestorWhichIsA_ret2 do
				wait(0.5);
			end
			while p4 and p4.Parent do
				if u13 and FindFirstAncestorWhichIsA_ret2.Enabled then
					Shine();
				end
				wait(Random_new_ret:NextNumber(0.5, 3));
			end
		end);
		coroutine_wrap_ret6();
	end
	local function ToggleEquipped(p9) -- Line: 901
		--[[
			Upvalues:
				[1] = p4
				[2] = m_Functions
				[3] = UIStroke
				[4] = Clone_ret2
		--]]
		debug.profilebegin("PetUI.Create.ToggleEquipped");
		p4.BackgroundColor3 = p9 and Color3.fromRGB(69, 239, 69) or Color3.fromRGB(39, 233, 55);
		if p9 then
			p4.Equipped.Size = UDim2.new(1, 0, 1, 0);
			m_Functions.Tween(p4.Equipped, {Size = UDim2.new(0.4, 0, 0.4, 0)}, table.pack(0.25, "Back", "Out"));
		end
		local UIGradient = p4.RarityGradient:FindFirstChildOfClass("UIGradient");
		if UIGradient then
			UIGradient.Enabled = not p9;
			p4.RarityGradient.ImageColor3 = p9 and Color3.fromRGB(69, 239, 69) or Color3.new(1, 1, 1);
		end
		if UIStroke then
			if Clone_ret2 then
				Clone_ret2.Enabled = not p9;
			end
			UIStroke.Color = p9 and Color3.fromRGB(19, 48, 57) or Clone_ret2 and Color3.new(1, 1, 1) or Color3.fromRGB(19, 48, 57);
		end
		debug.profileend();
	end
	local function ShowOverlay()  
		debug.profilebegin("PetUI.Create.ShowOverlay");
		if not u18 then
			debug.profileend();
			return;
		end
		RefreshPetData();
		if not u18 then
			debug.profileend();
			return;
		end
		local table5 = {{
			"Title",
			u11.name,
			t_rarity2
		}};
		if not t_isGift2 then
			table.insert(table5, {
				"Nickname",
				'"' .. (u18.nk or "???") .. '"',
				u18.snk
			});
		end
		if t_hc2 then
			table.insert(table5, {
				"Block",
				"Hardcore",
				"Hardcore"
			});
		end
		table.insert(table5, {
			"Rarity",
			t_rarity2
		});
		if u10 then
			table.insert(table5, {
				"Block",
				"Dark Matter",
				"Dark Matter"
			});
		elseif u9 then
			table.insert(table5, {
				"Block",
				"Rainbow",
				"Rainbow"
			});
		elseif u8 then
			table.insert(table5, {
				"Block",
				"Golden",
				"Golden"
			});
		end
		if t_sh2 then
			table.insert(table5, {
				"Block",
				"Shiny",
				"Shiny"
			});
		end
		local world = m_Shared.IsHardcore and v3.Hardcore.World or v3.World
		if world == "Yeet" then
			local v642 = m_PetCmds.GetEquipped(t_LocalPlayer) 
			local pwr = m_Shared.GetYeetPower(u18, v642)
			if pwr >= 0 then 
				table.insert(table5, {"YeetPower", m_Functions.NumberShorten(pwr)})
			end
		end	
		local rep = u18.rep
		if u11.replacements and rep then
			if #rep > 0 then
				for i,v in ipairs(rep) do
					table.insert(table5, {"Replacement", u18.id, v})
				end
			end
		end
		local cv = u18.cv
		if u11.colorReplacements and cv then
			table.insert(table5, {"ColorVariant", u18.id, cv})
		end
		if t_powers2 and #t_powers2 > 0 then
			for _, val6 in ipairs(t_powers2) do
				local unpack_ret1_2, unpack_ret2_2 = unpack(val6);
				local v24, v25 = m_Shared.GetPowerDir(unpack_ret1_2, unpack_ret2_2);
				assert(v24 and v25);
				table.insert(table5, {
					"Power",
					v24.title,
					v24.desc,
					v25.isUnique
				});
			end
		end

		local t_merchData2 = u18.merchData;
		local t_serialData2 = u18.serialData;
		if m_Shared.ShowPetExists(u18) then
			local v16 = m_Save.Get();
			assert(v16);
			local GetPetsInExistence_ret1_2, GetPetsInExistence_ret2_2 = GetPetsInExistence(t_id2);
			if GetPetsInExistence_ret1_2 and GetPetsInExistence_ret2_2 then
				local v26 = GetPetsInExistence_ret1_2 < 100000 and m_Functions.Commas(GetPetsInExistence_ret1_2) or m_Functions.NumberShorten(GetPetsInExistence_ret1_2);
				table.insert(table5, {
					"Rare",
					v26 .. " Exist"
				});
			end
		end
		if t_merchData2 then
			table.insert(table5, {
				"MerchSerial",
				t_merchData2.serial or 0
			});
			table.insert(table5, {
				"MerchPlayer",
				t_merchData2.user or -1
			});
		elseif t_serialData2 then
			table.insert(table5, {
				"MerchSerial",
				t_serialData2.serial or 0
			});
			table.insert(table5, {
				"MerchPlayer",
				t_serialData2.user or -1
			});
		end
		if u18.snk then
			table.insert(table5, {"Signed"});
		end
		if m_Settings.ShowPetDebug then
			table.insert(table5, {
				"Nickname",
				"PetID: " .. u18.id
			});
			table.insert(table5, {
				"debug_UID",
				u18.uid,
				p4
			});
		end
		if u11.tradeable and t_isGift2 then
			if u11.giftEggId then
				local v27 = m_Directory.Eggs[u11.giftEggId];
				table.insert(table5, {
					"Nickname",
					"Contains:"
				});
				table.insert(table5, {
					"GiftPetOdds",
					u11.giftEggId,
					v27.drops
				});
			end
			table.insert(table5, {
				"ClickToOpen",
				(m_Variables.Mobile and "Tap" or "Click") .. " to open"
			});
			if u11.tradeable then
				table.insert(table5, {"Tradeable"});
			end
		end
		if m_FFlags.Get(m_FFlags.Keys.RAP) or m_FFlags.CanBypass() then
			local v17 = m_RAPShared.CreateKey(u18);
			if v17 then
				table.insert(table5, {
					"RAP",
					v17
				});
			end
		end
		if m_FFlags.CanBypass() then
			local t_o2 = u18.o;
			if t_o2 then
				table.insert(table5, {
					"OpenedBy",
					t_o2[1],
					t_o2[2]
				});
			end
			local t_h2 = u18.h;
			if t_h2 then
				table.insert(table5, {
					"OwnerCount",
					t_h2.n
				});
				local v28 = t_h2.l[2];
				if v28 then
					table.insert(table5, {
						"LastOwner",
						v28[1],
						v28[2]
					});
				end
			end
		end
		m_InfoOverlay.Add(p4, unpack(table5));
		debug.profileend();
	end
	p4.MouseEnter:Connect(function() -- Line: 1064
		--[[
			Upvalues:
				[1] = m_Audio
				[2] = ShowOverlay
		--]]
		m_Audio.Play("rbxassetid://6907626084", script, 1, 0.2);
		ShowOverlay();
	end);
	p4.SelectionGained:Connect(function() -- Line: 1069
		--[[
			Upvalues:
				[1] = m_Audio
				[2] = ShowOverlay
		--]]
		m_Audio.Play("rbxassetid://6907626084", script, 1, 0.2);
		ShowOverlay();
	end);
	if not t_isGift2 then
		p4.Equipped:GetPropertyChangedSignal("Visible"):Connect(function() -- Line: 1075
			--[[
				Upvalues:
					[1] = p4
					[2] = ToggleEquipped
			--]]
			ToggleEquipped(p4.Equipped.Visible);
		end);
	end
	debug.profileend();
end
function GetPetsInExistence(p7) -- Line: 1088
	--[[
		Upvalues:
			[1] = u1
	--]]
	if not u1 then
		return nil, nil;
	end
	--if u1.pets[p7] then
	--	local t_am = u1.pets[p7].am;
	--	return t_am, u1.total;
    --end
    if u1[p7] then
        return u1[p7], u1[p7]
    end
	return nil, nil;
end
function UpdatePetDB() -- Line: 1104
	--[[
		Upvalues:
			[1] = m_Network
			[2] = u1
	--]]
	local v5 = m_Network.Invoke("Get Pet Rarity DB");
	if v5 then
		u1 = v5;
	end
end
local coroutine_wrap_ret9 = coroutine.wrap(function() -- Line: 1114
	--[[
		Upvalues:
			[1] = u1
	--]]
	while not u1 do
		UpdatePetDB();
		wait(1);
	end
	while true do
		task.wait(30);
		UpdatePetDB();
	end
end);
coroutine_wrap_ret9();
local u3 = 0;
game:GetService("RunService").RenderStepped:Connect(function(p8) -- Line: 1127
	--[[
		Upvalues:
			[1] = u3
			[2] = Color3_fromHSV_ret
			[3] = u2
	--]]
	u3 = u3 + p8;
	Color3_fromHSV_ret = Color3.fromHSV(u3 / 2 % 1, 1, 1);
	u2 = math.sin(u3 * 4) * 0.2 + 0.7;
end);
return table1;
