local settings = {
	Banks = {
		Default = true,
		Important = true
	},
	Trading = {
		Default = true,
		Important = true
	},
	TradingBooths = {
		Default = true
	},
	UpgradeMachine = {
		Default = true
	},
	GoldenMachine = {
		Default = true
	},
	RainbowMachine = {
		Default = true
	},
	DarkMatterMachine = {
		Default = true
	},
	BoostMachine = {
		Default = true
	},
	FuseMachine = {
		Default = true
	},
	HugeMachine = {
		Default = true
	},
	HardcoreJoining = {
		Default = true
	},
	TradingJoining = {
		Default = true
	},
	RankRewards = {
		Default = true
	},
	VIPRewards = {
		Default = true
	},
	EggOpening = {
		Default = true
	},
	ExclusiveEggs = {
		Default = true
	},
	Purchases = {
		Default = true,
		Important = true
	},
	CoinRewards = {
		Default = true
	},
	DiamondRewards = {
		Default = true
	},
	Lootbags = {
		Default = true
	},
	LuckyBlockRewards = {
		Default = true
	},
	Cannons = {
		Default = true
	},
	Gates = {
		Default = true
	},
	Merchants = {
		Default = true
	},
	Inventory = {
		Default = true
	},
	BankInterest = {
		Default = false
	},
	DistanceChecksEgg = {
		Default = true
	},
	DistanceChecksGate = {
		Default = true
	},
	DistanceChecksInteractable = {
		Default = true
	},
	DistanceChecksCannon = {
		Default = true
	},
	ChristmasSleigh = {
		Default = false
	},
	ChristmasSnowballs = {
		Default = false
	},
	Mailbox = {
		Default = true
	},
	MailboxRefunds = {
		Default = true
	},
	MailboxClaiming = {
		Default = true
	},
	MailboxReject = {
		Default = true
	},
	MailboxSending = {
		Default = true
	},
	MailboxHuges = {
		Default = true
	},
	MailboxTitanics = {
		Default = false
	},
	ChristmasRewards = {
		Default = false
	},
	MerchCodes = {
		Default = true
	},
	Teleporting = {
		Default = true
	},
	TitanicTransactions = {
		Default = true
	},
	BanksDepositTitanic = {
		Default = false
	},
	BanksDepositHuge = {
		Default = true
	},
	BanksDepositGift = {
		Default = true
	},
	BanksDepositDiamonds = {
		Default = true
	},
	AllowNonOwnerAccessBanks = {
		Default = true
	},
	DragDelete = {
		Default = true
	},
	BankDragDelete = {
		Default = true
	},
	InventoryDragDelete = {
		Default = true
	},
	UpdateGift = {
		Default = true
	},
	ExclusiveEggTimer = {
		Default = true
	},
	AllowBankOnNonProduction = {
		Default = false,
		Important = true
	},
	CoinsEvent = {
		Default = 0,
		Toggles = {0, 2, 3, 5, 10, 20, 30, 50},
		Min = 0,
		Max = 50
	},
	LuckEvent = {
		Default = 0,
		Toggles = {0, 2, 3, 5, 10, 20, 30, 50},
		Min = 0,
		Max = 50
	},
	DiamondsEvent = {
		Default = 0,
		Toggles = {0, 2, 3, 5, 10, 20, 30, 50},
		Min = 0,
		Max = 50
	},
	DominusGate = {
		Default = true
	},
	ScavengerClaim = {
		Default = true
	},
	CoolbeansPatch = {
		Default = true
	},
	Daycare = {
		Default = true
	},
	Auction = {
		Default = true
	},
	LazarBeam = {
		Default = true
	},
	DiamondParty = {
		Default = true
	},
	RAP = {
		Default = true
	},
	RAPAuction = {
		Default = true
	},
	CustomJoinFriends = {
		Default = true
	},
	ThanksForPlayingPet = {
		Default = true
	},
	MassiveCometSpawn = {
		Default = true
	},
	MiniCometSpawn = {
		Default = true
	},
	CometEggOpen = {
		Default = true
	},
	GiantRainbowEvent = {
		Default = true
	},
	HugeChefCatPromo = {
		Default = true
	},
	Limit100PetOnCoin = {
		Default = false
	},
	CoinBalancer = {
		Default = true
	},
	AprilPaintballs = {
		Default = true
	},
	InfinitePetPass = {
		Default = false
	},
	EasterEggHuntEvent = {
		Default = true
	},
	Fruit = {
		Default = true
	},
	DiamondBags = {
		Default = true
	},
	ReleasePet = {
		Default = true
	},
	RespawnAfterDeath = {
		Default = true
	},
	MiningSpeedMultiplier = {
		Default = 1
	},
	RojanAPI = {
		Default = true
	},
	Quests = {
		Default = true
	},
	QuestRewards = {
		Default = true
	},
	EvolveMachine = {
		Default = true
	},
	GlobalVote = {
		Default = "Do you like this game?"
	},
	GlobalVoteKey = {
		Default = "1"
	},
	ReturningPlayerPet = {
		Default = true
	},
	Voting = {
		Default = true
	},
	GroupHugeReward = {
		Default = true
	},
	VerifyTwitterLimiter = {
		Default = true
	},
	GlobalTitanicAnnouncements = {
		Default = true
	},
	BoothPublishInterval = {
		Default = 0
	},
	BoothLoadInterval = {
		Default = 0
	},
	BoothAnyPets = {
		Default = false
	},
	BloombergTerminal = {
		Default = true
	},
	BloombergScreenDataSubmission = {
		Default = true
	},
	BloombergScreenSound = {
		Default = true
	},
	BoothPublishForce = {
		Default = false
	},
	DisableBankNearUpdate = {
		Default = true
	},
	WaitForUpdateAlwaysFalse = {
		Default = false
	},
	SandcastleEvent = {
		Default = true
	},
	Events = {
		Default = true
	},
	EventRewards = {
		Default = true
	},
	WaterLauncher = {
		Default = true
	},
	SummerIslandsEvent = {
		Default = true
	},
	ButterflyBaseChance = {
		Default = 5e-07
	},
	RefundNightmare = {
		Default = true
	},
	VisitorGift = {
		Default = true
	},
	VisitorFix = {
		Default = true
	},
	ClawMachine = {
		Default = true
	},
	ClawMachineRewards = {
		Default = true
	},
	TitanicCatBaseChance = {
		Default = 3e-08
	},
	ClawHugeSpawnChance = {
		Default = 0.0001
	},
	Claw50xSpawnChance = {
		Default = 1
	},
	Claw20xSpawnChance = {
		Default = 5
	},
	Claw10xSpawnChance = {
		Default = 10
	},
	Claw1xHugeChance = {
		Default = 0.02
	},
	Claw5xHugeChance = {
		Default = 0.1
	},
	Claw10xHugeChance = {
		Default = 0.2
	},
	Claw20xHugeChance = {
		Default = 0.4
	},
	Claw50xHugeChance = {
		Default = 1
	},
	AnniversaryGiftChance = {
		Default = 0.3
	},
	YeetRewards = {
		Default = true
	},
	AntiAFK = {
		Default = true
	},
	FixHugeAppleCapybara = {
		Default = false
	},
	FixHugeAppleCapybaraNEW = {
		Default = true
	},
	["DiamondPurchasables"] = {
		Default = true;
		Important = true;
	};
}

return settings