--[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⣿⣿⣿⣷⣦⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣿⣿⣷⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⡿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⡇⠀⠀⢀⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⡇⠀⠀⢸⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⣿⣿⣿⣧⠀⠀⠘⣿⣿⣿⣷⣤⣀⣀⠀⠀⣀⣀⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⡄⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣷⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⡆⠀⠀⠀⠈⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠿⠀⠀⠀⠀⠀⠀⠈⠉⠛⠻⠿⠿⠿⠟⠛⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

	Velvet Groups rbx.lua Framework [2025] - [2025]
	Written by kalidrios - 1037898275229020250
	Developed with a VScode and Rojo.
	
	-+-+-+- SPECIFICS -+-+-+-
	_L.Audio
	===========
	Play SFX and Music through a single module. Pretty basic stuff.
	You can cross-fade music tracks or edit all sound entities without using soundgroups - useful for lots of rapid fire sounds that
	would normally cause sound tearing. Bundled with tons of little random QOL features. Built-in garbage collection, too :D
	===========
		\\\ Play SFX
		Audio.Play(
			id / ids,				<-- |REQ|	Sound ID Supports link or just ID. (also supports array of IDs. Will pick one by random)
			parent / position,		<-- |REQ|	Sound parent or position (cf/v3)
			pitch,					<--			Sound pitch 										[defaults to: 1]
			volume,					<-- 		Sound volume										[defaults to: 0.5]
			max distance,			<-- 		Sound max distance in studs 						[defaults to: 100]
			sound group,			<-- 		Sound group											[defaults to: nil]
			looped,					<-- 		Sound looped 										[defaults to: false]
			start time				<-- 		Sound start time in seconds 						[defaults to: 0]
		)
		
		\\\ Play background music or ambience. Will automatically crossfade with any song that is already playing.
		Audio.PlayMusic(
			id,						<-- |REQ|	Music ID (without link)
			volume,					<-- 		Music volume										[defaults to: 1]
			speed,					<-- 		Crossfade speed in seconds							[defaults to: 1]
			sound group,			<-- 		Sound group											[defaults to: nil]
			looped,					<-- 		Music looped 										[defaults to: true]
			start time				<-- 		Music start time in seconds 						[defaults to: 0]
		)
		
		\\\ Stops any song that is currently playing.
		Audio.StopMusic(
			speed,					<-- 		Crossfade speed in seconds							[defaults to: 1]
		) 
	===========
--]]
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- | load library | --
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Library = ReplicatedStorage:WaitForChild("Library")
local ClientLibrary = Library:WaitForChild("Client")
local Modules = Library:WaitForChild("Modules")
local Types = Library:WaitForChild("Types")

-- | shared modules | --
local Functions = require(Library.Functions)
local Settings = require(ClientLibrary.Settings)
local Network = require(ClientLibrary.Network)
local Debug = require(ClientLibrary.Debug)

--------|       Top       |--------
local Audio = {}
--------|     Setting     |--------

--------|    Reference    |--------
local debris = game.Workspace.__DEBRIS
local musicFolder = Instance.new("Folder", script)
local rng = Random.new()
local RunService = game:GetService("RunService")

--------|    Variables    |--------
local garbage = {}
local isClient = RunService:IsClient()

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function Audio.Play(...) 
	--- If server, tell clients to play sound (to keep a secular soundscape)
	if not isClient then
		local Network = require(game:GetService("ServerScriptService"):WaitForChild("Library").Network)
		local args = {...}
		coroutine.wrap(function()
			network.FireAll("PlaySound", unpack(args))
		end)()
		return
	end
	
	--- Unpack
	local id, parent, pitch, volume, maxDistance, soundGroup, looped, startTime = unpack({...})
	
	--- Array of IDs support
	if type(id) == "table" then
		id = id[rng:NextInteger(1, #id)]
	end
	
	if pitch and type(pitch) == "table" then
		pitch = rng:NextNumber(unpack(pitch))
	end
	
	if volume and type(volume) == "table" then
		volume = rng:NextNumber(unpack(volume))
	end
	
	--- Sanity checks
	if not parent then
		--- Abort! Parent doesn't exist.
		warn("Parent cannot be nil", debug.traceback())
		return nil
	elseif id == 0 then
		--- Sound ID is 0 (removed error because console spamming issues)
		return nil
	end
	
	--- Missing link
	if type(id) == "number" or not string.find(id, "rbxassetid://", 1, true) then
		id = "rbxassetid://" .. id
	end
	
	--- Variables
	pitch = (pitch or 1)
	volume = (volume or 0.5)
	soundGroup = soundGroup and game.SoundService:FindFirstChild(soundGroup) or nil
	looped = (looped or false)
	maxDistance = (maxDistance or 100)
	startTime = (startTime == nil and 0 or startTime)
	--
	local rollOffMode = Enum.RollOffMode.Linear
	local name = "sound-" .. id
	local parentWasGenerated = false
	
	--- If parent is Vector3/CFrame - create sound part!
	if not pcall(function()  local x = parent.Parent  end) then
		local position = parent
		
		--- If Vector3, convert to CFrame
		pcall(function() 
			position = CFrame.new(position)
		end)
		
		--- Create host part for sound
		parent = Instance.new("Part")
		parent.Anchored = true
		parent.CanCollide = false
		parent.CFrame = position
		parent.Size = Vector3.new()
		parent.Transparency = 1
		parent.Parent = debris
		
		--- Flag parent for garbage collection
		parentWasGenerated = true
	end
	
	--- Create
	local sound = Instance.new("Sound")
	sound.SoundId = id
	sound.Name = name
	sound.Pitch = pitch
	sound.Volume = volume
	sound.SoundGroup = soundGroup
	sound.Looped = looped
	sound.MaxDistance = maxDistance
	sound.TimePosition = startTime
	sound.RollOffMode = rollOffMode
	sound.Parent = parent
	
	--- Muted?
	if not Settings.SoundsEnabled then
		sound:SetAttribute("CachedVolume", sound.Volume)
		sound.Volume = 0
	end
	
	--- Play sound
	sound:Play()
	
	--- Add to garbage collection
	AddToGarbageCollection(sound, parentWasGenerated)
	
	--
	return sound
end


function Audio.PlayMusic(id, volume, speed, soundGroup, looped, startTime) 
	--- Disable being called on server (compatibility reasons)
	if not isClient then
		warn("Cannot use this on the server!")
		return
	end
	
	--- Sanity checks
	if not Settings.MusicEnabled then
		--- Abort! Sounds are disabled in settings.
		warn("Music is disabled in settings module!")
		return
	elseif id == 0 then
		--- Sound ID is 0
		return 
	end
	
	--- Has link
	if type(id) == "number" or not string.find(id, "rbxassetid://", 1, true) then
		id = "rbxassetid://" .. id
	end
	
	--- Variables
	volume = (volume or 0.5)
	speed = (speed or 1)
	soundGroup = soundGroup and game.SoundService:FindFirstChild(soundGroup) or nil
	looped = (looped == nil and true or looped)
	startTime = (startTime == nil and 0 or startTime)
	--
	local name = "music-" .. id
	
	--- Create
	local music = Instance.new("Sound")
	music.SoundId = id
	music.Volume = 0
	music.Looped = looped
	music.SoundGroup = soundGroup
	music.Parent = musicFolder
	music:Play()
	
	--- Fade function
	local function Fade(song, newVolume) 
		Functions.Tween(song, {Volume = newVolume}, {speed})
	end
	
	--- Fade out
	for _, song in ipairs(musicFolder:GetChildren()) do
		Fade(song, 0)
	end
	
	--- Fade in
	Fade(music, volume)
	
	--
	AddToGarbageCollection(music)
	--
	return music
end


function Audio.StopMusic(speed) 
	--- Disable being called on server (compatibility reasons)
	if not isClient then
		warn("Cannot use this on the server!")
		return
	end
	
	--- Variables
	speed = (speed or 1)
	
	--- Fade function
	local function Fade(p12, p13) 
		Functions.Tween(p12, {Volume = p13}, {speed})
	end
	
	--- Stop current music
	for _, song in ipairs(musicFolder:GetChildren()) do
		Fade(song, 0)
	end
end


------------------------------------------------------------------------------------------------------------------------


--- Pile onto garbage collection
function AddToGarbageCollection(sound, parentWasGenerated)
	--- Add to garbage collection
	table.insert(garbage, {sound, parentWasGenerated or false})
end


--- Scan garbage collection for GARBAGE
function ScanGarbageCollection() 
	for i = #garbage, 1, -1 do
		if i%25 == 0 then
			RunService.Heartbeat:Wait()
		end
		
		--- Variables
		local garbageArray = garbage[i]
		local garbageItem = garbageArray[1]
		local garbageParentWasGenerated = garbageArray[2]
		local due = false
		
		--- Sanity check
		if not due then
			if (not garbageItem) or (not garbageItem.Parent) then
				due = true
			end
		end
		
		--- Stopped check #1
		if not due then
			local playing = garbageItem.Playing
			if not playing then
				due = true
			end
		end
		
		--- Empty sound check
		if not due then
			local soundId = garbageItem.SoundId
			if soundId == "" then
				due = true
			end
		end
		
		--- Remove if due
		if due then
			if garbageParentWasGenerated then
				if garbageItem.Parent then
					Functions.AddDebris(garbageItem.Parent, 0)
				end
			elseif garbageItem then
				Functions.AddDebris(garbageItem, 0)
			end
			table.remove(garbage, i)
		end
	end
	
	--- Debug
	if isClient then
		Debug.Track("Garbage #", "Audio", #garbage)
	end
end
coroutine.wrap(function()
	if isClient then
		while true do
			--- Wait
			wait(1)
			
			--- Scan garbage
			ScanGarbageCollection()
			
			--- Music debug
			local musicPlaying = false
			for _, music in ipairs(musicFolder:GetChildren()) do
				musicPlaying = true
				break
			end
			Debug.Track("Music Playing", "Audio", musicPlaying)
		end
	end
end)()


--- Disabled sounds
if isClient then
	coroutine.wrap(function() 
		local Settings = Settings
		local last = Settings.SoundsEnabled
		while wait() do
			if last ~= Settings.SoundsEnabled then
				last = Settings.SoundsEnabled
				
				--- Scan all active sounds
				for i, v in pairs(garbage) do
					local sound = v[1]
					if sound and sound.Parent ~= musicFolder then
						if not last then
							--- Mute sound and cache volume
							sound:SetAttribute("CachedVolume", sound.Volume)
							sound.Volume = 0
						elseif sound:GetAttribute("CachedVolume") then
							sound.Volume = sound:GetAttribute("CachedVolume")
							sound:SetAttribute("CachedVolume", nil)
						end	
					end
				end	
			end
		end
	end)()
end


--- Recieve sounds from server
if isClient then
	Network.Fired("PlaySound"):Connect(function(...) 
		Audio.Play(...)
	end)
end


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

return Audio