-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Spend = {
		Amount = 500000000000, 
		Tier = "Easy", 
		Description = "Spend {Amount.Short} Cartoon Coins in the Dojo!"
	}, 
	Coins = {
		Amount = 500, 
		Tier = "Medium", 
		Coin = {
			Pattern = "Giant Kawaii Dojo Chest"
		}
	}, 
	Eggs = {
		Amount = 1, 
		Tier = "Hard", 
		Description = "Hatch {Amount} Shiny Secret Pet from Dojo Egg!", 
		Egg = {
			Pattern = "Dojo Egg", 
			Rarity = "Secret", 
			Attributes = {
				sh = true
			}
		}
	}
};
