-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Eggs = {
		Amount = 15000, 
		Tier = "Easy", 
		Description = "Hatch {Amount} Pets from the Kawaii Eggs!", 
		Egg = {
			Pattern = "Kawaii Egg"
		}
	}, 
	Coins = {
		Amount = 500, 
		Tier = "Medium", 
		Coin = {
			Pattern = "Kawaii Alley Chest"
		}
	}, 
	Eggs2 = {
		Amount = 50000, 
		Tier = "Hard", 
		Egg = {
			Pattern = "Tokyo Alley"
		}
	}
};
