-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Coins = {
		Amount = 250, 
		Tier = "Easy", 
		Description = "Break {Amount} Giant Kawaii Chests!", 
		Coin = {
			Pattern = "Giant Kawaii Chest"
		}
	}, 
	Collect = {
		Amount = 5000000000000, 
		Tier = "Medium", 
		Description = "Collect {Amount.Short} Cartoon Coins!"
	}, 
	DarkMatter = {
		Amount = 5, 
		Tier = "Hard", 
		Description = "Dark Matter 5 Masked Owl Pets!"
	}
};
