--[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⣿⣿⣿⣷⣦⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣿⣿⣷⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⡿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⡇⠀⠀⢀⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⡇⠀⠀⢸⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⣿⣿⣿⣧⠀⠀⠘⣿⣿⣿⣷⣤⣀⣀⠀⠀⣀⣀⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⡄⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣷⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⡆⠀⠀⠀⠈⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠿⠀⠀⠀⠀⠀⠀⠈⠉⠛⠻⠿⠿⠿⠟⠛⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

	Velvet Groups rbx.lua Framework [2025] - [2025]
	Written by kalidrios - 1037898275229020250
	Developed with a VScode and Rojo.
	
	-+-+-+- SPECIFICS -+-+-+-
	_L.Functions
	===========
	And in-house library of helpful functions and QOL stuff like FastTween, GetProductInfo, Commas - down to things that aren't already
	implemented natively by Roblox like ScaleModel. The functions individually can be found as children under this module.
	===========
--]]
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- | load library | --
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Library = ReplicatedStorage:WaitForChild("Library")
local ClientLibrary = Library:WaitForChild("Client")
local Modules = Library:WaitForChild("Modules")
local Types = Library:WaitForChild("Types")

-- | shared modules | --

--------|       Top       |--------
local Functions = {
	FormatTime = require(script.FormatTime), 
	Animation = require(script.Animation), 
	Base64 = require(script.Base64), 
	Clicked = require(script.Clicked), 
	CloneTable = require(script.CloneTable), 
	Commas = require(script.Commas), 
	CompareTable = require(script.CompareTable), 
	Compress = require(script.Compress), 
	CreateParticleHost = require(script.CreateParticleHost), 
	DictionaryLength = require(script.DictionaryLength), 
	DrawRaycast = require(script.DrawRaycast), 
	Easing = require(script.Easing), 
	Tween = require(script.Tween), 
	FindFirstChildCustom = require(script.FindFirstChildCustom), 
	GenerateCustomUUID = require(script.GenerateCustomUUID), 
	GetGamepassInfo = require(script.GetGamepassInfo), 
	GetPrice = require(script.GetPrice), 
	GetProductInfo = require(script.GetProductInfo), 
	GetTouchingParts = require(script.GetTouchingParts), 
	HasUserdata = require(script.HasUserdata), 
	IsArray = require(script.IsArray), 
	Lottery = require(script.Lottery), 
	NumberShorten = require(script.NumberShorten), 
	PlayerDist = require(script.PlayerDist), 
	QuickValue = require(script.QuickValue), 
	RandomizeTable = require(script.RandomizeTable), 
	ResolutionScale = require(script.ResolutionScale), 
	Weld = require(script.Weld), 
	ScaleModel = require(script.ScaleModel), 
	ScaleParticle = require(script.ScaleParticle), 
	SearchArray = require(script.SearchArray), 
	SearchDictionary = require(script.SearchDictionary), 
	SolveIK = require(script.SolveIK), 
	StringByte = require(script.StringByte), 
	TextStyles = require(script.TextStyles), 
	TimeString = require(script.TimeString), 
	UserIdToUsername = require(script.UserIdToUsername), 
	Wait = require(script.Wait), 
	RemoveTable = require(script.RemoveTable), 
	ToRomanNum = require(script.ToRomanNum), 
	PatchTable = require(script.PatchTable), 
	GetFriends = require(script.GetFriends), 
	TimerString = require(script.TimerString), 
	FormatChance = require(script.FormatChance), 
	FormatAbbreviated = require(script.FormatAbbreviated), 
	IsNaN = require(script.IsNaN), 
	FormatPercent = require(script.FormatPercent), 
	FormatOdds = require(script.FormatOdds), 
	IsInf = require(script.IsInf), 
	IsFinite = require(script.IsFinite), 
	Lerp = require(script.Lerp), 
	DegNorm = require(script.DegNorm), 
	RadNorm = require(script.RadNorm), 
	DegDeltaUnsafeVec = require(script.DegDeltaUnsafeVec), 
	DegDeltaUnsafe = require(script.DegDeltaUnsafe), 
	RadDelta = require(script.RadDelta), 
	RadDeltaUnsafe = require(script.RadDeltaUnsafe), 
	Sigmoid = require(script.Sigmoid), 
	GetUserId = require(script.GetUserId), 
	RemoveIf = require(script.RemoveIf), 
	CumulativeProbability = require(script.CumulativeProbability), 
	ContainsAABBPoint = require(script.ContainsAABBPoint), 
	RegexEscape = require(script.RegexEscape), 
	VecMin = require(script.VecMin), 
	LotteryStruct = require(script.LotteryStruct), 
	Erfc = require(script.Erfc), 
	KeepIf = require(script.KeepIf), 
	Erf = require(script.Erf), 
	AutoUIScaling = require(script.AutoUIScaling), 
	AddDebris = require(script.AddDebris), 
	DistAABBPoint = require(script.DistAABBPoint), 
	DeepCopy = require(script.DeepCopy), 
	FormatTimeShort = require(script.FormatTimeShort), 
	DeepEquals = require(script.DeepEquals), 
	AngleOfReach = require(script.AngleOfReach), 
	GetNextUpdateTime = require(script.GetNextUpdateTime), 
	AbsDifferenceFromNextUpdateTime = require(script.AbsDifferenceFromNextUpdateTime), 
	VerifyPlayerMagnitude = require(script.VerifyPlayerMagnitude), 
	GenerateUID = require(script.GenerateUID), 
	LotteryCustom = require(script.LotteryCustom), 
	FireInterval = require(script.FireInterval), 
	ErfInv = require(script.ErfInv), 
	ScaleNumberSequence = require(script.ScaleNumberSequence), 
	ParseNumberSmart = require(script.ParseNumberSmart), 
	IsEmpty = require(script.IsEmpty), 
	FireAt = require(script.FireAt), 
	RadDeltaVec = require(script.RadDeltaVec), 
	RadDeltaUnsafeVec = require(script.RadDeltaUnsafeVec), 
	DegDeltaVec = require(script.DegDeltaVec), 
	DegDelta = require(script.DegDelta), 
	VecMax = require(script.VecMax), 
	IsASCII = require(script.IsASCII), 
	CheckRectangleIntersection = require(script.CheckRectangleIntersection), 
	IsGuiClipped = require(script.IsGuiClipped), 
	BuildQueryString = require(script.BuildQueryString), 
	BuildSortedQueryString = require(script.BuildSortedQueryString), 
	DeepCopyUnsafe = require(script.DeepCopyUnsafe), 
	DeepEqualsUnsafe = require(script.DeepEqualsUnsafe), 
	ShallowEqualsUnsafe = require(script.ShallowEqualsUnsafe), 
	DistOBBPoint = require(script.DistOBBPoint), 
	ComputeAABBCustom = require(script.ComputeAABBCustom), 
	ComputeAABBModel = require(script.ComputeAABBModel), 
	VecToColor = require(script.VecToColor), 
	VecToColorClamped = require(script.VecToColorClamped), 
	ColorToVec = require(script.ColorToVec), 
	EvalColorSequence = require(script.EvalColorSequence), 
	EvalSequence = require(script.EvalSequence), 
	AsColorSequence = require(script.AsColorSequence), 
	IsFiniteCFrame = require(script.IsFiniteCFrame), 
	IsFiniteVec = require(script.IsFiniteVec), 
	IsFiniteVec2 = require(script.IsFiniteVec2), 
	RenderStepped = require(script.RenderStepped), 
	Scaler = require(script.Scaler), 
	Comb = require(script.Comb), 
	Factorial = require(script.Factorial), 
	Bezier = require(script.Bezier), 
	Emit = require(script.Emit), 
	Transparency = require(script.Transparency), 
	GetCurrentDay = require(script.GetCurrentDay), 
	GetCurrentMonth = require(script.GetCurrentMonth), 
	Bezier2 = require(script.Bezier2), 
	Map = require(script.Map), 
	Map2 = require(script.Map2), 
	Map3 = require(script.Map3), 
	PlaceInsideRect = require(script.PlaceInsideRect), 
	Gauss = require(script.Gauss), 
	PolyVal = require(script.PolyVal), 
	PolyFit = require(script.PolyFit), 
	PolyVal2 = require(script.PolyVal2), 
	PolyFit2 = require(script.PolyFit2), 
	PolyVal3 = require(script.PolyVal3), 
	PolyFit3 = require(script.PolyFit3), 
	SplineFit = require(script.SplineFit), 
	ExpFit = require(script.ExpFit), 
	LotteryCurve = require(script.LotteryCurve), 
	wcall = require(script.wcall), 
	tcall = require(script.tcall), 
	twcall = require(script.twcall), 
	Tasks = require(script.Tasks), 
	UnpackColor = require(script.UnpackColor), 
	PackColor = require(script.PackColor), 
	GlobalSpawner = require(script.GlobalSpawner), 
	Shuffle = require(script.Shuffle), 
	GetNextScavengerTime = require(script.GetNextScavengerTime), 
	GetNextScavengerSeed = require(script.GetNextScavengerSeed), 
	ObjectDebounce = require(script.ObjectDebounce), 
	Debounce = require(script.Debounce), 
	LevDist = require(script.LevDist), 
	GetNameFromUserIdAsync = require(script.GetNameFromUserIdAsync), 
	GetDateTable = require(script.GetDateTable), 
	AddOrdinalSuffix = require(script.AddOrdinalSuffix), 
	FormatDate = require(script.FormatDate), 
	ColorDist = require(script.ColorDist), 
	Recolor = require(script.Recolor), 
	ParseAssetId = require(script.ParseAssetId), 
	PreloadAssets = require(script.PreloadAssets), 
	PreloadSounds = require(script.PreloadSounds), 
	SphereCast = require(script.SphereCast), 
	Tracker = require(script.Tracker), 
	ReverseArray = require(script.ReverseArray), 
	Heartbeat = require(script.Heartbeat), 
	Leaderstat = require(script.Leaderstat), 
	ToHSL = require(script.ToHSL), 
	FromHSL = require(script.FromHSL), 
	HSLToHSV = require(script.HSLToHSV), 
	HSVToHSL = require(script.HSVToHSL), 
	InverseLerp = require(script.InverseLerp), 
	RobloxSaturation = require(script.RobloxSaturation), 
	InverseRobloxSaturation = require(script.InverseRobloxSaturation), 
	CompareColor = require(script.CompareColor), 
	Grayscale = require(script.Grayscale), 
	CorrectColor = require(script.CorrectColor), 
	ClampColor = require(script.ClampColor),
	FaceSize = require(script.FaceSize),
}

--------|     Setting     |--------

--------|    Reference    |--------

--------|    Variables    |--------
local unaddedEntries = ""

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

for _, module in ipairs(script:GetChildren()) do
	if module:IsA("ModuleScript") and Functions[module.Name] == nil then
		unaddedEntries = unaddedEntries .. string.format("%s = require(script.%s),\n", module.Name, module.Name)
	end	
end

if #unaddedEntries > 0 then
	warn(string.format("Unadded entries: \n\n%s\n", unaddedEntries))
end

for index, v in pairs(Functions) do
	if not script:FindFirstChild(index) then
		warn(string.format("Unknown entry: %s", tostring(index)))
	end	
end

for _, module in ipairs(script:GetChildren()) do
	if module:IsA("ModuleScript") and Functions[module.Name] == nil then
		Functions[module.Name] = require(module)
	end	
end


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

return Functions
