--[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⣿⣿⣿⣷⣦⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣿⣿⣷⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⡿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⡇⠀⠀⢀⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⡇⠀⠀⢸⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⣿⣿⣿⣧⠀⠀⠘⣿⣿⣿⣷⣤⣀⣀⠀⠀⣀⣀⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⡄⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣷⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⡆⠀⠀⠀⠈⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠿⠀⠀⠀⠀⠀⠀⠈⠉⠛⠻⠿⠿⠿⠟⠛⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
	Velvet Groups rbx.lua Framework [2025] - [2025]
	Written by kalidrios - 1037898275229020250
	Developed with a VScode and Rojo.
	
	-+-+-+- SPECIFICS -+-+-+-
	_L.Network
	===========
	Handles all the networking from client to server. Automatically compresses strings and tables to save bandwidth (theoretical)
	Makes networking completely automatic and somehow also makes the syntax simplier. No fiddling with remotes required. B)
	
	Event example:
		CLIENT:
		_L.Network.Fire("Bullet Fired", bullet.CFrame, bullet, {speed = 33, damage = 423})
		
		SERVER:
		_L.Network.Fired("Bullet Fired"):Connect(function(player, ...)
			FireBullet(player, ...)
		end)
	
	Function example:
		CLIENT:
		local success = _L.Network.Invoke("Buy", "Super Soaker 5000", 2455)
		
		SERVER:
		_L.Network.Invoked("Buy").OnInvoke = function(player, itemName, price)
			return (price <= 3000)
		end
		
	===========
		\\\ Subsititute for RemoteEvent:FireServer() / RemoteEvent:FireClient()
		Network.Fire(
			remoteName,				<--	|REQ|	Remote name											
			player,					<-- |REQ|	Player instance	(SERVER ONLY)								
			...,					<-- 		Anything :)							
		)
	
		\\\ Subsititute for RemoteFunction:InvokeClient() / RemoteFunction:InvokeServer()
		Network.Invoke(
			remoteName,				<--	|REQ|	Remote name											
			player,					<-- |REQ|	Player instance	(SERVER ONLY)								
			...,					<-- 		Anything :)							
		)

		\\\ Subsititute for RemoteEvent.OnClientEvent / RemoteEvent.OnServerEvent
		Network.Fired(
			remoteName,				<--	|REQ|	Remote name			
		)
		
		\\\ Subsititute for RemoteFunction.OnClientInvoke / RemoteFunction.OnServerInvoke
		Network.Invoked.OnInvoke(
			remoteName,				<--	|REQ|	Remote name			
		)
		
		\\\ Subsititute for RemoteEvent:FireAllClients()
		Network.FireAll(
			remoteName,				<--	|REQ|	Remote name																		
			...,					<-- 		Anything :)							
		)
--]]
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- | load library | --
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Library = ReplicatedStorage:WaitForChild("Library")

-- | shared modules | --
local Signal = require(Library.Signal)

--------|       Top       |--------
local Network = {}

--------|     Setting     |--------
local Debug = false -- track 

--------|    Reference    |--------
local isServer = game:GetService("RunService"):IsServer()
local things = workspace:WaitForChild("__THINGS")
local remotes = things:WaitForChild("__REMOTES")
local mainRemote = remotes:WaitForChild("MAIN")

--------|    Variables    |--------
local queue = {}
local lastQueue = tick()
local events = {}
local listening = {}

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--- Fire
Network.Fire = function(remoteName, arg, ...)
	--- Variables
	remoteName = string.lower(remoteName)

	--- Get/create remote
	local remote = GetRemote(remoteName)

	--- Signal for visualization/tracking purposes on Debug (Client only)
	if not isServer then
		Signal.Fire("CORE Network Fire", remoteName)
	end
	
	-- dssd
	if Debug then
		warn("Network Debug .Fire | " .. remoteName)
	end

	--- Create packet with arguments
	if isServer then
		--- Server
		local packet = CreatePacket(...)
		local player = arg

		--- Check if player is past intro
		if not player:FindFirstChild("__LOADED") then
			return
		end

		--- Send
		remote:FireClient(player, packet)

	else
		--- Client
		local packet = CreatePacket(arg, ...)

		--- Send
		remote:FireServer(packet)
	end
end

--- Fire (everyone)
Network.FireAll = function(remoteName, ...)
	--- Variables
	remoteName = string.lower(remoteName)
	
	--- Get/create remote
	local remote = GetRemote(remoteName)
	
	-- dssd
	if Debug then
		warn("Network Debug .FireAll | " .. remoteName)
	end

	--- Create packet with arguments
	local packet = CreatePacket(...)

	--- Get a list of players loaded past intro (that we can fire event on)
	local players = game.Players:GetPlayers()
	local playersToSend = {}
	--
	for _, player in ipairs(players) do
		if player:FindFirstChild("__LOADED") then
			table.insert(playersToSend, player)
		end
	end

	--- Send
	if #playersToSend >= #players then
		--- Can use optimized FireAllClients
		remote:FireAllClients(packet)

	else
		--- Some players are in intro, so we gotta fire each manually
		for _, player in ipairs(playersToSend) do
			coroutine.wrap(function()
				remote:FireClient(player, packet)
			end)()
		end
	end
end

--- Invoke
Network.Invoke = function(remoteName, arg, ...)
	--- Variables
	remoteName = string.lower(remoteName)
	
	
	--- Get/create remote
	local remote = GetRemote(remoteName, true)
	
	-- dssd
	if Debug then
		warn("Network Debug .Invoke | " .. remoteName)
	end
	
	--- Signal for visualization/tracking purposes on Debug (Client only)
	if not isServer then
		Signal.Fire("CORE Network Invoke", remoteName)
	end

	--- Create packet with arguments
	if isServer then
		--- Server
		local packet = CreatePacket(...)
		local player = arg

		--- Check if player is past intro
		if not player:FindFirstChild("__LOADED") then
			return
		end

		--- Return decoded packet
		return DecodePacket(remote:InvokeClient(arg, packet))

	else
		--- Client
		local packet = CreatePacket(arg, ...)

		--- Return decoded packet
		return DecodePacket(remote:InvokeServer(packet))
	end
end


--- On Fire
Network.Fired = function(remoteName)
	--- Variables
	remoteName = string.lower(remoteName)

	--- Get/create bindableEvent
	local event = GetEvent(remoteName)
	
	-- dssd
	if Debug then
		warn("Network Debug .Fired | " .. remoteName)
	end
	
	--
	return event.Event
end


--- On Invoke
Network.Invoked = function(remoteName)
	--- Variables
	remoteName = string.lower(remoteName)

	--- Get/create bindableFunction
	local event = GetEvent(remoteName, true)
	
	-- dssd
	if Debug then
		warn("Network Debug .Invoked | " .. remoteName)
	end
	
	--
	return event
end

--- Packet recieved from server/client
Network.Recieve = function(packetType, ...)
	--- Variables
	local data = {...}

	--- Direct packet info based on packetType
	if packetType == "a" then
		--- SERVER | Create remote event
		GetRemote(unpack(data))

	elseif packetType == "b" then
		--- SERVER | Create remote function
		GetRemote(unpack(data), true)

	elseif packetType == "c" then
		--- CLIENT | Recieved event
		local remoteName, packet = unpack(data)
		local event = GetEvent(remoteName)
		event:Fire(DecodePacket(packet))

	elseif packetType == "d" then
		--- CLIENT | Recieved invoke
		local remoteName, packet = unpack(data)
		local event = GetEvent(remoteName, true)
		return CreatePacket(event:Invoke(DecodePacket(packet)))

	elseif packetType == "e" then
		--- SERVER | Recieved event
		local remoteName, player, packet = unpack(data)
		local event = GetEvent(remoteName)
		event:Fire(player, DecodePacket(packet))

	elseif packetType == "f" then
		--- SERVER | Recieved invoke
		local remoteName, player, packet = unpack(data)
		local event = GetEvent(remoteName, true)
		return CreatePacket(event:Invoke(player, DecodePacket(packet)))

	else
		--- packetType returned doesn't exist :(
		warn("_L.Network.Recieve | Corrupted packet (packet type recieved as " .. packetType .. ")")
	end
end


----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--- Turn series of arguments into compressed 'packet'
function CreatePacket(...)
	local newPacket = { {}, {} }
	local newPacketData = newPacket[1]
	local newPacketIndex = newPacket[2]
	
	return { ... }
end


--- Decode previously encoded packet into a series of readable arguments
function DecodePacket(packet)
	--- Variables
	local newData = {}
	
	return unpack(packet)
end


--- Get (or create) BindableEvent / BindableFunction
function GetEvent(remoteName, isRemoteFunction)
	--- Variables
	remoteName = string.lower(remoteName)
	local event = events[remoteName]

	--- Check if event already exists
	if not event then
		--- Create event
		event = Instance.new(isRemoteFunction and "BindableFunction" or "BindableEvent")
		event.Name = string.reverse(remoteName)
		event.Parent = script
		events[remoteName] = event
	end

	--
	return event
end


--- Get (or create) RemtoeEvent / RemoteFunction
function GetRemote(remoteName, isRemoteFunction)
	--- Variables
	remoteName = string.lower(remoteName)
	local remote = remotes:FindFirstChild(remoteName)

	--- Check if remote already exists
	if not remote then
		if isServer then
			--- Server -> create remote
			remote = Instance.new(isRemoteFunction and "RemoteFunction" or "RemoteEvent")
			remote.Name = remoteName
			remote.Parent = remotes

			--- Track remote traffic
			ListenRemote(remoteName, isRemoteFunction)
		else
			--- Client -> Tell server to create remote
			mainRemote:FireServer((isRemoteFunction and "b" or "a"), remoteName)

			--- Wait for remote to exist
			repeat game:GetService("RunService").RenderStepped:Wait() until remotes:FindFirstChild(remoteName)
			remote = remotes:FindFirstChild(remoteName)

			--- Track remote traffic
			ListenRemote(remoteName, isRemoteFunction)
		end
	end

	return remote
end


--- Listen for data from remotes
function ListenRemote(remoteName, isRemoteFunction)
	--- Variables
	remoteName = string.lower(remoteName)
	local remote = GetRemote(remoteName, isRemoteFunction)

	--- Check if remote is already being tracked
	if not listening[remoteName] then
		listening[remoteName] = true
	else
		return
	end

	--- Listen to remote
	if isServer then
		--- Server
		if isRemoteFunction then
			--- Remote function
			function remote.OnServerInvoke(player, ...)
				return Network.Recieve("f", remoteName, player, ...)
			end

		else
			--- Remote event
			remote.OnServerEvent:Connect(function(player, ...)
				Network.Recieve("e", remoteName, player, ...)
			end)
		end

	else
		--- Client
		if isRemoteFunction then
			--- Remote function
			function remote.OnClientInvoke(...)
				--- Signal for visualization/tracking purposes on Debug (Client only)
				if not isServer then
					Signal.Fire("CORE Network Invoked", remoteName)
				end

				--
				return Network.Recieve("d", remoteName, ...)
			end

		else
			--- Remote event
			remote.OnClientEvent:Connect(function(...)
				--- Signal for visualization/tracking purposes on Debug (Client only)
				if not isServer then
					Signal.Fire("CORE Network Fired", remoteName)
				end

				--
				Network.Recieve("c", remoteName, ...)
			end)
		end
	end
end


--- Initailize client
function ClientInit()
	--- Scan all remotes
	for _, remote in ipairs(remotes:GetChildren()) do
		if remote.Name ~= "MAIN" then
			--- Listen for traffic
			ListenRemote(remote.Name, remote:IsA("RemoteFunction"))
		end
	end
end


--- First time
if isServer then
	--- If server, listen for any traffic from MAIN remote
	mainRemote.OnServerEvent:Connect(function(player, packetType, remoteName, ...)
		Network.Recieve(packetType, remoteName, ...)
	end)

else
	--- If client, initailize
	coroutine.wrap(function()
		wait()
		ClientInit()
	end)()
end


--- Listen in on newly added remotes
remotes.ChildAdded:Connect(function(remote)
	if remote:IsA("RemoteEvent") or remote:IsA("RemoteFunction") then
		ListenRemote(remote.Name, remote:IsA("RemoteFunction"))
	end
end)


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

return Network