--[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⣿⣿⣿⣷⣦⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣿⣿⣷⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⡿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⡇⠀⠀⢀⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⡇⠀⠀⢸⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⣿⣿⣿⣧⠀⠀⠘⣿⣿⣿⣷⣤⣀⣀⠀⠀⣀⣀⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⡄⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣷⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⡆⠀⠀⠀⠈⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠿⠀⠀⠀⠀⠀⠀⠈⠉⠛⠻⠿⠿⠿⠟⠛⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀        

	Velvet Groups rbx.lua Framework [2025] - [2025]
	Written by kalidrios - 1037898275229020250
	Developed with a VScode and Rojo.
	
	-+-+-+- SPECIFICS -+-+-+-
	_L.Signal
	===========
		
	===========
	
--]]
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

local Debug = false

local u1 = {};
local ReplicatedStorage = game:GetService("ReplicatedStorage");
local IsStudio_ret = game:GetService("RunService"):IsStudio();
local IsServer_ret = game:GetService("RunService"):IsServer();
local function _check(_) -- Line: 206
	return true;
end
local function _getName(p1, p2) -- Line: 214
	assert(typeof(p1) == "number");
	assert(typeof(p2) == "string");
	return p2:lower();
end
local table1 = {
	{},
	{}
};
local table2 = {
	"BindableEvent",
	"BindableFunction"
};
local function _get(p3, p4) -- Line: 225
	--[[
		Upvalues:
			[1] = table1
			[2] = table2
	--]]
	local v1 = table1[p3];
	local v2 = v1[p4];
	if not v2 then
		v2 = Instance.new(table2[p3]);
		v2.Parent = script;
		v1[p4] = v2;
	end
	return v2;
end
local function _event(p5) -- Line: 245
	--[[
		Upvalues:
			[1] = table1
			[2] = table2
	--]]
	assert(true);
	assert(typeof(p5) == "string");
	local lower_ret = p5:lower();
	local v3 = table1[1];
	local v4 = v3[lower_ret];
	if not v4 then
		v4 = Instance.new(table2[1]);
		v4.Parent = script;
		v3[lower_ret] = v4;
	end
	return v4;
end
local function _function(p6) -- Line: 246
	--[[
		Upvalues:
			[1] = table1
			[2] = table2
	--]]
	assert(true);
	assert(typeof(p6) == "string");
	local lower_ret2 = p6:lower();
	local v5 = table1[2];
	local v6 = v5[lower_ret2];
	if not v6 then
		v6 = Instance.new(table2[2]);
		v6.Parent = script;
		v5[lower_ret2] = v6;
	end
	return v6;
end
function u1.Fire(p7, ...) -- Line: 249
	--[[
		Upvalues:
			[1] = IsServer_ret
			[2] = u1
			[3] = table1
			[4] = table2
	--]]
	if not true then return end
	p7 = string.lower(p7);
	if not IsServer_ret and p7:lower() ~= "core signal fired" then
		u1.Fire("CORE Signal Fired", p7);
	end
	
	local v7 = p7;
	assert(true);
	assert(typeof(v7) == "string");
	local lower_ret3 = v7:lower();
	if Debug then
		print("Signal Debug .Fire | ".. lower_ret3)
	end
	local v8 = table1[1];
	local v9 = v8[lower_ret3];
	if not v9 then
		v9 = Instance.new(table2[1]);
		v9.Parent = script;
		v8[lower_ret3] = v9;
	end
	local v10 = v9;
	v10:Fire(...);
end
function u1.Fired(p8) -- Line: 260
	--[[
		Upvalues:
			[1] = table1
			[2] = table2
	--]]
	if not true then
		return Instance.new("BindableEvent").Event;
	end
	assert(true);
	assert(typeof(p8) == "string");
	local lower_ret4 = p8:lower();
	if Debug then
		print("Signal Debug .Fired | ".. lower_ret4)
	end
	
	local v11 = table1[1];
	local v12 = v11[lower_ret4];
	if not v12 then
		v12 = Instance.new(table2[1]);
		v12.Parent = script;
		v11[lower_ret4] = v12;
	end
	return v12.Event;
end
function u1.Invoke(p9, ...) -- Line: 265
	--[[
		Upvalues:
			[1] = IsServer_ret
			[2] = u1
			[3] = table1
			[4] = table2
	--]]
	if not true then return end
	if not IsServer_ret and p9:lower() ~= "core signal fired" then
		u1.Fire("CORE Signal Fired", p9);
	end
	assert(true);
	assert(typeof(p9) == "string");
	local lower_ret5 = p9:lower();
	if Debug then
		print("Signal Debug .Invoke | ".. lower_ret5)
	end
	local v13 = table1[2];
	local v14 = v13[lower_ret5];
	if not v14 then
		v14 = Instance.new(table2[2]);
		v14.Parent = script;
		v13[lower_ret5] = v14;
	end
	local v15 = v14;
	return v15:Invoke(...);
end
function u1.Invoked(p10) -- Line: 275
	--[[
		Upvalues:
			[1] = table1
			[2] = table2
	--]]
	if not true then
		return Instance.new("BindableFunction");
	end
	assert(true);
	assert(typeof(p10) == "string");
	local lower_ret6 = p10:lower();
	if Debug then
		print("Signal Debug .Invoked | ".. lower_ret6)
	end
	local v16 = table1[2];
	local v17 = v16[lower_ret6];
	if not v17 then
		v17 = Instance.new(table2[2]);
		v17.Parent = script;
		v16[lower_ret6] = v17;
	end
	return v17;
end
function u1.Get(p11) -- Line: 280
	--[[
		Upvalues:
			[1] = table1
			[2] = table2
	--]]
	if not true then
		return Instance.new("BindableEvent");
	end
	assert(true);
	assert(typeof(p11) == "string");
	local lower_ret7 = p11:lower();
	local v18 = table1[1];
	local v19 = v18[lower_ret7];
	if not v19 then
		v19 = Instance.new(table2[1]);
		v19.Parent = script;
		v18[lower_ret7] = v19;
	end
	return v19;
end
table.freeze(u1);
if game:GetService("RunService"):IsClient() then
	task.spawn(function(p14) -- Line: 290
		local table_clone_ret2 = table.clone(p14);
		setmetatable(table_clone_ret2, nil);
		local v23 = getmetatable(p14);
		if v23 then
			v23 = table.clone(v23);
		end
		local function check(p18, p19) -- Line: 298
			if p18 ~= p19 then
				if typeof(p18) ~= "table" or typeof(p19) ~= "table" then
					return false;
				end
				for key2, val2 in next, p19 do
					if rawget(p18, key2) == val2 then continue end
					return false;
				end
			end
			return true;
		end
		local function _warn(p20) -- Line: 313
			if not pcall(_G.Blunder, Enum.MessageType.MessageWarning, p20) then
				warn(p20);
			end
		end
		while check(getmetatable(p14), v23) and check(p14, table_clone_ret2) do
			task.wait(math.random() * 15 + 1);
		end
		if not pcall(_G.Blunder, Enum.MessageType.MessageWarning, "ExternalModification : Signal") then
			warn("ExternalModification : Signal");
		end
	end, u1);
end
task.spawn(function(p12) -- Line: 330
	--[[
		Upvalues:
			[1] = IsStudio_ret
	--]]
	local v20 = p12();
	local table_clone_ret = table.clone(v20);
	setmetatable(table_clone_ret, nil);
	local v21 = getmetatable(v20);
	if v21 then
		v21 = table.clone(v21);
	end
	local function _compare(p15, p16) -- Line: 339
		if p15 ~= p16 then
			if typeof(p15) ~= "table" or typeof(p16) ~= "table" then
				return false;
			end
			for key1, val1 in next, p16 do
				if rawget(p15, key1) == val1 then continue end
				return false;
			end
		end
		return true;
	end
	local function _warn(p17) -- Line: 354
		--[[
			Upvalues:
				[1] = IsStudio_ret
		--]]
		if IsStudio_ret or not pcall(_G.Blunder, Enum.MessageType.MessageWarning, p17) then
			warn(p17);
		end
	end
	while true do
		local v25 = p12();
		if not _compare(getmetatable(v25), v21) or not _compare(v25, table_clone_ret) then break end
		task.wait(math.random() * 15 + 1);
	end
	if IsStudio_ret or not pcall(_G.Blunder, Enum.MessageType.MessageWarning, "ExternalModification : Signal Env") then
		warn("ExternalModification : Signal Env");
	end
end, function() -- Line: 368
	--[[
		Upvalues:
			[1] = ReplicatedStorage
			[2] = IsStudio_ret
			[3] = IsServer_ret
			[4] = _check
			[5] = _getName
			[6] = _event
			[7] = _function
	--]]
	local table3 = {
		ReplicatedStorage,
		false,
		IsStudio_ret,
		IsServer_ret,
		_check,
		1,
		2,
		_getName,
		_event,
		_function
	};
	return table3;
end);
u1 = (function(p13) -- Line: 384
	return setmetatable({}, {
		__index = function(_, p21) -- __index (Line: 384)
			--[[
				Upvalues:
					[1] = p13
			--]]
			return p13[p21];
		end,
		__newindex = function(_, _, _) -- __newindex (Line: 384)
		end,
		__metatable = {}
	});
end)(u1);
return u1;
