-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Eggs = {
		Amount = 1000, 
		Tier = "Easy", 
		Egg = {
			Pattern = "Alien"
		}
	}, 
	GiantAlienChest = {
		Amount = 500, 
		Description = "Break {Amount} Giant Alien Chests", 
		Tier = "Medium"
	}, 
	DarkMatter = {
		Amount = 25, 
		Tier = "Hard", 
		Description = "Use the Dark Matter Machine {Amount} times on Secret pets!"
	}
};
