-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Coins = {
		Amount = 2500, 
		Tier = "Easy", 
		Coin = {
			Pattern = "Coin"
		}
	}, 
	Coins2 = {
		Amount = 500, 
		Tier = "Medium", 
		Coin = {
			Pattern = "Vault"
		}
	}, 
	Eggs = {
		Amount = 25, 
		Tier = "Hard", 
		Description = "Hatch {Amount} Shiny Dominus Alienus pets from the Chemical Eggs!", 
		Egg = {
			Pattern = "Chemical", 
			Pet = "209", 
			Attributes = {
				sh = true
			}
		}
	}
};
