-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Coins = {
		Amount = 750, 
		Tier = "Easy", 
		Coin = {
			Pattern = "Crate"
		}
	}, 
	Eggs = {
		Amount = 5000, 
		Tier = "Medium", 
		Egg = {
			Pattern = { "Dark Tech", "Titanium" }, 
			PatternDescription = "Dark Tech"
		}
	}, 
	DarkMatter = {
		Amount = 100, 
		Tier = "Hard", 
		Description = "Use the Dark Matter Machine {Amount} times!"
	}
};
