-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Coins = {
		Amount = 750, 
		Tier = "Easy", 
		Coin = {
			Pattern = "Present"
		}
	}, 
	DarkMatter = {
		Amount = 50, 
		Tier = "Medium", 
		Description = "Use the Dark Matter Machine {Amount} times on Glitch Egg pets!"
	}, 
	FreeGifts = {
		Amount = 100, 
		Tier = "Hard", 
		Description = "Claim {Amount} Free Gifts!"
	}
};
