-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Enchant = {
		Amount = 1000, 
		Tier = "Easy", 
		Description = "Enchant {Amount} Pixel Wolves!"
	}, 
	Chests = {
		Amount = 750, 
		Tier = "Medium", 
		Coin = {
			Pattern = "Giant Pixel Chest"
		}
	}, 
	Eggs2 = {
		Amount = 1000, 
		Tier = "Hard", 
		Description = "Hatch {Amount} Mythicals from Rainbow Pixel Eggs!"
	}
};
