-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	["More Diamonds"] = {
		title = "More Diamonds", 
		currency = "Diamonds", 
		icon = "rbxassetid://7056089501", 
		prices = { 7500, 30000, 90000, 240000, 500000 }
	}, 
	["Player Walkspeed"] = {
		title = "Player Speed", 
		currency = "Diamonds", 
		icon = "rbxassetid://7056089609", 
		prices = { 1500, 6000, 15000, 25000, 75000 }
	}, 
	["Pet Storage"] = {
		title = "More Storage", 
		currency = "Diamonds", 
		icon = "rbxassetid://7056089976", 
		prices = { 3000, 5000, 7000, 11000, 15000 }
	}, 
	["Orb Pickup Distance"] = {
		title = "Orbs Reach", 
		currency = "Diamonds", 
		icon = "rbxassetid://7056089728", 
		prices = { 3000, 7000, 15000, 30000, 50000 }
	}, 
	["Pet Walkspeed"] = {
		title = "Brainrot Speed", 
		currency = "Diamonds", 
		icon = "rbxassetid://7056089832", 
		prices = { 2000, 5000, 15000, 25000, 40000 }
	}, 
	["Pet Strength"] = {
		title = "Brainrot Strength", 
		currency = "Diamonds", 
		icon = "rbxassetid://7056090073", 
		prices = { 5000, 10000, 40000, 80000, 750000 }
	}, 
	["Halloween More Candy"] = {
		title = "More Candy", 
		currency = "Halloween Candy", 
		icon = "rbxassetid://7878227066", 
		isHalloweenEvent = true, 
		prices = { 2500000, 12000000, 47500000, 175000000, 450000000 }
	}, 
	["Halloween More Diamonds"] = {
		title = "More Diamonds", 
		currency = "Halloween Candy", 
		icon = "rbxassetid://7056089501", 
		isHalloweenEvent = true, 
		prices = { 2000000, 9500000, 32500000, 90000000, 175000000 }
	}, 
	["Halloween Pet Storage"] = {
		title = "More Storage", 
		currency = "Halloween Candy", 
		icon = "rbxassetid://7878226631", 
		isHalloweenEvent = true, 
		prices = { 500000, 1250000, 4500000, 11000000, 35000000 }
	}, 
	["Halloween Better Enchants"] = {
		title = "Better Re-Enchants", 
		currency = "Halloween Candy", 
		icon = "rbxassetid://7878227199", 
		isHalloweenEvent = true, 
		prices = { 1250000, 4750000, 12500000, 35000000, 70000000 }
	}, 
	["Halloween Legendary Pets"] = {
		title = "Legendary Pets Chance", 
		currency = "Halloween Candy", 
		icon = "rbxassetid://7878226947", 
		isHalloweenEvent = true, 
		prices = { 1750000, 6000000, 25000000, 110000000, 300000000 }
	}, 
	["Halloween Mythical Pets"] = {
		title = "Mythical Pets Chance", 
		currency = "Halloween Candy", 
		icon = "rbxassetid://7878226819", 
		isHalloweenEvent = true, 
		prices = { 8000000, 32500000, 115000000, 375000000, 1000000000 }
	}
};
