return {
	Noob = {
		title = "Noob", 
		needed = 40000, 
		productId = 3288471475, 
		rewardCooldown = 0, 
		rewards = { { "Diamonds", 5000 }, { "Super Lucky Boost", 1 } }
	}, 
	["Just Got In"] = {
		title = "Just Got In", 
		needed = 200000, 
		productId = 3288471475, 
		rewardCooldown = 0, 
		rewards = { { "Diamonds", 7500 },{ "Super Lucky Boost", 1 }, { "Triple Damage Boost", 1 } }
	}, 
	["Average Enjoyer"] = {
		title = "Average Enjoyer", 
		needed = 1000000, 
		productId = 3288471475, 
		rewardCooldown = 28800, 
		rewards = { { "Diamonds", 10000 },{ "Super Lucky Boost", 3 }, { "Triple Damage Boost", 3 } }
	}, 
	["Weekender Warrior"] = {
		title = "Weekender Warrior", 
		needed = 5000000, 
		productId = 3288471476, 
		rewardCooldown = 28800, 
		rewards = { { "Diamonds", 15000 },{ "Super Lucky Boost", 5 }, { "Triple Damage Boost", 5 } }
	}, 
	["Roblox Technician"] = {
		title = "Roblox Technician", 
		needed = 25000000, 
		productId = 3288471476, 
		rewardCooldown = 28800, 
		rewards = { { "Diamonds", 25000 },{ "Super Lucky Boost", 7 }, { "Triple Damage Boost", 7 } }
	}, 
	["Trippi Hero"] = {
		title = "Trippi Hero", 
		needed = 163840000, 
		productId = 3288471476, 
		rewardCooldown = 28800, 
		rewards = { { "Diamonds", 30000 }, { "Super Lucky Boost", 25 } }
	}, 
	["Bombardino Main"] = {
		title = "Bombardino Main", 
		needed = 655360000, 
		productId = 3288471471, 
		rewardCooldown = 28800, 
		rewards = { { "Diamonds", 45000 }, { "Super Lucky Boost", 50 } }
	}, 
	["Dumpster Lord"] = {
		title = "Dumpster Lord", 
		needed = 2621440000, 
		productId = 3288471471, 
		rewardCooldown = 28800, 
		rewards = { { "Diamonds", 60000 }, { "Super Lucky Boost", 5 }, { "Triple Damage Boost", 5 } }
	}, 
	["Capuchino Ultra"] = {
		title = "Capuchino Ultra", 
		needed = 10485760000, 
		productId = 3288471471, 
		rewardCooldown = 21600, 
		rewards = { { "Diamonds", 75000 }, { "Super Lucky Boost", 5 }, { "Triple Damage Boost", 5 } }
	}, 
	Udindindindin = {
		title = "Udindindindin", 
		needed = 52428800000, 
		productId = 3288471471, 
		rewardCooldown = 18000, 
		rewards = { { "Diamonds", 125000 }, { "Triple Coins Boost", 5 }, { "Super Lucky Boost", 5 }, { "Triple Damage Boost", 5 } }
	}, 
	["Garam Ascended"] = {
		title = "Garam Ascended", 
		needed = 419430400000, 
		productId = 3288471471, 
		rewardCooldown = 18000, 
		rewards = { { "Diamonds", 145000 }, { "Triple Coins Boost", 10 }, { "Super Lucky Boost", 20 }, { "Triple Damage Boost", 10 } }
	}, 
	["Tralalero Ultra"] = {
		title = "Tralalero Ultra", 
		needed = 13421772800000, 
		productId = 3288471471, 
		rewardCooldown = 18000, 
		rewards = { { "Diamonds", 200000 }, { "Triple Coins Boost", 10 }, { "Super Lucky Boost", 20 }, { "Triple Damage Boost", 20 } }
	}, 
	["Chimpanzini.exe"] = {
		title = "Chimpanzini.exe", 
		needed = 429496729600000, 
		productId = 3288471468, 
		rewardCooldown = 18000, 
		rewards = { { "Diamonds", 350000 }, { "Triple Coins Boost", 10 }, { "Super Lucky Boost", 20 }, { "Triple Damage Boost", 20 }, { "Ultra Lucky Boost", 10 } }
	}, 
	["Sahur Gold"] = {
		title = "Sahur Gold", 
		needed = 13743895347200000, 
		productId = 3288471468, 
		rewardCooldown = 16200, 
		rewards = { { "Diamonds", 500000 }, { "Triple Coins Boost", 20 }, { "Super Lucky Boost", 20 }, { "Triple Damage Boost", 20 }, { "Ultra Lucky Boost", 10 } }
	}, 
	["Peak Fiction"] = {
		title = "Peak Fiction", 
		needed = 8.796093022208E+17, 
		productId = 3288471468, 
		rewardCooldown = 14400, 
		rewards = { { "Diamonds", 1000000 }, { "Triple Coins Boost", 20 }, { "Super Lucky Boost", 20 }, { "Triple Damage Boost", 20 }, { "Ultra Lucky Boost", 20 } }
	}, 
	["Fiction Overload"] = {
		title = "Fiction Overload", 
		needed = 1.125899906842624E+20, 
		productId = 3288471468, 
		rewardCooldown = 14400, 
		rewards = { { "Diamonds", 1500000 }, { "Triple Coins Boost", 20 }, { "Super Lucky Boost", 20 }, { "Triple Damage Boost", 20 }, { "Ultra Lucky Boost", 20 } }
	}, 
	["Brainrot Overdrive"] = {
		title = "Brainrot Overdrive", 
		needed = 7.205759403792794E+21, 
		productId = 3288471470, 
		rewardCooldown = 12600, 
		rewards = { { "Diamonds", 1500000 }, { "Triple Coins Boost", 30 }, { "Super Lucky Boost", 20 }, { "Triple Damage Boost", 20 }, { "Ultra Lucky Boost", 20 } }
	}, 
	["Lord of Memes"] = {
		title = "Lord of Memes", 
		needed = 4.611686018427388E+23, 
		productId = 3288471470, 
		rewardCooldown = 12600, 
		rewards = { { "Diamonds", 1500000 }, { "Triple Coins Boost", 30 }, { "Super Lucky Boost", 30 }, { "Triple Damage Boost", 20 }, { "Ultra Lucky Boost", 20 } }
	}, 
	["Collector of Creatures"] = {
		title = "Collector of Creatures", 
		needed = 1.4757395258967641E+25, 
		productId = 3288471470, 
		rewardCooldown = 12600, 
		rewards = { { "Diamonds", 2500000 }, { "Triple Coins Boost", 30 }, { "Super Lucky Boost", 30 }, { "Triple Damage Boost", 30 }, { "Ultra Lucky Boost", 30 } }
	}, 
	["Trash Deity"] = {
		title = "Trash Deity", 
		needed = 0, 
		productId = 0, 
		rewardCooldown = 12600, 
		rewards = { { "Diamonds", 12500000 }, { "Triple Coins Boost", 400 }, { "Super Lucky Boost", 300 }, { "Triple Damage Boost", 300 }, { "Ultra Lucky Boost", 300 } }
	}
};
