-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Diamond = {
		Amount = 250, 
		Tier = "Easy", 
		Coin = {
			Pattern = "Diamond"
		}
	}, 
	Eggs = {
		Amount = 300, 
		Tier = "Medium", 
		Egg = {
			Area = script.Name, 
			Pattern = "Spiked", 
			Rarity = "Epic"
		}
	}, 
	Daycare = {
		Amount = 50, 
		Tier = "Hard", 
		Description = "Use the Daycare {Amount} times!"
	}
};
