-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Presents = {
		Amount = 200, 
		Tier = "Easy", 
		Coin = {
			Pattern = "Present"
		}
	}, 
	Upgrades = {
		Amount = 30, 
		Tier = "Medium", 
		Description = "Max out your player upgrades!"
	}, 
	Eggs = {
		Amount = 10000, 
		Tier = "Hard", 
		Egg = {
			Pattern = { "Grass", "Wood" }, 
			PatternDescription = "Forest"
		}
	}
};
