-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Eggs = {
		Amount = 500, 
		Tier = "Easy", 
		Egg = {
			Pattern = { "Rock", "Geode" }, 
			PatternDescription = "Mine"
		}
	}, 
	Rainbow = {
		Amount = 100, 
		Tier = "Medium", 
		Description = "Use the Rainbow Machine {Amount} times successfully!"
	}, 
	Vaults = {
		Amount = 750, 
		Tier = "Hard", 
		Coin = {
			Pattern = "Vault"
		}
	}
};
