-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Crates = {
		Amount = 300, 
		Tier = "Easy", 
		Coin = {
			Pattern = "Crate"
		}
	}, 
	Eggs = {
		Amount = 20, 
		Tier = "Medium", 
		Egg = {
			Pattern = { "Ice", "Snow" }, 
			PatternDescription = "Winter", 
			Attributes = {
				sh = true
			}
		}
	}, 
	Chests = {
		Amount = 1000, 
		Tier = "Hard", 
		Coin = {
			Pattern = "Chest"
		}
	}
};
