-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Spend = {
		Amount = 10000000000, 
		Tier = "Easy", 
		Description = "Spend {Amount.Short} Rainbow Coins on Shiny Axolotl Eggs!"
	}, 
	Eggs = {
		Amount = 500, 
		Tier = "Medium", 
		Description = "Hatch {Amount} Mythical Pets from Shiny Axolotl Eggs!"
	}, 
	Chests = {
		Amount = 1500, 
		Tier = "Hard", 
		Coin = {
			Pattern = "Giant Ocean Chest"
		}
	}
};
