-- Como sou pouco e sei pouco faço pouco que me cabe dado por inteiro

return {
	Eggs = {
		Amount = 1000, 
		Tier = "Easy", 
		Egg = {
			Pattern = "Axolotl"
		}
	}, 
	Presents = {
		Amount = 1000, 
		Tier = "Medium", 
		Coin = {
			Pattern = "Present"
		}
	}, 
	Eggs2 = {
		Amount = 750, 
		Tier = "Hard", 
		Description = "Hatch {Amount} Mythicals from Axolotl Eggs!", 
		Egg = {
			Pattern = "Axolotl", 
			Rarity = "Mythical"
		}
	}
};
