-- its june and i making a game instead study for my entrance exame
local v7 = require(game.ReplicatedStorage.Library.Modules.Pets)
local v8 = {
	["Upgrades"] =  {
		["Yeet Egg Luck"] = {
			[1] = 1, [2] = 2, [3] = 3, [4] = 4, [5] = 5, [6] = 6, [7] = 7, [8] = 8, 
			[9] = 9, [10] = 10
		},
		["Yeet Egg Price"] =  {
			0.95, 0.9 ,0.85, 0.8, 0.75, 0.7, 0.65, 0.55, 0.5
		},
		["Yeet Orb Power"] = {
			[1] = 100, [2] = 250, [3] = 500, [4] = 800, [5] = 1000, [6] = 1500, [7] = 2500, [8] = 3500, 
			[9] = 3500, [10] = 4000
		}
	}
}
return v8
