local Data = {{
	waitTime = 300, 
	rare = false, 
	rewardNum = { 1, 1 }, 
	rewards = { { "Coins", 10 }, { "Diamonds", 90 } }, 
	icon = "rbxassetid://75464300248025", 
	masteryXP = 250
}, {
	waitTime = 600, 
	rare = false, 
	rewardNum = { 1, 2 }, 
	rewards = { { "Coins", 10 }, { "Diamonds", 80 }, { "Boosts", 10 } }, 
	icon = "rbxassetid://75464300248025", 
	masteryXP = 350
}, {
	waitTime = 900, 
	rare = false, 
	rewardNum = { 1, 2 }, 
	rewards = { { "Coins", 15 }, { "Diamonds", 70 }, { "Boosts", 15 } }, 
	icon = "rbxassetid://75464300248025", 
	masteryXP = 400
}, {
	waitTime = 1200, 
	rare = false, 
	rewardNum = { 2, 2 }, 
	rewards = { { "Coins", 20 }, { "Diamonds", 50 }, { "Boosts", 20 }, { "CoinsJumbo", 1 }, { "DiamondsJumbo", 4 }, { "BoostsRare", 4 } }, 
	icon = "rbxassetid://131657705103348", 
	masteryXP = 500
}, {
	waitTime = 1800, 
	rare = false, 
	rewardNum = { 2, 3 }, 
	rewards = { { "Coins", 25 }, { "Diamonds", 40 }, { "Boosts", 25 }, { "CoinsJumbo", 5 }, { "DiamondsJumbo", 2.5 }, { "BoostsRare", 2.5 } }, 
	icon = "rbxassetid://131657705103348", 
	masteryXP = 700
}, {
	waitTime = 2400, 
	rare = false, 
	rewardNum = { 3, 3 }, 
	rewards = { { "Coins", 30 }, { "Diamonds", 30 }, { "Boosts", 30 }, { "CoinsJumbo", 5 }, { "DiamondsJumbo", 4 }, { "BoostsRare", 1 } }, 
	icon = "rbxassetid://131657705103348", 
	masteryXP = 800
}, {
	waitTime = 3000, 
	rare = false, 
	rewardNum = { 3, 3 }, 
	rewards = { { "Coins", 40 }, { "Diamonds", 20 }, { "Boosts", 25 }, { "CoinsJumbo", 5 }, { "DiamondsJumbo", 5 }, { "BoostsRare", 5 } }, 
	icon = "rbxassetid://131657705103348", 
	masteryXP = 1000
}, {
	waitTime = 3600, 
	rare = false, 
	rewardNum = { 3, 4 }, 
	rewards = { { "Coins", 90 }, { "Diamonds", 60 }, { "Boosts", 30 }, { "CoinsJumbo", 12.5 }, { "DiamondsJumbo", 10 }, { "BoostsRare", 10 } }, 
		icon = "rbxassetid://80267891812838", 
	masteryXP = 1200
}, {
	waitTime = 4500, 
	rare = false, 
	rewardNum = { 3, 4 }, 
	rewards = { { "Coins", 80 }, { "Diamonds", 60 }, { "Boosts", 30 }, { "CoinsJumbo", 20 }, { "DiamondsJumbo", 15 }, { "BoostsRare", 12.5 } }, 
		icon = "rbxassetid://80267891812838", 
	masteryXP = 1400
}, {
	waitTime = 5400, 
	rare = false, 
	rewardNum = { 4, 4 }, 
	rewards = { { "Diamonds", 60 }, { "Boosts", 25 }, { "CoinsJumbo", 20 }, { "DiamondsJumbo", 15 }, { "BoostsRare", 15 } }, 
		icon = "rbxassetid://80267891812838", 
	masteryXP = 1800
}, {
	waitTime = 7200, 
	rare = true, 
	rewardNum = { 5, 5 }, 
	rewards = { { "Diamonds", 30 }, { "Boosts", 15 }, { "CoinsJumbo", 20 }, { "DiamondsJumbo", 15 }, { "BoostsRare", 10 }, { "HugePet", 0.000000000000000001 } }, 
		icon = "rbxassetid://108787149226601", 
	masteryXP = 2800
}, {
	waitTime = 10800, 
	rare = true, 
	rewardNum = { 6, 6 }, 
	rewards = { { "Diamonds", 30 }, { "CoinsJumbo", 20 }, { "DiamondsJumbo", 15 }, { "BoostsRare", 10 }, { "HugePet", 0.0000000000001 } }, 
		icon = "rbxassetid://108787149226601", 
	masteryXP = 4000
}}

return Data
